// This file is auto-generated by @hey-api/openapi-ts

export const CreateUserRequestSchema = {
    type: 'object',
    required: [
        'username',
        'display_name',
        'email',
        'password'
    ],
    properties: {
        username: {
            $ref: '#/components/schemas/Username'
        },
        display_name: {
            $ref: '#/components/schemas/DisplayName'
        },
        email: {
            type: 'string',
            format: 'email',
            example: 'user@example.com'
        },
        password: {
            $ref: '#/components/schemas/Password'
        }
    }
} as const;

export const AuthRequestSchema = {
    type: 'object',
    required: [
        'username',
        'password'
    ],
    properties: {
        username: {
            $ref: '#/components/schemas/Username'
        },
        password: {
            $ref: '#/components/schemas/Password'
        }
    }
} as const;

export const UpdateProfileRequestSchema = {
    type: 'object',
    anyOf: [
        {
            required: [
                'display_name'
            ]
        },
        {
            required: [
                'username'
            ]
        },
        {
            required: [
                'email'
            ]
        }
    ],
    properties: {
        display_name: {
            $ref: '#/components/schemas/DisplayName'
        },
        username: {
            type: 'string',
            minLength: 3,
            maxLength: 32,
            pattern: '^[a-z0-9_-]+$'
        },
        email: {
            type: 'string',
            format: 'email'
        }
    }
} as const;

export const ChangePasswordRequestSchema = {
    type: 'object',
    required: [
        'current_password',
        'password'
    ],
    properties: {
        current_password: {
            type: 'string'
        },
        password: {
            type: 'string',
            minLength: 8,
            maxLength: 72
        }
    }
} as const;

export const CreateDeviceRequestSchema = {
    type: 'object',
    required: [
        'name'
    ],
    properties: {
        name: {
            type: 'string',
            example: 'Personal phone',
            minLength: 1,
            maxLength: 50,
            description: 'User-friendly name for the device'
        }
    }
} as const;

export const AddAddressRequestSchema = {
    required: [
        'ip'
    ],
    type: 'object',
    properties: {
        ip: {
            $ref: '#/components/schemas/IPAddress'
        }
    }
} as const;

export const DeviceHeartbeatByApiKeyRequestSchema = {
    type: 'object',
    properties: {
        ip: {
            $ref: '#/components/schemas/IPAddress'
        }
    }
} as const;

export const CreateDeviceResponseSchema = {
    type: 'object',
    required: [
        'device',
        'api_key'
    ],
    properties: {
        device: {
            $ref: '#/components/schemas/Device'
        },
        api_key: {
            type: 'string',
            description: 'Secret key for the device; only returned on creation or regeneration.'
        }
    }
} as const;

export const ErrorResponseSchema = {
    type: 'object',
    properties: {
        error: {
            type: 'string',
            example: 'device not found'
        }
    }
} as const;

export const AddressHistoryResponseSchema = {
    type: 'object',
    required: [
        'buckets',
        'events',
        'total_events'
    ],
    properties: {
        buckets: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/AddressHistoryBucket'
            }
        },
        events: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/AddressHistoryEvent'
            }
        },
        total_events: {
            type: 'integer',
            description: 'Total number of events matching the filters (for pagination)'
        },
        next_cursor: {
            allOf: [
                {
                    $ref: '#/components/schemas/ID'
                }
            ],
            nullable: true
        }
    }
} as const;

export const AddressHistoryBucketSchema = {
    type: 'object',
    required: [
        'timestamp',
        'active_count',
        'event_count'
    ],
    properties: {
        timestamp: {
            type: 'string',
            format: 'date-time',
            'x-go-type': 'UTCTime'
        },
        active_count: {
            type: 'integer',
            description: 'Maximum active IPs seen in this time bucket'
        },
        event_count: {
            type: 'integer',
            description: 'Total address events in this time bucket'
        }
    }
} as const;

export const AddressHistoryEventSchema = {
    type: 'object',
    required: [
        'id',
        'timestamp',
        'ip',
        'is_enabled',
        'source',
        'device_id',
        'device_name'
    ],
    properties: {
        id: {
            $ref: '#/components/schemas/ID'
        },
        timestamp: {
            type: 'string',
            format: 'date-time',
            'x-go-type': 'UTCTime'
        },
        ip: {
            type: 'string',
            description: 'IP address'
        },
        is_enabled: {
            type: 'boolean',
            description: 'Whether the address was enabled or disabled'
        },
        source: {
            type: 'string',
            enum: [
                'heartbeat',
                'manual',
                'expiry'
            ],
            description: 'What triggered the state change'
        },
        device_id: {
            $ref: '#/components/schemas/ID'
        },
        device_name: {
            type: 'string',
            description: 'Name of the device'
        }
    }
} as const;

export const UserSchema = {
    type: 'object',
    required: [
        'id',
        'username',
        'display_name',
        'email',
        'role',
        'must_change_password',
        'created_at'
    ],
    properties: {
        id: {
            $ref: '#/components/schemas/ID'
        },
        username: {
            $ref: '#/components/schemas/Username'
        },
        display_name: {
            $ref: '#/components/schemas/DisplayName'
        },
        email: {
            type: 'string',
            format: 'email'
        },
        role: {
            $ref: '#/components/schemas/UserRole',
            readOnly: true
        },
        must_change_password: {
            type: 'boolean',
            readOnly: true,
            description: 'When true, the user must change their password before using the app.'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            'x-go-type': 'UTCTime'
        }
    }
} as const;

export const DeviceSchema = {
    type: 'object',
    required: [
        'id',
        'name',
        'created_at',
        'api_key_prefix'
    ],
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time',
            'x-go-type': 'UTCTime'
        },
        id: {
            $ref: '#/components/schemas/ID'
        },
        name: {
            description: 'User-friendly name for the device',
            type: 'string',
            minLength: 1,
            maxLength: 50
        },
        api_key_prefix: {
            type: 'string',
            description: 'Prefix of the device API key (for display only).'
        },
        address_count: {
            type: 'integer',
            minimum: 0,
            readOnly: true,
            description: 'Number of currently enabled addresses for this device.'
        },
        last_seen_at: {
            type: 'string',
            format: 'date-time',
            nullable: true,
            readOnly: true,
            'x-go-type': 'UTCTime',
            description: 'Most recent address activity for this device (heartbeat or manual update).'
        }
    }
} as const;

export const AddressSchema = {
    type: 'object',
    required: [
        'id',
        'device_id',
        'ip',
        'is_enabled',
        'created_at',
        'updated_at'
    ],
    properties: {
        id: {
            $ref: '#/components/schemas/ID'
        },
        device_id: {
            $ref: '#/components/schemas/ID'
        },
        ip: {
            $ref: '#/components/schemas/IPAddress'
        },
        is_enabled: {
            type: 'boolean',
            description: 'The latest state of this address, enabled or disabled'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            'x-go-type': 'UTCTime'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            'x-go-type': 'UTCTime',
            description: 'Last time it was enabled or disabled'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            'x-go-type': 'UTCTime',
            nullable: true,
            readOnly: true,
            description: 'UTC timestamp when this address will auto-expire, if an auto-expiry rule is enabled for the device. Null if no expiry is scheduled.\n'
        }
    }
} as const;

export const AccessLogResponseSchema = {
    type: 'object',
    required: [
        'total',
        'next_cursor',
        'rows'
    ],
    properties: {
        total: {
            type: 'integer',
            description: 'Total rows matching the current filters (excludes cursor, useful for "N results" UI)'
        },
        next_cursor: {
            allOf: [
                {
                    $ref: '#/components/schemas/ID'
                }
            ],
            nullable: true
        },
        rows: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/AccessLogRow'
            }
        }
    }
} as const;

export const AccessLogCountryStatsSchema = {
    type: 'object',
    required: [
        'country_code',
        'total',
        'allowed',
        'denied'
    ],
    properties: {
        country_code: {
            type: 'string'
        },
        country_name: {
            type: 'string'
        },
        continent_code: {
            type: 'string'
        },
        total: {
            type: 'integer'
        },
        allowed: {
            type: 'integer'
        },
        denied: {
            type: 'integer'
        }
    }
} as const;

export const AccessLogRowSchema = {
    type: 'object',
    required: [
        'id',
        'created_at',
        'outcome',
        'client_ip',
        'headers'
    ],
    properties: {
        id: {
            $ref: '#/components/schemas/ID'
        },
        client_ip: {
            $ref: '#/components/schemas/IPAddress'
        },
        outcome: {
            type: 'boolean'
        },
        deny_reason: {
            type: 'string'
        },
        device_id: {
            $ref: '#/components/schemas/ID'
        },
        device_name: {
            type: 'string'
        },
        address_id: {
            $ref: '#/components/schemas/ID'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            'x-go-type': 'UTCTime'
        },
        xff_chain: {
            type: 'string'
        },
        target_host: {
            type: 'string'
        },
        target_uri: {
            type: 'string'
        },
        http_method: {
            type: 'string'
        },
        country_code: {
            type: 'string',
            description: 'ISO 3166-1 alpha-2, e.g. "DE"'
        },
        country_name: {
            type: 'string',
            description: 'e.g. "Germany"'
        },
        continent_code: {
            type: 'string',
            description: 'e.g. "EU"'
        },
        asn: {
            type: 'integer',
            description: 'Autonomous System Number'
        },
        asn_org: {
            type: 'string',
            description: 'e.g. "Cloudflare, Inc."'
        },
        headers: {
            type: 'object',
            additionalProperties: {
                type: 'array',
                items: {
                    type: 'string'
                }
            }
        }
    }
} as const;

export const DeviceAddressLeaseRuleSchema = {
    type: 'object',
    required: [
        'id',
        'device_id',
        'enabled',
        'ttl_seconds',
        'created_at',
        'updated_at'
    ],
    properties: {
        id: {
            $ref: '#/components/schemas/ID'
        },
        device_id: {
            $ref: '#/components/schemas/ID'
        },
        enabled: {
            type: 'boolean',
            description: 'Whether the lease rule is active'
        },
        ttl_seconds: {
            type: 'integer',
            minimum: 1,
            description: 'Seconds after which an enabled device address lease expires'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            'x-go-type': 'UTCTime'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            'x-go-type': 'UTCTime'
        }
    }
} as const;

export const PutDeviceAddressLeaseRuleRequestSchema = {
    type: 'object',
    required: [
        'ttl_seconds'
    ],
    properties: {
        ttl_seconds: {
            type: 'integer',
            minimum: 1,
            description: 'Seconds after which an enabled device address lease expires'
        }
    }
} as const;

export const DashboardStatsSchema = {
    type: 'object',
    required: [
        'total_requests',
        'allowed_count',
        'denied_count',
        'unique_ips'
    ],
    properties: {
        total_requests: {
            type: 'integer',
            format: 'int64'
        },
        allowed_count: {
            type: 'integer',
            format: 'int64'
        },
        denied_count: {
            type: 'integer',
            format: 'int64'
        },
        unique_ips: {
            type: 'integer',
            format: 'int64'
        }
    }
} as const;

export const DashboardTrafficBucketSchema = {
    type: 'object',
    required: [
        'timestamp',
        'allow_count',
        'deny_count'
    ],
    properties: {
        timestamp: {
            type: 'string',
            format: 'date-time',
            'x-go-type': 'UTCTime'
        },
        allow_count: {
            type: 'integer',
            format: 'int64'
        },
        deny_count: {
            type: 'integer',
            format: 'int64'
        }
    }
} as const;

export const DashboardTrafficResponseSchema = {
    type: 'object',
    required: [
        'buckets'
    ],
    properties: {
        buckets: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/DashboardTrafficBucket'
            }
        }
    }
} as const;

export const DashboardServiceCountSchema = {
    type: 'object',
    required: [
        'host',
        'allow_count',
        'deny_count'
    ],
    properties: {
        host: {
            type: 'string'
        },
        allow_count: {
            type: 'integer',
            format: 'int64'
        },
        deny_count: {
            type: 'integer',
            format: 'int64'
        }
    }
} as const;

export const DashboardServicesResponseSchema = {
    type: 'object',
    required: [
        'services'
    ],
    properties: {
        services: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/DashboardServiceCount'
            }
        }
    }
} as const;

export const DashboardTopDeniedIpSchema = {
    type: 'object',
    required: [
        'ip',
        'count'
    ],
    properties: {
        ip: {
            type: 'string'
        },
        count: {
            type: 'integer',
            format: 'int64'
        }
    }
} as const;

export const DashboardTopDeniedIpsResponseSchema = {
    type: 'object',
    required: [
        'ips'
    ],
    properties: {
        ips: {
            type: 'array',
            items: {
                $ref: '#/components/schemas/DashboardTopDeniedIp'
            }
        }
    }
} as const;

export const UsernameSchema = {
    type: 'string',
    description: 'Unique username. Lowercase alphanumeric, underscores, and hyphens only. Uppercase letters are not accepted.',
    minLength: 3,
    maxLength: 32,
    pattern: '^[a-z0-9_-]+$',
    example: 'john_doe'
} as const;

export const UserRoleSchema = {
    type: 'string',
    enum: [
        'admin',
        'user'
    ],
    description: 'The user\'s role. Only "admin" users can access admin endpoints.'
} as const;

export const DisplayNameSchema = {
    type: 'string',
    description: 'User\'s public name. Unicode allowed.',
    minLength: 1,
    maxLength: 50,
    example: 'John Doe'
} as const;

export const PasswordSchema = {
    type: 'string',
    format: 'password',
    minLength: 8,
    maxLength: 72,
    example: '123ASecretPassword'
} as const;

export const IPAddressSchema = {
    type: 'string',
    description: 'IPv4 or IPv6 address',
    anyOf: [
        {
            type: 'string',
            format: 'ipv4'
        },
        {
            type: 'string',
            format: 'ipv6'
        }
    ],
    example: '192.168.1.132'
} as const;

export const IDSchema = {
    type: 'integer',
    format: 'int64'
} as const;

export const CreateDeviceResponseWritableSchema = {
    type: 'object',
    required: [
        'device',
        'api_key'
    ],
    properties: {
        device: {
            $ref: '#/components/schemas/DeviceWritable'
        },
        api_key: {
            type: 'string',
            description: 'Secret key for the device; only returned on creation or regeneration.'
        }
    }
} as const;

export const UserWritableSchema = {
    type: 'object',
    required: [
        'id',
        'username',
        'display_name',
        'email',
        'created_at'
    ],
    properties: {
        id: {
            $ref: '#/components/schemas/ID'
        },
        username: {
            $ref: '#/components/schemas/Username'
        },
        display_name: {
            $ref: '#/components/schemas/DisplayName'
        },
        email: {
            type: 'string',
            format: 'email'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            'x-go-type': 'UTCTime'
        }
    }
} as const;

export const DeviceWritableSchema = {
    type: 'object',
    required: [
        'id',
        'name',
        'created_at',
        'api_key_prefix'
    ],
    properties: {
        created_at: {
            type: 'string',
            format: 'date-time',
            'x-go-type': 'UTCTime'
        },
        id: {
            $ref: '#/components/schemas/ID'
        },
        name: {
            description: 'User-friendly name for the device',
            type: 'string',
            minLength: 1,
            maxLength: 50
        },
        api_key_prefix: {
            type: 'string',
            description: 'Prefix of the device API key (for display only).'
        }
    }
} as const;

export const AddressWritableSchema = {
    type: 'object',
    required: [
        'id',
        'device_id',
        'ip',
        'is_enabled',
        'created_at',
        'updated_at'
    ],
    properties: {
        id: {
            $ref: '#/components/schemas/ID'
        },
        device_id: {
            $ref: '#/components/schemas/ID'
        },
        ip: {
            $ref: '#/components/schemas/IPAddress'
        },
        is_enabled: {
            type: 'boolean',
            description: 'The latest state of this address, enabled or disabled'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            'x-go-type': 'UTCTime'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            'x-go-type': 'UTCTime',
            description: 'Last time it was enabled or disabled'
        }
    }
} as const;
