// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AddAddressData, AddAddressErrors, AddAddressResponses, ChangePasswordData, ChangePasswordErrors, ChangePasswordResponses, CreateDeviceData, CreateDeviceErrors, CreateDeviceResponses, CreateUserData, CreateUserErrors, CreateUserResponses, DeleteDeviceData, DeleteDeviceErrors, DeleteDeviceResponses, DeleteUserData, DeleteUserErrors, DeleteUserResponses, DemoteUserData, DemoteUserErrors, DemoteUserResponses, DeviceHeartbeatByApiKeyData, DeviceHeartbeatByApiKeyErrors, DeviceHeartbeatByApiKeyResponses, DeviceHeartbeatData, DeviceHeartbeatErrors, DeviceHeartbeatResponses, DisableAddressData, DisableAddressErrors, DisableAddressResponses, DisableDeviceAddressLeaseRuleData, DisableDeviceAddressLeaseRuleErrors, DisableDeviceAddressLeaseRuleResponses, GetCurrentUserData, GetCurrentUserErrors, GetCurrentUserResponses, GetDeviceAddressesData, GetDeviceAddressesErrors, GetDeviceAddressesResponses, GetDeviceAddressHistoryData, GetDeviceAddressHistoryErrors, GetDeviceAddressHistoryResponses, GetDeviceAddressLeaseRuleData, GetDeviceAddressLeaseRuleErrors, GetDeviceAddressLeaseRuleResponses, GetDeviceData, GetDeviceErrors, GetDeviceResponses, GetDevicesData, GetDevicesErrors, GetDevicesResponses, GetRequestAuditLogData, GetRequestAuditLogDenyReasonsData, GetRequestAuditLogDenyReasonsErrors, GetRequestAuditLogDenyReasonsResponses, GetRequestAuditLogErrors, GetRequestAuditLogResponses, ListUsersData, ListUsersErrors, ListUsersResponses, LoginData, LoginErrors, LoginResponses, LogoutData, LogoutResponses, PromoteUserData, PromoteUserErrors, PromoteUserResponses, PutDeviceAddressLeaseRuleData, PutDeviceAddressLeaseRuleErrors, PutDeviceAddressLeaseRuleResponses, RegenerateDeviceApiKeyData, RegenerateDeviceApiKeyErrors, RegenerateDeviceApiKeyResponses, UpdateMeData, UpdateMeErrors, UpdateMeResponses } from './types.gen';
import { zAddAddressData, zAddAddressResponse, zChangePasswordData, zChangePasswordResponse, zCreateDeviceData, zCreateDeviceResponse2, zCreateUserData, zCreateUserResponse, zDeleteDeviceData, zDeleteDeviceResponse, zDeleteUserData, zDeleteUserResponse, zDemoteUserData, zDemoteUserResponse, zDeviceHeartbeatByApiKeyData, zDeviceHeartbeatByApiKeyResponse, zDeviceHeartbeatData, zDeviceHeartbeatResponse, zDisableAddressData, zDisableAddressResponse, zDisableDeviceAddressLeaseRuleData, zDisableDeviceAddressLeaseRuleResponse, zGetCurrentUserData, zGetCurrentUserResponse, zGetDeviceAddressesData, zGetDeviceAddressesResponse, zGetDeviceAddressHistoryData, zGetDeviceAddressHistoryResponse, zGetDeviceAddressLeaseRuleData, zGetDeviceAddressLeaseRuleResponse, zGetDeviceData, zGetDeviceResponse, zGetDevicesData, zGetDevicesResponse, zGetRequestAuditLogData, zGetRequestAuditLogDenyReasonsData, zGetRequestAuditLogDenyReasonsResponse, zGetRequestAuditLogResponse, zListUsersData, zListUsersResponse, zLoginData, zLoginResponse, zLogoutData, zLogoutResponse, zPromoteUserData, zPromoteUserResponse, zPutDeviceAddressLeaseRuleData, zPutDeviceAddressLeaseRuleResponse, zRegenerateDeviceApiKeyData, zRegenerateDeviceApiKeyResponse, zUpdateMeData, zUpdateMeResponse } from './zod.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List all users (Admin only)
 *
 * Returns all non-deleted users.
 */
export const listUsers = <ThrowOnError extends boolean = false>(options?: Options<ListUsersData, ThrowOnError>) => (options?.client ?? client).get<ListUsersResponses, ListUsersErrors, ThrowOnError>({
    requestValidator: async (data) => await zListUsersData.parseAsync(data),
    responseValidator: async (data) => await zListUsersResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-wdc_session',
            type: 'apiKey'
        }],
    url: '/admin/users',
    ...options
});

/**
 * Register a new user (Admin only)
 *
 * Creates a new user account.
 */
export const createUser = <ThrowOnError extends boolean = false>(options: Options<CreateUserData, ThrowOnError>) => (options.client ?? client).post<CreateUserResponses, CreateUserErrors, ThrowOnError>({
    requestValidator: async (data) => await zCreateUserData.parseAsync(data),
    responseValidator: async (data) => await zCreateUserResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-wdc_session',
            type: 'apiKey'
        }],
    url: '/admin/users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a user (Admin only)
 *
 * Soft-deletes a user and revokes all user sessions.
 */
export const deleteUser = <ThrowOnError extends boolean = false>(options: Options<DeleteUserData, ThrowOnError>) => (options.client ?? client).delete<DeleteUserResponses, DeleteUserErrors, ThrowOnError>({
    requestValidator: async (data) => await zDeleteUserData.parseAsync(data),
    responseValidator: async (data) => await zDeleteUserResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-wdc_session',
            type: 'apiKey'
        }],
    url: '/admin/users/{user_id}',
    ...options
});

/**
 * Promote a user to admin (Admin only)
 *
 * Promotes another user to the admin role. Cannot promote oneself.
 */
export const promoteUser = <ThrowOnError extends boolean = false>(options: Options<PromoteUserData, ThrowOnError>) => (options.client ?? client).post<PromoteUserResponses, PromoteUserErrors, ThrowOnError>({
    requestValidator: async (data) => await zPromoteUserData.parseAsync(data),
    responseValidator: async (data) => await zPromoteUserResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-wdc_session',
            type: 'apiKey'
        }],
    url: '/admin/users/{user_id}/promote',
    ...options
});

/**
 * Demote an admin to regular user (Admin only)
 *
 * Demotes another admin to the user role. Cannot demote oneself.
 */
export const demoteUser = <ThrowOnError extends boolean = false>(options: Options<DemoteUserData, ThrowOnError>) => (options.client ?? client).post<DemoteUserResponses, DemoteUserErrors, ThrowOnError>({
    requestValidator: async (data) => await zDemoteUserData.parseAsync(data),
    responseValidator: async (data) => await zDemoteUserResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-wdc_session',
            type: 'apiKey'
        }],
    url: '/admin/users/{user_id}/demote',
    ...options
});

/**
 * Login user
 *
 * Authenticates user and sets a strict HTTP-only session cookie.
 */
export const login = <ThrowOnError extends boolean = false>(options: Options<LoginData, ThrowOnError>) => (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    requestValidator: async (data) => await zLoginData.parseAsync(data),
    responseValidator: async (data) => await zLoginResponse.parseAsync(data),
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Logout user
 *
 * Invalidates the session cookie.
 */
export const logout = <ThrowOnError extends boolean = false>(options?: Options<LogoutData, ThrowOnError>) => (options?.client ?? client).post<LogoutResponses, unknown, ThrowOnError>({
    requestValidator: async (data) => await zLogoutData.parseAsync(data),
    responseValidator: async (data) => await zLogoutResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-wdc_session',
            type: 'apiKey'
        }],
    url: '/auth/logout',
    ...options
});

/**
 * Get current user
 *
 * Returns the currently authenticated user's details.
 */
export const getCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<GetCurrentUserData, ThrowOnError>) => (options?.client ?? client).get<GetCurrentUserResponses, GetCurrentUserErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetCurrentUserData.parseAsync(data),
    responseValidator: async (data) => await zGetCurrentUserResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-wdc_session',
            type: 'apiKey'
        }],
    url: '/auth/me',
    ...options
});

/**
 * Update current user profile
 *
 * Updates display name, username, and/or email for the authenticated user.
 */
export const updateMe = <ThrowOnError extends boolean = false>(options: Options<UpdateMeData, ThrowOnError>) => (options.client ?? client).patch<UpdateMeResponses, UpdateMeErrors, ThrowOnError>({
    requestValidator: async (data) => await zUpdateMeData.parseAsync(data),
    responseValidator: async (data) => await zUpdateMeResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-wdc_session',
            type: 'apiKey'
        }],
    url: '/users/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Change current user password
 *
 * Validates current password, updates password, and revokes all other sessions.
 */
export const changePassword = <ThrowOnError extends boolean = false>(options: Options<ChangePasswordData, ThrowOnError>) => (options.client ?? client).post<ChangePasswordResponses, ChangePasswordErrors, ThrowOnError>({
    requestValidator: async (data) => await zChangePasswordData.parseAsync(data),
    responseValidator: async (data) => await zChangePasswordResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-wdc_session',
            type: 'apiKey'
        }],
    url: '/users/me/password',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List all devices
 *
 * Get all devices belonging to the authenticated user.
 */
export const getDevices = <ThrowOnError extends boolean = false>(options?: Options<GetDevicesData, ThrowOnError>) => (options?.client ?? client).get<GetDevicesResponses, GetDevicesErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetDevicesData.parseAsync(data),
    responseValidator: async (data) => await zGetDevicesResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-wdc_session',
            type: 'apiKey'
        }],
    url: '/devices',
    ...options
});

/**
 * Create a device
 *
 * Create a new device for the authenticated user.
 */
export const createDevice = <ThrowOnError extends boolean = false>(options: Options<CreateDeviceData, ThrowOnError>) => (options.client ?? client).post<CreateDeviceResponses, CreateDeviceErrors, ThrowOnError>({
    requestValidator: async (data) => await zCreateDeviceData.parseAsync(data),
    responseValidator: async (data) => await zCreateDeviceResponse2.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-wdc_session',
            type: 'apiKey'
        }],
    url: '/devices',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a device
 *
 * Soft-deletes a device. The device is hidden from lists and cannot receive addresses.
 */
export const deleteDevice = <ThrowOnError extends boolean = false>(options: Options<DeleteDeviceData, ThrowOnError>) => (options.client ?? client).delete<DeleteDeviceResponses, DeleteDeviceErrors, ThrowOnError>({
    requestValidator: async (data) => await zDeleteDeviceData.parseAsync(data),
    responseValidator: async (data) => await zDeleteDeviceResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-wdc_session',
            type: 'apiKey'
        }],
    url: '/devices/{device_id}',
    ...options
});

/**
 * Get a device
 *
 * Get a single device by its id.
 */
export const getDevice = <ThrowOnError extends boolean = false>(options: Options<GetDeviceData, ThrowOnError>) => (options.client ?? client).get<GetDeviceResponses, GetDeviceErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetDeviceData.parseAsync(data),
    responseValidator: async (data) => await zGetDeviceResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-wdc_session',
            type: 'apiKey'
        }],
    url: '/devices/{device_id}',
    ...options
});

/**
 * Regenerate device API key
 *
 * Generates a new API key for the device, immediately invalidating the old one. The raw key is returned once. Admin-only.
 *
 */
export const regenerateDeviceApiKey = <ThrowOnError extends boolean = false>(options: Options<RegenerateDeviceApiKeyData, ThrowOnError>) => (options.client ?? client).post<RegenerateDeviceApiKeyResponses, RegenerateDeviceApiKeyErrors, ThrowOnError>({
    requestValidator: async (data) => await zRegenerateDeviceApiKeyData.parseAsync(data),
    responseValidator: async (data) => await zRegenerateDeviceApiKeyResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-wdc_session',
            type: 'apiKey'
        }],
    url: '/devices/{device_id}/api-key/regenerate',
    ...options
});

/**
 * Get addresses for a device
 *
 * Get all enabled addresses for a specific device.
 */
export const getDeviceAddresses = <ThrowOnError extends boolean = false>(options: Options<GetDeviceAddressesData, ThrowOnError>) => (options.client ?? client).get<GetDeviceAddressesResponses, GetDeviceAddressesErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetDeviceAddressesData.parseAsync(data),
    responseValidator: async (data) => await zGetDeviceAddressesResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-wdc_session',
            type: 'apiKey'
        }],
    url: '/devices/{device_id}/addresses',
    ...options
});

/**
 * Assign address to device
 *
 * Add a new address to a device.
 */
export const addAddress = <ThrowOnError extends boolean = false>(options: Options<AddAddressData, ThrowOnError>) => (options.client ?? client).post<AddAddressResponses, AddAddressErrors, ThrowOnError>({
    requestValidator: async (data) => await zAddAddressData.parseAsync(data),
    responseValidator: async (data) => await zAddAddressResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-wdc_session',
            type: 'apiKey'
        }],
    url: '/devices/{device_id}/addresses',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get address activity history for a device
 *
 * Returns time-bucketed active IP counts and individual address events for the given device within the specified time window.
 *
 */
export const getDeviceAddressHistory = <ThrowOnError extends boolean = false>(options: Options<GetDeviceAddressHistoryData, ThrowOnError>) => (options.client ?? client).get<GetDeviceAddressHistoryResponses, GetDeviceAddressHistoryErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetDeviceAddressHistoryData.parseAsync(data),
    responseValidator: async (data) => await zGetDeviceAddressHistoryResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-wdc_session',
            type: 'apiKey'
        }],
    url: '/devices/{device_id}/addresses/history',
    ...options
});

/**
 * Device heartbeat
 *
 * Device reports its current IP address. Extracts the client IP from the request and ensures it is enabled. Requires API Token or Session.
 */
export const deviceHeartbeat = <ThrowOnError extends boolean = false>(options: Options<DeviceHeartbeatData, ThrowOnError>) => (options.client ?? client).post<DeviceHeartbeatResponses, DeviceHeartbeatErrors, ThrowOnError>({
    requestValidator: async (data) => await zDeviceHeartbeatData.parseAsync(data),
    responseValidator: async (data) => await zDeviceHeartbeatResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-wdc_session',
            type: 'apiKey'
        }],
    url: '/devices/{device_id}/heartbeat',
    ...options
});

/**
 * Performs a heartbeat with the given api key header
 *
 * Same as /devices/{device_id}/heartbeat but authentication is provided via api-key for the device to update
 */
export const deviceHeartbeatByApiKey = <ThrowOnError extends boolean = false>(options?: Options<DeviceHeartbeatByApiKeyData, ThrowOnError>) => (options?.client ?? client).post<DeviceHeartbeatByApiKeyResponses, DeviceHeartbeatByApiKeyErrors, ThrowOnError>({
    requestValidator: async (data) => await zDeviceHeartbeatByApiKeyData.parseAsync(data),
    responseValidator: async (data) => await zDeviceHeartbeatByApiKeyResponse.parseAsync(data),
    security: [{ name: 'X-API-Key', type: 'apiKey' }],
    url: '/heartbeat',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * List request audit log entries
 *
 * Returns paginated request log entries to review access-control decisions. Admin-only.
 *
 */
export const getRequestAuditLog = <ThrowOnError extends boolean = false>(options?: Options<GetRequestAuditLogData, ThrowOnError>) => (options?.client ?? client).get<GetRequestAuditLogResponses, GetRequestAuditLogErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetRequestAuditLogData.parseAsync(data),
    responseValidator: async (data) => await zGetRequestAuditLogResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-wdc_session',
            type: 'apiKey'
        }],
    url: '/request-audit-log',
    ...options
});

/**
 * List valid deny reason values
 *
 * Returns all valid deny_reason values that can appear in audit log entries or be used as the deny_reason filter on GET /request-audit-log.
 *
 */
export const getRequestAuditLogDenyReasons = <ThrowOnError extends boolean = false>(options?: Options<GetRequestAuditLogDenyReasonsData, ThrowOnError>) => (options?.client ?? client).get<GetRequestAuditLogDenyReasonsResponses, GetRequestAuditLogDenyReasonsErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetRequestAuditLogDenyReasonsData.parseAsync(data),
    responseValidator: async (data) => await zGetRequestAuditLogDenyReasonsResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-wdc_session',
            type: 'apiKey'
        }],
    url: '/request-audit-log/deny-reasons',
    ...options
});

/**
 * Disable address
 *
 * Disables the address for the device.
 */
export const disableAddress = <ThrowOnError extends boolean = false>(options: Options<DisableAddressData, ThrowOnError>) => (options.client ?? client).delete<DisableAddressResponses, DisableAddressErrors, ThrowOnError>({
    requestValidator: async (data) => await zDisableAddressData.parseAsync(data),
    responseValidator: async (data) => await zDisableAddressResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-wdc_session',
            type: 'apiKey'
        }],
    url: '/devices/{device_id}/addresses/{address_id}',
    ...options
});

/**
 * Disable device lease rule for a device
 *
 * Disables the device lease rule for the device (sets enabled to false).
 */
export const disableDeviceAddressLeaseRule = <ThrowOnError extends boolean = false>(options: Options<DisableDeviceAddressLeaseRuleData, ThrowOnError>) => (options.client ?? client).delete<DisableDeviceAddressLeaseRuleResponses, DisableDeviceAddressLeaseRuleErrors, ThrowOnError>({
    requestValidator: async (data) => await zDisableDeviceAddressLeaseRuleData.parseAsync(data),
    responseValidator: async (data) => await zDisableDeviceAddressLeaseRuleResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-wdc_session',
            type: 'apiKey'
        }],
    url: '/devices/{device_id}/rules/address_lease',
    ...options
});

/**
 * Get address lease rule for a device
 *
 * Returns the address lease rule for the device if configured.
 */
export const getDeviceAddressLeaseRule = <ThrowOnError extends boolean = false>(options: Options<GetDeviceAddressLeaseRuleData, ThrowOnError>) => (options.client ?? client).get<GetDeviceAddressLeaseRuleResponses, GetDeviceAddressLeaseRuleErrors, ThrowOnError>({
    requestValidator: async (data) => await zGetDeviceAddressLeaseRuleData.parseAsync(data),
    responseValidator: async (data) => await zGetDeviceAddressLeaseRuleResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-wdc_session',
            type: 'apiKey'
        }],
    url: '/devices/{device_id}/rules/address_lease',
    ...options
});

/**
 * Create or update IP auto-expiry rule for a device
 *
 * Creates or updates the ip_auto_expiry rule for the device. ttl_seconds must be positive.
 */
export const putDeviceAddressLeaseRule = <ThrowOnError extends boolean = false>(options: Options<PutDeviceAddressLeaseRuleData, ThrowOnError>) => (options.client ?? client).put<PutDeviceAddressLeaseRuleResponses, PutDeviceAddressLeaseRuleErrors, ThrowOnError>({
    requestValidator: async (data) => await zPutDeviceAddressLeaseRuleData.parseAsync(data),
    responseValidator: async (data) => await zPutDeviceAddressLeaseRuleResponse.parseAsync(data),
    security: [{
            in: 'cookie',
            name: '__Host-wdc_session',
            type: 'apiKey'
        }],
    url: '/devices/{device_id}/rules/address_lease',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
