// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zErrorResponse = z.object({
    error: z.string().optional()
});

export const zId = z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' });

/**
 * IPv4 or IPv6 address
 */
export const zIpAddress = z.union([
    z.ipv4(),
    z.ipv6()
]);

/**
 * Unique username. Lowercase alphanumeric, underscores, and hyphens only. Uppercase letters are not accepted.
 */
export const zUsername = z.string().min(3).max(32).regex(/^[a-z0-9_-]+$/);

/**
 * The user's role. User role cannot login. Only superadmin can manage users.
 */
export const zUserRole = z.enum([
    'superadmin',
    'admin',
    'user'
]);

/**
 * User's public name. Unicode allowed.
 */
export const zDisplayName = z.string().min(1).max(50);

export const zPassword = z.string().min(8).max(72);

export const zUser = z.object({
    id: zId,
    username: zUsername,
    display_name: zDisplayName,
    email: z.email(),
    role: zUserRole,
    must_change_password: z.boolean().readonly(),
    bypass_host_allowlist: z.boolean(),
    created_at: z.iso.datetime({ offset: true, local: true })
});

export const zAuthRequest = z.object({
    username: zUsername,
    password: zPassword
});

export const zCreateUserRequest = z.object({
    username: zUsername,
    display_name: zDisplayName,
    email: z.email()
});

export const zUpdateProfileRequest = z.intersection(z.unknown(), z.object({
    display_name: zDisplayName.optional(),
    username: z.string().min(3).max(32).regex(/^[a-z0-9_-]+$/).optional(),
    email: z.email().optional()
}));

export const zChangePasswordRequest = z.object({
    current_password: z.string(),
    password: z.string().min(8).max(72)
});

export const zCreateDeviceRequest = z.object({
    name: z.string().min(1).max(50),
    owner_id: z.int().nullish()
});

export const zUpdateDeviceRequest = z.object({
    name: z.string().min(1).max(50).optional(),
    device_type: z.enum(['static', 'mobile']).optional(),
    description: z.string().max(200).nullish(),
    icon: z.string().max(80).nullish(),
    owner_id: z.int().nullish()
});

export const zDevice = z.object({
    created_at: z.iso.datetime({ offset: true, local: true }),
    updated_at: z.iso.datetime({ offset: true, local: true }),
    id: zId,
    name: z.string().min(1).max(50),
    device_type: z.enum(['static', 'mobile']),
    description: z.string().max(200).nullish(),
    icon: z.string().max(80).nullish(),
    api_key_prefix: z.string().nullish(),
    address_count: z.int().gte(0).readonly().optional(),
    last_seen_at: z.iso.datetime({ offset: true, local: true }).readonly().nullish(),
    owner_id: zId,
    owner_name: z.string().readonly().optional()
});

export const zCreateDeviceResponse = z.object({
    device: zDevice
});

export const zDeviceTypeItem = z.object({
    value: z.string(),
    label: z.string()
});

export const zDeviceHeartbeatByApiKeyRequest = z.object({
    ip: zIpAddress.optional()
});

export const zAddAddressRequest = z.object({
    ip: zIpAddress
});

export const zAddress = z.object({
    id: zId,
    device_id: zId,
    ip: zIpAddress,
    is_enabled: z.boolean(),
    created_at: z.iso.datetime({ offset: true, local: true }),
    updated_at: z.iso.datetime({ offset: true, local: true }),
    expires_at: z.iso.datetime({ offset: true, local: true }).readonly().nullish()
});

export const zAddressHistoryBucket = z.object({
    timestamp: z.iso.datetime({ offset: true, local: true }),
    active_count: z.int(),
    event_count: z.int()
});

/**
 * What triggered an address state change
 */
export const zAddressEventSource = z.enum([
    'heartbeat',
    'manual',
    'expiry',
    'limit_exceeded'
]);

export const zAddressHistoryEvent = z.object({
    id: zId,
    timestamp: z.iso.datetime({ offset: true, local: true }),
    ip: z.string(),
    is_enabled: z.boolean(),
    source: zAddressEventSource,
    device_id: zId,
    device_name: z.string()
});

export const zAddressHistoryResponse = z.object({
    buckets: z.array(zAddressHistoryBucket),
    events: z.array(zAddressHistoryEvent),
    total_events: z.int(),
    next_cursor: zId.nullish()
});

export const zAccessLogCountryStats = z.object({
    country_code: z.string(),
    country_name: z.string().optional(),
    continent_code: z.string().optional(),
    total: z.int(),
    allowed: z.int(),
    denied: z.int()
});

export const zAccessLogRow = z.object({
    id: zId,
    client_ip: zIpAddress,
    outcome: z.boolean(),
    deny_reason: z.string().optional(),
    device_id: zId.optional(),
    device_name: z.string().optional(),
    address_id: zId.optional(),
    created_at: z.iso.datetime({ offset: true, local: true }),
    xff_chain: z.string().optional(),
    target_host: z.string().optional(),
    target_uri: z.string().optional(),
    http_method: z.string().optional(),
    country_code: z.string().optional(),
    country_name: z.string().optional(),
    continent_code: z.string().optional(),
    asn: z.int().optional(),
    asn_org: z.string().optional(),
    duration_us: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    headers: z.record(z.string(), z.array(z.string()))
});

export const zAccessLogResponse = z.object({
    total: z.int(),
    next_cursor: zId.nullable(),
    rows: z.array(zAccessLogRow)
});

export const zDeviceAddressLeaseRule = z.object({
    id: zId,
    device_id: zId,
    enabled: z.boolean(),
    ttl_seconds: z.int().gte(1),
    created_at: z.iso.datetime({ offset: true, local: true }),
    updated_at: z.iso.datetime({ offset: true, local: true })
});

export const zPutDeviceAddressLeaseRuleRequest = z.object({
    ttl_seconds: z.int().gte(1)
});

export const zMaxActiveAddressesRule = z.object({
    id: zId,
    device_id: zId,
    enabled: z.boolean(),
    max_addresses: z.int().gte(1),
    created_at: z.iso.datetime({ offset: true, local: true }),
    updated_at: z.iso.datetime({ offset: true, local: true })
});

export const zPutMaxActiveAddressesRuleRequest = z.object({
    max_addresses: z.int().gte(1)
});

export const zDashboardStats = z.object({
    total_requests: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    allowed_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    denied_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    unique_ips: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    avg_duration_us: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zDashboardTrafficBucket = z.object({
    timestamp: z.iso.datetime({ offset: true, local: true }),
    allow_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    deny_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zDashboardTrafficResponse = z.object({
    buckets: z.array(zDashboardTrafficBucket)
});

export const zDashboardServiceCount = z.object({
    host: z.string(),
    allow_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    deny_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zDashboardServicesResponse = z.object({
    services: z.array(zDashboardServiceCount)
});

export const zDashboardTopDeniedIp = z.object({
    ip: z.string(),
    count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zDashboardTopDeniedIpsResponse = z.object({
    ips: z.array(zDashboardTopDeniedIp)
});

export const zCreateRegistrationRequest = z.object({
    owner_id: zId,
    device_name: z.string().min(1).max(100),
    heartbeat_server_url: z.url(),
    interval_seconds: z.int().gte(60),
    app_biometric_enabled: z.boolean().optional().default(false),
    app_settings_locked: z.boolean().optional().default(false),
    expires_in_hours: z.union([
        z.literal(1),
        z.literal(24),
        z.literal(48),
        z.literal(168)
    ])
});

export const zPendingRegistration = z.object({
    id: zId,
    device_name: z.string(),
    owner_id: zId,
    registration_code: z.string().nullish(),
    heartbeat_server_url: z.string(),
    interval_seconds: z.int(),
    app_biometric_enabled: z.boolean(),
    app_settings_locked: z.boolean(),
    expires_at: z.iso.datetime({ offset: true, local: true }),
    created_at: z.iso.datetime({ offset: true, local: true }),
    used_at: z.iso.datetime({ offset: true, local: true }).nullish(),
    invalidated_at: z.iso.datetime({ offset: true, local: true }).nullish(),
    created_device_id: zId.optional(),
    status: z.enum([
        'pending',
        'used',
        'expired',
        'invalidated'
    ])
});

export const zClaimRegistrationRequest = z.object({
    code: z.string()
});

export const zClaimRegistrationResponse = z.object({
    server_url: z.string(),
    interval_seconds: z.int(),
    app_biometric_enabled: z.boolean(),
    app_settings_locked: z.boolean(),
    api_key: z.string()
});

export const zGroupRef = z.object({
    id: zId,
    name: z.string()
});

export const zKnownHostRef = z.object({
    id: zId,
    fqdn: z.string().max(253),
    icon: z.string().nullish()
});

export const zKnownHostWithStats = z.object({
    id: zId,
    fqdn: z.string().max(253),
    icon: z.string().nullish(),
    created_at: z.iso.datetime({ offset: true, local: true }),
    user_count: z.int(),
    groups: z.array(zGroupRef)
});

/**
 * A single known host inside a reconcile request. A null `id` marks a
 * brand-new host; a non-null `id` must match an existing row. `fqdn` is
 * immutable on updates — a mismatch is rejected.
 *
 */
export const zDesiredKnownHost = z.object({
    id: zId.nullish(),
    fqdn: z.string().min(3).max(253),
    icon: z.string().nullish()
});

/**
 * Full desired image of all known hosts. Hosts already in the database whose
 * ID is absent from `hosts` will be deleted; hosts with a non-null ID are
 * updated (icon only); hosts with a null ID are created. An empty `hosts`
 * array deletes every known host.
 *
 */
export const zReconcileKnownHostsRequest = z.object({
    hosts: z.array(zDesiredKnownHost)
});

export const zHostGroupWithMembers = z.object({
    id: zId,
    name: z.string(),
    color: z.string().nullish(),
    description: z.string().nullish(),
    icon: z.string().nullish(),
    created_at: z.iso.datetime({ offset: true, local: true }),
    hosts: z.array(zKnownHostRef),
    member_ids: z.array(zId)
});

/**
 * A single host group inside a reconcile request. A null `id` marks a
 * brand-new group; a non-null `id` must match an existing group.
 *
 */
export const zDesiredHostGroup = z.object({
    id: zId.nullish(),
    name: z.string().min(1).max(100),
    color: z.string().nullish(),
    description: z.string().max(500).nullish(),
    icon: z.string().nullish(),
    host_ids: z.array(zId).optional()
});

/**
 * Full desired image of all host groups. Groups already in the database whose
 * ID is absent from `groups` will be deleted; groups with a non-null ID are
 * updated; groups with a null ID are created.
 *
 */
export const zReconcileHostGroupsRequest = z.object({
    groups: z.array(zDesiredHostGroup)
});

export const zSetUserHostGrantsRequest = z.object({
    bypass: z.boolean().optional(),
    host_ids: z.array(z.int()).optional(),
    group_ids: z.array(z.int()).optional()
});

export const zIgnoredHostSuggestion = z.object({
    id: zId,
    fqdn: z.string().max(253),
    created_at: z.iso.datetime({ offset: true, local: true })
});

export const zHostSuggestion = z.object({
    fqdn: z.string().max(253),
    first_seen: z.iso.datetime({ offset: true, local: true }),
    allowed_hits: z.int(),
    denied_hits: z.int()
});

export const zIgnoreSuggestionRequest = z.object({
    fqdn: z.string().min(3).max(253).regex(/^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)+$/)
});

export const zHostSuggestionsPage = z.object({
    suggestions: z.array(zHostSuggestion),
    ignored: z.array(zIgnoredHostSuggestion)
});

export const zUserHostAccessSummary = z.object({
    id: zId,
    display_name: z.string(),
    email: z.email(),
    role: zUserRole,
    bypass: z.boolean(),
    direct_host_count: z.int(),
    groups: z.array(zGroupRef)
});

export const zUserHostDetailsGroup = z.object({
    id: zId,
    name: z.string(),
    icon: z.string().nullish(),
    granted: z.boolean(),
    hosts: z.array(zKnownHostRef)
});

export const zUserHostDetailsHost = z.object({
    id: zId,
    fqdn: z.string().max(253),
    icon: z.string().nullish(),
    directly_granted: z.boolean(),
    via_group: zGroupRef.nullish()
});

export const zUserHostDetails = z.object({
    id: zId,
    display_name: z.string(),
    email: z.email(),
    role: zUserRole,
    bypass: z.boolean(),
    groups: z.array(zUserHostDetailsGroup),
    hosts: z.array(zUserHostDetailsHost)
});

export const zPromoteUserRequest = z.object({
    password: zPassword
});

export const zDeviceApiKeyResponse = z.object({
    device: zDevice,
    api_key: z.string()
});

export const zUserWritable = z.object({
    id: zId,
    username: zUsername,
    display_name: zDisplayName,
    email: z.email(),
    bypass_host_allowlist: z.boolean(),
    created_at: z.iso.datetime({ offset: true, local: true })
});

export const zDeviceWritable = z.object({
    created_at: z.iso.datetime({ offset: true, local: true }),
    updated_at: z.iso.datetime({ offset: true, local: true }),
    id: zId,
    name: z.string().min(1).max(50),
    device_type: z.enum(['static', 'mobile']),
    description: z.string().max(200).nullish(),
    icon: z.string().max(80).nullish(),
    api_key_prefix: z.string().nullish()
});

export const zCreateDeviceResponseWritable = z.object({
    device: zDeviceWritable
});

export const zAddressWritable = z.object({
    id: zId,
    device_id: zId,
    ip: zIpAddress,
    is_enabled: z.boolean(),
    created_at: z.iso.datetime({ offset: true, local: true }),
    updated_at: z.iso.datetime({ offset: true, local: true })
});

export const zDeviceApiKeyResponseWritable = z.object({
    device: zDeviceWritable,
    api_key: z.string()
});

/**
 * Users list
 */
export const zListUsersResponse = z.array(zUser);

export const zCreateUserBody = zCreateUserRequest;

/**
 * User created successfully
 */
export const zCreateUserResponse = zUser;

export const zDeleteUserPath = z.object({
    user_id: zId
});

/**
 * User deleted successfully
 */
export const zDeleteUserResponse = z.void();

export const zPromoteUserBody = zPromoteUserRequest;

export const zPromoteUserPath = z.object({
    user_id: zId
});

/**
 * User promoted successfully
 */
export const zPromoteUserResponse = zUser;

export const zDemoteUserPath = z.object({
    user_id: zId
});

/**
 * User demoted successfully
 */
export const zDemoteUserResponse = zUser;

export const zGetDevicesByUserPath = z.object({
    user_id: zId
});

/**
 * OK
 */
export const zGetDevicesByUserResponse = z.array(zDevice);

export const zLoginBody = zAuthRequest;

/**
 * Logged in successfully
 */
export const zLoginResponse = zUser;

/**
 * Logged out successfully
 */
export const zLogoutResponse = z.void();

/**
 * Current user details
 */
export const zGetCurrentUserResponse = zUser;

export const zUpdateMeBody = zUpdateProfileRequest;

/**
 * User profile updated
 */
export const zUpdateMeResponse = zUser;

export const zChangePasswordBody = zChangePasswordRequest;

/**
 * Password changed successfully
 */
export const zChangePasswordResponse = z.void();

/**
 * OK
 */
export const zGetDevicesResponse = z.array(zDevice);

/**
 * Device creation request
 */
export const zCreateDeviceBody = zCreateDeviceRequest;

/**
 * Created
 */
export const zCreateDeviceResponse2 = zCreateDeviceResponse;

export const zDeleteDevicePath = z.object({
    device_id: zId
});

/**
 * No Content - Device deleted successfully
 */
export const zDeleteDeviceResponse = z.void();

export const zGetDevicePath = z.object({
    device_id: zId
});

/**
 * OK
 */
export const zGetDeviceResponse = zDevice;

export const zUpdateDeviceBody = zUpdateDeviceRequest;

export const zUpdateDevicePath = z.object({
    device_id: zId
});

/**
 * OK
 */
export const zUpdateDeviceResponse = zDevice;

/**
 * OK
 */
export const zListDeviceTypesResponse = z.array(zDeviceTypeItem);

export const zDeleteDeviceApiKeyPath = z.object({
    device_id: zId
});

/**
 * No Content - API key deleted successfully
 */
export const zDeleteDeviceApiKeyResponse = z.void();

export const zRegenerateDeviceApiKeyPath = z.object({
    device_id: zId
});

/**
 * API key generated or regenerated successfully
 */
export const zRegenerateDeviceApiKeyResponse = zDeviceApiKeyResponse;

export const zDeviceHeartbeatPath = z.object({
    device_id: zId
});

/**
 * Address enabled
 */
export const zDeviceHeartbeatResponse = zAddress;

export const zDeviceHeartbeatByApiKeyBody = zDeviceHeartbeatByApiKeyRequest;

/**
 * Address enabled
 */
export const zDeviceHeartbeatByApiKeyResponse = zAddress;

export const zGetDeviceAddressesPath = z.object({
    device_id: zId
});

/**
 * OK
 */
export const zGetDeviceAddressesResponse = z.array(zAddress);

/**
 * Address assignment request
 */
export const zAddAddressBody = zAddAddressRequest;

export const zAddAddressPath = z.object({
    device_id: zId
});

/**
 * Address already existed, enabled status set
 */
export const zAddAddressResponse = zAddress;

export const zGetAddressHistoryQuery = z.object({
    device_id: z.array(zId).optional(),
    from: z.iso.datetime({ offset: true, local: true }).optional(),
    to: z.iso.datetime({ offset: true, local: true }).optional(),
    granularity: z.enum(['hour', 'day']).optional().default('hour'),
    source: zAddressEventSource.optional(),
    is_enabled: z.boolean().optional(),
    ip: z.string().optional(),
    limit: z.int().lte(200).optional().default(50),
    before_id: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    include_all: z.boolean().optional().default(false)
});

/**
 * Address history with time-series buckets and paginated events
 */
export const zGetAddressHistoryResponse = zAddressHistoryResponse;

export const zDisableAddressPath = z.object({
    device_id: zId,
    address_id: zId
});

/**
 * Address successfully disabled
 */
export const zDisableAddressResponse = zAddress;

export const zGetAccessLogQuery = z.object({
    device_id: zId.optional(),
    outcome: z.boolean().optional(),
    deny_reason: z.string().optional(),
    ip: z.string().optional(),
    host: z.string().optional(),
    country_code: z.string().optional(),
    continent_code: z.string().optional(),
    from: z.iso.datetime({ offset: true, local: true }).optional(),
    to: z.iso.datetime({ offset: true, local: true }).optional(),
    limit: z.int().lte(200).optional().default(50),
    before_id: zId.optional()
});

/**
 * Access log entries
 */
export const zGetAccessLogResponse = zAccessLogResponse;

export const zGetAccessLogByCountryQuery = z.object({
    from: z.iso.datetime({ offset: true, local: true }).optional(),
    to: z.iso.datetime({ offset: true, local: true }).optional()
});

/**
 * Request counts by country
 */
export const zGetAccessLogByCountryResponse = z.array(zAccessLogCountryStats);

/**
 * List of deny reason values
 */
export const zGetAccessLogDenyReasonsResponse = z.array(z.string());

export const zDisableDeviceAddressLeaseRulePath = z.object({
    device_id: zId
});

/**
 * Rule disabled
 */
export const zDisableDeviceAddressLeaseRuleResponse = z.void();

export const zGetDeviceAddressLeaseRulePath = z.object({
    device_id: zId
});

/**
 * OK
 */
export const zGetDeviceAddressLeaseRuleResponse = zDeviceAddressLeaseRule;

export const zPutDeviceAddressLeaseRuleBody = zPutDeviceAddressLeaseRuleRequest;

export const zPutDeviceAddressLeaseRulePath = z.object({
    device_id: zId
});

/**
 * Rule updated or created
 */
export const zPutDeviceAddressLeaseRuleResponse = zDeviceAddressLeaseRule;

export const zDisableMaxActiveAddressesRulePath = z.object({
    device_id: zId
});

/**
 * Rule disabled
 */
export const zDisableMaxActiveAddressesRuleResponse = z.void();

export const zGetMaxActiveAddressesRulePath = z.object({
    device_id: zId
});

/**
 * OK
 */
export const zGetMaxActiveAddressesRuleResponse = zMaxActiveAddressesRule;

export const zPutMaxActiveAddressesRuleBody = zPutMaxActiveAddressesRuleRequest;

export const zPutMaxActiveAddressesRulePath = z.object({
    device_id: zId
});

/**
 * Rule updated or created
 */
export const zPutMaxActiveAddressesRuleResponse = zMaxActiveAddressesRule;

export const zGetDashboardStatsQuery = z.object({
    from: z.iso.datetime({ offset: true, local: true }).optional(),
    to: z.iso.datetime({ offset: true, local: true }).optional()
});

/**
 * Summary statistics
 */
export const zGetDashboardStatsResponse = zDashboardStats;

export const zGetDashboardTrafficQuery = z.object({
    from: z.iso.datetime({ offset: true, local: true }).optional(),
    to: z.iso.datetime({ offset: true, local: true }).optional(),
    granularity: z.enum(['hour', 'day']).optional().default('hour')
});

/**
 * Traffic time series
 */
export const zGetDashboardTrafficResponse = zDashboardTrafficResponse;

export const zGetDashboardServicesQuery = z.object({
    from: z.iso.datetime({ offset: true, local: true }).optional(),
    to: z.iso.datetime({ offset: true, local: true }).optional()
});

/**
 * Service breakdown
 */
export const zGetDashboardServicesResponse = zDashboardServicesResponse;

export const zGetDashboardTopDeniedIpsQuery = z.object({
    from: z.iso.datetime({ offset: true, local: true }).optional(),
    to: z.iso.datetime({ offset: true, local: true }).optional(),
    limit: z.int().lte(100).optional().default(10)
});

/**
 * Top denied IPs
 */
export const zGetDashboardTopDeniedIpsResponse = zDashboardTopDeniedIpsResponse;

export const zClaimRegistrationBody = zClaimRegistrationRequest;

/**
 * Registration successful — device created and config returned
 */
export const zClaimRegistrationResponse2 = zClaimRegistrationResponse;

export const zListRegistrationsQuery = z.object({
    status: z.enum(['pending', 'all']).optional().default('pending')
});

/**
 * List of registrations
 */
export const zListRegistrationsResponse = z.array(zPendingRegistration);

export const zCreateRegistrationBody = zCreateRegistrationRequest;

/**
 * Registration invite created — includes registration_code
 */
export const zCreateRegistrationResponse = zPendingRegistration;

export const zDeleteRegistrationPath = z.object({
    registration_id: zId
});

/**
 * Invite deleted
 */
export const zDeleteRegistrationResponse = z.void();

export const zGetRegistrationPath = z.object({
    registration_id: zId
});

/**
 * Registration invite
 */
export const zGetRegistrationResponse = zPendingRegistration;

/**
 * Known hosts list with stats
 */
export const zListKnownHostsResponse = z.array(zKnownHostWithStats);

export const zReconcileKnownHostsBody = zReconcileKnownHostsRequest;

/**
 * Reconciliation applied
 */
export const zReconcileKnownHostsResponse = z.void();

/**
 * Host groups list
 */
export const zListHostGroupsResponse = z.array(zHostGroupWithMembers);

export const zReconcileHostGroupsBody = zReconcileHostGroupsRequest;

/**
 * Reconciliation applied
 */
export const zReconcileHostGroupsResponse = z.void();

export const zSetUserHostGrantsBody = zSetUserHostGrantsRequest;

export const zSetUserHostGrantsPath = z.object({
    user_id: zId
});

/**
 * Grants updated
 */
export const zSetUserHostGrantsResponse = z.void();

/**
 * Suggestions page with active and ignored lists
 */
export const zListHostSuggestionsResponse = zHostSuggestionsPage;

export const zIgnoreSuggestionBody = zIgnoreSuggestionRequest;

/**
 * Suggestion ignored
 */
export const zIgnoreSuggestionResponse = zIgnoredHostSuggestion;

export const zUnignoreSuggestionPath = z.object({
    fqdn: z.string()
});

/**
 * Suggestion unignored
 */
export const zUnignoreSuggestionResponse = z.void();

/**
 * Users host access summary list
 */
export const zListUsersHostAccessResponse = z.array(zUserHostAccessSummary);

export const zGetUserHostDetailsPath = z.object({
    user_id: zId
});

/**
 * Full user host access details
 */
export const zGetUserHostDetailsResponse = zUserHostDetails;
