// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

export const zErrorResponse = z.object({
    error: z.string().optional()
});

export const zId = z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' });

/**
 * IPv4 or IPv6 address
 */
export const zIpAddress = z.union([
    z.ipv4(),
    z.ipv6()
]);

/**
 * Unique username. Lowercase alphanumeric, underscores, and hyphens only. Uppercase letters are not accepted.
 */
export const zUsername = z.string().min(3).max(32).regex(/^[a-z0-9_-]+$/);

/**
 * The user's role. Only "admin" users can access admin endpoints.
 */
export const zUserRole = z.enum(['admin', 'user']);

/**
 * User's public name. Unicode allowed.
 */
export const zDisplayName = z.string().min(1).max(50);

export const zPassword = z.string().min(8).max(72);

export const zUser = z.object({
    id: zId,
    username: zUsername,
    display_name: zDisplayName,
    email: z.email(),
    role: zUserRole,
    must_change_password: z.boolean().readonly(),
    created_at: z.iso.datetime({ offset: true, local: true })
});

export const zAuthRequest = z.object({
    username: zUsername,
    password: zPassword
});

export const zCreateUserRequest = z.object({
    username: zUsername,
    display_name: zDisplayName,
    email: z.email(),
    password: zPassword
});

export const zUpdateProfileRequest = z.intersection(z.unknown(), z.object({
    display_name: zDisplayName.optional(),
    username: z.string().min(3).max(32).regex(/^[a-z0-9_-]+$/).optional(),
    email: z.email().optional()
}));

export const zChangePasswordRequest = z.object({
    current_password: z.string(),
    password: z.string().min(8).max(72)
});

export const zCreateDeviceRequest = z.object({
    name: z.string().min(1).max(50),
    owner_id: z.int().nullish()
});

export const zUpdateDeviceRequest = z.object({
    name: z.string().min(1).max(50).optional(),
    device_type: z.enum(['static', 'mobile']).optional(),
    description: z.string().max(200).nullish(),
    icon: z.string().max(80).nullish(),
    owner_id: z.int().nullish()
});

export const zDevice = z.object({
    created_at: z.iso.datetime({ offset: true, local: true }),
    updated_at: z.iso.datetime({ offset: true, local: true }),
    id: zId,
    name: z.string().min(1).max(50),
    device_type: z.enum(['static', 'mobile']),
    description: z.string().max(200).nullish(),
    icon: z.string().max(80).nullish(),
    api_key_prefix: z.string().nullish(),
    address_count: z.int().gte(0).readonly().optional(),
    last_seen_at: z.iso.datetime({ offset: true, local: true }).readonly().nullish(),
    owner_id: zId,
    owner_name: z.string().readonly().optional()
});

export const zCreateDeviceResponse = z.object({
    device: zDevice
});

export const zDeviceTypeItem = z.object({
    value: z.string(),
    label: z.string()
});

export const zDeviceHeartbeatByApiKeyRequest = z.object({
    ip: zIpAddress.optional()
});

export const zAddAddressRequest = z.object({
    ip: zIpAddress
});

export const zAddress = z.object({
    id: zId,
    device_id: zId,
    ip: zIpAddress,
    is_enabled: z.boolean(),
    created_at: z.iso.datetime({ offset: true, local: true }),
    updated_at: z.iso.datetime({ offset: true, local: true }),
    expires_at: z.iso.datetime({ offset: true, local: true }).readonly().nullish()
});

export const zAddressHistoryBucket = z.object({
    timestamp: z.iso.datetime({ offset: true, local: true }),
    active_count: z.int(),
    event_count: z.int()
});

/**
 * What triggered an address state change
 */
export const zAddressEventSource = z.enum([
    'heartbeat',
    'manual',
    'expiry',
    'limit_exceeded'
]);

export const zAddressHistoryEvent = z.object({
    id: zId,
    timestamp: z.iso.datetime({ offset: true, local: true }),
    ip: z.string(),
    is_enabled: z.boolean(),
    source: zAddressEventSource,
    device_id: zId,
    device_name: z.string()
});

export const zAddressHistoryResponse = z.object({
    buckets: z.array(zAddressHistoryBucket),
    events: z.array(zAddressHistoryEvent),
    total_events: z.int(),
    next_cursor: zId.nullish()
});

export const zAccessLogCountryStats = z.object({
    country_code: z.string(),
    country_name: z.string().optional(),
    continent_code: z.string().optional(),
    total: z.int(),
    allowed: z.int(),
    denied: z.int()
});

export const zAccessLogRow = z.object({
    id: zId,
    client_ip: zIpAddress,
    outcome: z.boolean(),
    deny_reason: z.string().optional(),
    device_id: zId.optional(),
    device_name: z.string().optional(),
    address_id: zId.optional(),
    created_at: z.iso.datetime({ offset: true, local: true }),
    xff_chain: z.string().optional(),
    target_host: z.string().optional(),
    target_uri: z.string().optional(),
    http_method: z.string().optional(),
    country_code: z.string().optional(),
    country_name: z.string().optional(),
    continent_code: z.string().optional(),
    asn: z.int().optional(),
    asn_org: z.string().optional(),
    duration_us: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
    headers: z.record(z.string(), z.array(z.string()))
});

export const zAccessLogResponse = z.object({
    total: z.int(),
    next_cursor: zId.nullable(),
    rows: z.array(zAccessLogRow)
});

export const zDeviceAddressLeaseRule = z.object({
    id: zId,
    device_id: zId,
    enabled: z.boolean(),
    ttl_seconds: z.int().gte(1),
    created_at: z.iso.datetime({ offset: true, local: true }),
    updated_at: z.iso.datetime({ offset: true, local: true })
});

export const zPutDeviceAddressLeaseRuleRequest = z.object({
    ttl_seconds: z.int().gte(1)
});

export const zMaxActiveAddressesRule = z.object({
    id: zId,
    device_id: zId,
    enabled: z.boolean(),
    max_addresses: z.int().gte(1),
    created_at: z.iso.datetime({ offset: true, local: true }),
    updated_at: z.iso.datetime({ offset: true, local: true })
});

export const zPutMaxActiveAddressesRuleRequest = z.object({
    max_addresses: z.int().gte(1)
});

export const zDashboardStats = z.object({
    total_requests: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    allowed_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    denied_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    unique_ips: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    avg_duration_us: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zDashboardTrafficBucket = z.object({
    timestamp: z.iso.datetime({ offset: true, local: true }),
    allow_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    deny_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zDashboardTrafficResponse = z.object({
    buckets: z.array(zDashboardTrafficBucket)
});

export const zDashboardServiceCount = z.object({
    host: z.string(),
    allow_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }),
    deny_count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zDashboardServicesResponse = z.object({
    services: z.array(zDashboardServiceCount)
});

export const zDashboardTopDeniedIp = z.object({
    ip: z.string(),
    count: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' })
});

export const zDashboardTopDeniedIpsResponse = z.object({
    ips: z.array(zDashboardTopDeniedIp)
});

export const zCreateRegistrationRequest = z.object({
    owner_id: z.int(),
    device_name: z.string().min(1).max(100),
    heartbeat_server_url: z.url(),
    interval_seconds: z.int().gte(60),
    biometric_enabled: z.boolean().optional().default(false),
    biometric_user_can_toggle: z.boolean().optional().default(true),
    expires_in_hours: z.union([
        z.literal(1),
        z.literal(24),
        z.literal(48),
        z.literal(168)
    ])
});

export const zPendingRegistration = z.object({
    id: z.string(),
    device_name: z.string(),
    owner_id: zId,
    registration_code: z.string().nullish(),
    device_api_key_prefix: z.string(),
    heartbeat_server_url: z.string(),
    interval_seconds: z.int(),
    biometric_enabled: z.boolean(),
    biometric_user_can_toggle: z.boolean(),
    expires_at: z.iso.datetime({ offset: true, local: true }),
    created_at: z.iso.datetime({ offset: true, local: true }),
    used_at: z.iso.datetime({ offset: true, local: true }).nullish(),
    created_device_id: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).nullish(),
    status: z.enum([
        'pending',
        'used',
        'expired'
    ])
});

export const zClaimRegistrationRequest = z.object({
    code: z.string()
});

export const zClaimRegistrationResponse = z.object({
    server_url: z.string(),
    interval_seconds: z.int(),
    biometric_enabled: z.boolean(),
    biometric_user_can_toggle: z.boolean(),
    api_key: z.string()
});

export const zDeviceApiKeyResponse = z.object({
    device: zDevice,
    api_key: z.string()
});

export const zUserWritable = z.object({
    id: zId,
    username: zUsername,
    display_name: zDisplayName,
    email: z.email(),
    created_at: z.iso.datetime({ offset: true, local: true })
});

export const zDeviceWritable = z.object({
    created_at: z.iso.datetime({ offset: true, local: true }),
    updated_at: z.iso.datetime({ offset: true, local: true }),
    id: zId,
    name: z.string().min(1).max(50),
    device_type: z.enum(['static', 'mobile']),
    description: z.string().max(200).nullish(),
    icon: z.string().max(80).nullish(),
    api_key_prefix: z.string().nullish()
});

export const zCreateDeviceResponseWritable = z.object({
    device: zDeviceWritable
});

export const zAddressWritable = z.object({
    id: zId,
    device_id: zId,
    ip: zIpAddress,
    is_enabled: z.boolean(),
    created_at: z.iso.datetime({ offset: true, local: true }),
    updated_at: z.iso.datetime({ offset: true, local: true })
});

export const zDeviceApiKeyResponseWritable = z.object({
    device: zDeviceWritable,
    api_key: z.string()
});

export const zListUsersData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Users list
 */
export const zListUsersResponse = z.array(zUser);

export const zCreateUserData = z.object({
    body: zCreateUserRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * User created successfully
 */
export const zCreateUserResponse = zUser;

export const zDeleteUserData = z.object({
    body: z.never().optional(),
    path: z.object({
        user_id: zId
    }),
    query: z.never().optional()
});

/**
 * User deleted successfully
 */
export const zDeleteUserResponse = z.void();

export const zPromoteUserData = z.object({
    body: z.never().optional(),
    path: z.object({
        user_id: zId
    }),
    query: z.never().optional()
});

/**
 * User promoted successfully
 */
export const zPromoteUserResponse = zUser;

export const zDemoteUserData = z.object({
    body: z.never().optional(),
    path: z.object({
        user_id: zId
    }),
    query: z.never().optional()
});

/**
 * User demoted successfully
 */
export const zDemoteUserResponse = zUser;

export const zGetDevicesByUserData = z.object({
    body: z.never().optional(),
    path: z.object({
        user_id: zId
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetDevicesByUserResponse = z.array(zDevice);

export const zLoginData = z.object({
    body: zAuthRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Logged in successfully
 */
export const zLoginResponse = zUser;

export const zLogoutData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Logged out successfully
 */
export const zLogoutResponse = z.void();

export const zGetCurrentUserData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Current user details
 */
export const zGetCurrentUserResponse = zUser;

export const zUpdateMeData = z.object({
    body: zUpdateProfileRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * User profile updated
 */
export const zUpdateMeResponse = zUser;

export const zChangePasswordData = z.object({
    body: zChangePasswordRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Password changed successfully
 */
export const zChangePasswordResponse = z.void();

export const zGetDevicesData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetDevicesResponse = z.array(zDevice);

export const zCreateDeviceData = z.object({
    body: zCreateDeviceRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Created
 */
export const zCreateDeviceResponse2 = zCreateDeviceResponse;

export const zDeleteDeviceData = z.object({
    body: z.never().optional(),
    path: z.object({
        device_id: zId
    }),
    query: z.never().optional()
});

/**
 * No Content - Device deleted successfully
 */
export const zDeleteDeviceResponse = z.void();

export const zGetDeviceData = z.object({
    body: z.never().optional(),
    path: z.object({
        device_id: zId
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetDeviceResponse = zDevice;

export const zUpdateDeviceData = z.object({
    body: zUpdateDeviceRequest,
    path: z.object({
        device_id: zId
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zUpdateDeviceResponse = zDevice;

export const zListDeviceTypesData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * OK
 */
export const zListDeviceTypesResponse = z.array(zDeviceTypeItem);

export const zDeleteDeviceApiKeyData = z.object({
    body: z.never().optional(),
    path: z.object({
        device_id: zId
    }),
    query: z.never().optional()
});

/**
 * No Content - API key deleted successfully
 */
export const zDeleteDeviceApiKeyResponse = z.void();

export const zRegenerateDeviceApiKeyData = z.object({
    body: z.never().optional(),
    path: z.object({
        device_id: zId
    }),
    query: z.never().optional()
});

/**
 * API key generated or regenerated successfully
 */
export const zRegenerateDeviceApiKeyResponse = zDeviceApiKeyResponse;

export const zDeviceHeartbeatData = z.object({
    body: z.never().optional(),
    path: z.object({
        device_id: zId
    }),
    query: z.never().optional()
});

/**
 * Address enabled
 */
export const zDeviceHeartbeatResponse = zAddress;

export const zDeviceHeartbeatByApiKeyData = z.object({
    body: zDeviceHeartbeatByApiKeyRequest.optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Address enabled
 */
export const zDeviceHeartbeatByApiKeyResponse = zAddress;

export const zGetDeviceAddressesData = z.object({
    body: z.never().optional(),
    path: z.object({
        device_id: zId
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetDeviceAddressesResponse = z.array(zAddress);

export const zAddAddressData = z.object({
    body: zAddAddressRequest,
    path: z.object({
        device_id: zId
    }),
    query: z.never().optional()
});

/**
 * Address already existed, enabled status set
 */
export const zAddAddressResponse = zAddress;

export const zGetAddressHistoryData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        device_id: z.array(zId).optional(),
        from: z.iso.datetime({ offset: true, local: true }).optional(),
        to: z.iso.datetime({ offset: true, local: true }).optional(),
        granularity: z.enum(['hour', 'day']).optional(),
        source: zAddressEventSource.optional(),
        is_enabled: z.boolean().optional(),
        ip: z.string().optional(),
        limit: z.int().lte(200).optional().default(50),
        before_id: z.coerce.bigint().min(BigInt('-9223372036854775808'), { error: 'Invalid value: Expected int64 to be >= -9223372036854775808' }).max(BigInt('9223372036854775807'), { error: 'Invalid value: Expected int64 to be <= 9223372036854775807' }).optional(),
        include_all: z.boolean().optional().default(false)
    }).optional()
});

/**
 * Address history with time-series buckets and paginated events
 */
export const zGetAddressHistoryResponse = zAddressHistoryResponse;

export const zDisableAddressData = z.object({
    body: z.never().optional(),
    path: z.object({
        device_id: zId,
        address_id: zId
    }),
    query: z.never().optional()
});

/**
 * Address successfully disabled
 */
export const zDisableAddressResponse = zAddress;

export const zGetAccessLogData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        device_id: zId.optional(),
        outcome: z.boolean().optional(),
        deny_reason: z.string().optional(),
        ip: z.string().optional(),
        host: z.string().optional(),
        country_code: z.string().optional(),
        continent_code: z.string().optional(),
        from: z.iso.datetime({ offset: true, local: true }).optional(),
        to: z.iso.datetime({ offset: true, local: true }).optional(),
        limit: z.int().lte(200).optional().default(50),
        before_id: zId.optional()
    }).optional()
});

/**
 * Access log entries
 */
export const zGetAccessLogResponse = zAccessLogResponse;

export const zGetAccessLogByCountryData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        from: z.iso.datetime({ offset: true, local: true }).optional(),
        to: z.iso.datetime({ offset: true, local: true }).optional()
    }).optional()
});

/**
 * Request counts by country
 */
export const zGetAccessLogByCountryResponse = z.array(zAccessLogCountryStats);

export const zGetAccessLogDenyReasonsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * List of deny reason values
 */
export const zGetAccessLogDenyReasonsResponse = z.array(z.string());

export const zDisableDeviceAddressLeaseRuleData = z.object({
    body: z.never().optional(),
    path: z.object({
        device_id: zId
    }),
    query: z.never().optional()
});

/**
 * Rule disabled
 */
export const zDisableDeviceAddressLeaseRuleResponse = z.void();

export const zGetDeviceAddressLeaseRuleData = z.object({
    body: z.never().optional(),
    path: z.object({
        device_id: zId
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetDeviceAddressLeaseRuleResponse = zDeviceAddressLeaseRule;

export const zPutDeviceAddressLeaseRuleData = z.object({
    body: zPutDeviceAddressLeaseRuleRequest,
    path: z.object({
        device_id: zId
    }),
    query: z.never().optional()
});

/**
 * Rule updated or created
 */
export const zPutDeviceAddressLeaseRuleResponse = zDeviceAddressLeaseRule;

export const zDisableMaxActiveAddressesRuleData = z.object({
    body: z.never().optional(),
    path: z.object({
        device_id: zId
    }),
    query: z.never().optional()
});

/**
 * Rule disabled
 */
export const zDisableMaxActiveAddressesRuleResponse = z.void();

export const zGetMaxActiveAddressesRuleData = z.object({
    body: z.never().optional(),
    path: z.object({
        device_id: zId
    }),
    query: z.never().optional()
});

/**
 * OK
 */
export const zGetMaxActiveAddressesRuleResponse = zMaxActiveAddressesRule;

export const zPutMaxActiveAddressesRuleData = z.object({
    body: zPutMaxActiveAddressesRuleRequest,
    path: z.object({
        device_id: zId
    }),
    query: z.never().optional()
});

/**
 * Rule updated or created
 */
export const zPutMaxActiveAddressesRuleResponse = zMaxActiveAddressesRule;

export const zGetDashboardStatsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        from: z.iso.datetime({ offset: true, local: true }).optional(),
        to: z.iso.datetime({ offset: true, local: true }).optional()
    }).optional()
});

/**
 * Summary statistics
 */
export const zGetDashboardStatsResponse = zDashboardStats;

export const zGetDashboardTrafficData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        from: z.iso.datetime({ offset: true, local: true }).optional(),
        to: z.iso.datetime({ offset: true, local: true }).optional(),
        granularity: z.enum(['hour', 'day']).optional()
    }).optional()
});

/**
 * Traffic time series
 */
export const zGetDashboardTrafficResponse = zDashboardTrafficResponse;

export const zGetDashboardServicesData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        from: z.iso.datetime({ offset: true, local: true }).optional(),
        to: z.iso.datetime({ offset: true, local: true }).optional()
    }).optional()
});

/**
 * Service breakdown
 */
export const zGetDashboardServicesResponse = zDashboardServicesResponse;

export const zGetDashboardTopDeniedIpsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        from: z.iso.datetime({ offset: true, local: true }).optional(),
        to: z.iso.datetime({ offset: true, local: true }).optional(),
        limit: z.int().lte(100).optional().default(10)
    }).optional()
});

/**
 * Top denied IPs
 */
export const zGetDashboardTopDeniedIpsResponse = zDashboardTopDeniedIpsResponse;

export const zClaimRegistrationData = z.object({
    body: zClaimRegistrationRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Registration successful — device created and config returned
 */
export const zClaimRegistrationResponse2 = zClaimRegistrationResponse;

export const zListRegistrationsData = z.object({
    body: z.never().optional(),
    path: z.never().optional(),
    query: z.object({
        status: z.enum(['pending', 'all']).optional()
    }).optional()
});

/**
 * List of registrations
 */
export const zListRegistrationsResponse = z.array(zPendingRegistration);

export const zCreateRegistrationData = z.object({
    body: zCreateRegistrationRequest,
    path: z.never().optional(),
    query: z.never().optional()
});

/**
 * Registration invite created — includes registration_code
 */
export const zCreateRegistrationResponse = zPendingRegistration;

export const zDeleteRegistrationData = z.object({
    body: z.never().optional(),
    path: z.object({
        registration_id: z.string()
    }),
    query: z.never().optional()
});

/**
 * Invite deleted
 */
export const zDeleteRegistrationResponse = z.void();

export const zGetRegistrationData = z.object({
    body: z.never().optional(),
    path: z.object({
        registration_id: z.string()
    }),
    query: z.never().optional()
});

/**
 * Registration invite
 */
export const zGetRegistrationResponse = zPendingRegistration;
