// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "apiKeyAuth.Scopes"
	CookieAuthScopes = "cookieAuth.Scopes"
)

// AddAddressRequest defines model for AddAddressRequest.
type AddAddressRequest struct {
	// Ip IPv4 or IPv6 address
	Ip IPAddress `json:"ip"`
}

// Address defines model for Address.
type Address struct {
	CreatedAt UTCTime `json:"created_at"`
	DeviceId  ID      `json:"device_id"`
	Id        ID      `json:"id"`

	// Ip IPv4 or IPv6 address
	Ip IPAddress `json:"ip"`

	// Status The latest state of this address, enabled or disabled
	Status bool `json:"status"`

	// UpdatedAt Last time it was enabled or disabled
	UpdatedAt UTCTime `json:"updated_at"`
}

// AuthRequest defines model for AuthRequest.
type AuthRequest struct {
	Password Password `json:"password"`

	// Username Unique username. Alphanumeric, underscores, and hyphens only.
	Username Username `json:"username"`
}

// CreateDeviceRequest defines model for CreateDeviceRequest.
type CreateDeviceRequest struct {
	// Name User-friendly name for the device
	Name string `json:"name"`
}

// CreateDeviceResponse defines model for CreateDeviceResponse.
type CreateDeviceResponse struct {
	// ApiKey Secret key for the device; only returned on creation.
	ApiKey string `json:"api_key"`
	Device Device `json:"device"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	// DisplayName User's public name. Unicode allowed.
	DisplayName DisplayName          `json:"display_name"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	Password    Password             `json:"password"`

	// Username Unique username. Alphanumeric, underscores, and hyphens only.
	Username Username `json:"username"`
}

// Device defines model for Device.
type Device struct {
	// ApiKeyPrefix Prefix of the device API key (for display only).
	ApiKeyPrefix string  `json:"api_key_prefix"`
	CreatedAt    UTCTime `json:"created_at"`
	Id           ID      `json:"id"`

	// Name User-friendly name for the device
	Name string `json:"name"`
}

// DeviceAddressLeaseRule defines model for DeviceAddressLeaseRule.
type DeviceAddressLeaseRule struct {
	CreatedAt UTCTime `json:"created_at"`
	DeviceId  ID      `json:"device_id"`

	// Enabled Whether the lease rule is active
	Enabled bool `json:"enabled"`
	Id      ID   `json:"id"`

	// TtlSeconds Seconds after which an enabled device address lease expires
	TtlSeconds int     `json:"ttl_seconds"`
	UpdatedAt  UTCTime `json:"updated_at"`
}

// DeviceHeartbeatByApiKeyRequest defines model for DeviceHeartbeatByApiKeyRequest.
type DeviceHeartbeatByApiKeyRequest struct {
	// Ip IPv4 or IPv6 address
	Ip *IPAddress `json:"ip,omitempty"`
}

// DisplayName User's public name. Unicode allowed.
type DisplayName = string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// ID defines model for ID.
type ID = int64

// IPAddress IPv4 or IPv6 address
type IPAddress = string

// Password defines model for Password.
type Password = string

// PutDeviceAddressLeaseRuleRequest defines model for PutDeviceAddressLeaseRuleRequest.
type PutDeviceAddressLeaseRuleRequest struct {
	// TtlSeconds Seconds after which an enabled device address lease expires
	TtlSeconds int `json:"ttl_seconds"`
}

// User defines model for User.
type User struct {
	CreatedAt UTCTime `json:"created_at"`

	// DisplayName User's public name. Unicode allowed.
	DisplayName DisplayName          `json:"display_name"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	Id          ID                   `json:"id"`

	// Username Unique username. Alphanumeric, underscores, and hyphens only.
	Username Username `json:"username"`
}

// Username Unique username. Alphanumeric, underscores, and hyphens only.
type Username = string

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = AuthRequest

// CreateDeviceJSONRequestBody defines body for CreateDevice for application/json ContentType.
type CreateDeviceJSONRequestBody = CreateDeviceRequest

// AddAddressJSONRequestBody defines body for AddAddress for application/json ContentType.
type AddAddressJSONRequestBody = AddAddressRequest

// PutDeviceAddressLeaseRuleJSONRequestBody defines body for PutDeviceAddressLeaseRule for application/json ContentType.
type PutDeviceAddressLeaseRuleJSONRequestBody = PutDeviceAddressLeaseRuleRequest

// DeviceHeartbeatByAPIKeyJSONRequestBody defines body for DeviceHeartbeatByAPIKey for application/json ContentType.
type DeviceHeartbeatByAPIKeyJSONRequestBody = DeviceHeartbeatByApiKeyRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Register a new user (Admin only)
	// (POST /admin/users)
	CreateUser(w http.ResponseWriter, r *http.Request)
	// Login user
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout user
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Get current user
	// (GET /auth/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// List all devices
	// (GET /devices)
	GetDevices(w http.ResponseWriter, r *http.Request)
	// Create a device
	// (POST /devices)
	CreateDevice(w http.ResponseWriter, r *http.Request)
	// Delete a device
	// (DELETE /devices/{device_id})
	DeleteDevice(w http.ResponseWriter, r *http.Request, deviceId ID)
	// Get a device
	// (GET /devices/{device_id})
	GetDevice(w http.ResponseWriter, r *http.Request, deviceId ID)
	// Get addresses for a device
	// (GET /devices/{device_id}/addresses)
	GetDeviceAddresses(w http.ResponseWriter, r *http.Request, deviceId ID)
	// Assign address to device
	// (POST /devices/{device_id}/addresses)
	AddAddress(w http.ResponseWriter, r *http.Request, deviceId ID)
	// Disable address
	// (DELETE /devices/{device_id}/addresses/{address_id})
	DisableAddress(w http.ResponseWriter, r *http.Request, deviceId ID, addressId ID)
	// Device heartbeat
	// (POST /devices/{device_id}/heartbeat)
	DeviceHeartbeat(w http.ResponseWriter, r *http.Request, deviceId ID)
	// Disable device lease rule for a device
	// (DELETE /devices/{device_id}/rules/address_lease)
	DisableDeviceAddressLeaseRule(w http.ResponseWriter, r *http.Request, deviceId ID)
	// Get IP auto-expiry rule for a device
	// (GET /devices/{device_id}/rules/address_lease)
	GetDeviceAddressLeaseRule(w http.ResponseWriter, r *http.Request, deviceId ID)
	// Create or update IP auto-expiry rule for a device
	// (PUT /devices/{device_id}/rules/address_lease)
	PutDeviceAddressLeaseRule(w http.ResponseWriter, r *http.Request, deviceId ID)
	// Performs a heartbeat with the given api key header
	// (POST /heartbeat)
	DeviceHeartbeatByAPIKey(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Register a new user (Admin only)
// (POST /admin/users)
func (_ Unimplemented) CreateUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Login user
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout user
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current user
// (GET /auth/me)
func (_ Unimplemented) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all devices
// (GET /devices)
func (_ Unimplemented) GetDevices(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a device
// (POST /devices)
func (_ Unimplemented) CreateDevice(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a device
// (DELETE /devices/{device_id})
func (_ Unimplemented) DeleteDevice(w http.ResponseWriter, r *http.Request, deviceId ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a device
// (GET /devices/{device_id})
func (_ Unimplemented) GetDevice(w http.ResponseWriter, r *http.Request, deviceId ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get addresses for a device
// (GET /devices/{device_id}/addresses)
func (_ Unimplemented) GetDeviceAddresses(w http.ResponseWriter, r *http.Request, deviceId ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Assign address to device
// (POST /devices/{device_id}/addresses)
func (_ Unimplemented) AddAddress(w http.ResponseWriter, r *http.Request, deviceId ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Disable address
// (DELETE /devices/{device_id}/addresses/{address_id})
func (_ Unimplemented) DisableAddress(w http.ResponseWriter, r *http.Request, deviceId ID, addressId ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Device heartbeat
// (POST /devices/{device_id}/heartbeat)
func (_ Unimplemented) DeviceHeartbeat(w http.ResponseWriter, r *http.Request, deviceId ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Disable device lease rule for a device
// (DELETE /devices/{device_id}/rules/address_lease)
func (_ Unimplemented) DisableDeviceAddressLeaseRule(w http.ResponseWriter, r *http.Request, deviceId ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get IP auto-expiry rule for a device
// (GET /devices/{device_id}/rules/address_lease)
func (_ Unimplemented) GetDeviceAddressLeaseRule(w http.ResponseWriter, r *http.Request, deviceId ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create or update IP auto-expiry rule for a device
// (PUT /devices/{device_id}/rules/address_lease)
func (_ Unimplemented) PutDeviceAddressLeaseRule(w http.ResponseWriter, r *http.Request, deviceId ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Performs a heartbeat with the given api key header
// (POST /heartbeat)
func (_ Unimplemented) DeviceHeartbeatByAPIKey(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDevices operation middleware
func (siw *ServerInterfaceWrapper) GetDevices(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDevices(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDevice operation middleware
func (siw *ServerInterfaceWrapper) CreateDevice(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDevice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDevice operation middleware
func (siw *ServerInterfaceWrapper) DeleteDevice(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId ID

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDevice(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDevice operation middleware
func (siw *ServerInterfaceWrapper) GetDevice(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId ID

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDevice(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDeviceAddresses operation middleware
func (siw *ServerInterfaceWrapper) GetDeviceAddresses(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId ID

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDeviceAddresses(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddAddress operation middleware
func (siw *ServerInterfaceWrapper) AddAddress(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId ID

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddAddress(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DisableAddress operation middleware
func (siw *ServerInterfaceWrapper) DisableAddress(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId ID

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	// ------------- Path parameter "address_id" -------------
	var addressId ID

	err = runtime.BindStyledParameterWithOptions("simple", "address_id", chi.URLParam(r, "address_id"), &addressId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "address_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DisableAddress(w, r, deviceId, addressId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeviceHeartbeat operation middleware
func (siw *ServerInterfaceWrapper) DeviceHeartbeat(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId ID

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeviceHeartbeat(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DisableDeviceAddressLeaseRule operation middleware
func (siw *ServerInterfaceWrapper) DisableDeviceAddressLeaseRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId ID

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DisableDeviceAddressLeaseRule(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDeviceAddressLeaseRule operation middleware
func (siw *ServerInterfaceWrapper) GetDeviceAddressLeaseRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId ID

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDeviceAddressLeaseRule(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutDeviceAddressLeaseRule operation middleware
func (siw *ServerInterfaceWrapper) PutDeviceAddressLeaseRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId ID

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutDeviceAddressLeaseRule(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeviceHeartbeatByAPIKey operation middleware
func (siw *ServerInterfaceWrapper) DeviceHeartbeatByAPIKey(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeviceHeartbeatByAPIKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/users", wrapper.CreateUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/devices", wrapper.GetDevices)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/devices", wrapper.CreateDevice)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/devices/{device_id}", wrapper.DeleteDevice)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/devices/{device_id}", wrapper.GetDevice)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/devices/{device_id}/addresses", wrapper.GetDeviceAddresses)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/devices/{device_id}/addresses", wrapper.AddAddress)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/devices/{device_id}/addresses/{address_id}", wrapper.DisableAddress)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/devices/{device_id}/heartbeat", wrapper.DeviceHeartbeat)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/devices/{device_id}/rules/address_lease", wrapper.DisableDeviceAddressLeaseRule)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/devices/{device_id}/rules/address_lease", wrapper.GetDeviceAddressLeaseRule)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/devices/{device_id}/rules/address_lease", wrapper.PutDeviceAddressLeaseRule)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/heartbeat", wrapper.DeviceHeartbeatByAPIKey)
	})

	return r
}

type CreateUserRequestObject struct {
	Body *CreateUserJSONRequestBody
}

type CreateUserResponseObject interface {
	VisitCreateUserResponse(w http.ResponseWriter) error
}

type CreateUser201JSONResponse User

func (response CreateUser201JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser400JSONResponse ErrorResponse

func (response CreateUser400JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser403Response struct {
}

func (response CreateUser403Response) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(403)
	return nil
}

type CreateUser409JSONResponse ErrorResponse

func (response CreateUser409JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser500JSONResponse ErrorResponse

func (response CreateUser500JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	SetCookie string
}

type Login200JSONResponse struct {
	Body    User
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type Login401JSONResponse ErrorResponse

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Login500JSONResponse ErrorResponse

func (response Login500JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204ResponseHeaders struct {
	SetCookie string
}

type Logout204Response struct {
	Headers Logout204ResponseHeaders
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(204)
	return nil
}

type GetCurrentUserRequestObject struct {
}

type GetCurrentUserResponseObject interface {
	VisitGetCurrentUserResponse(w http.ResponseWriter) error
}

type GetCurrentUser200JSONResponse User

func (response GetCurrentUser200JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUser401JSONResponse ErrorResponse

func (response GetCurrentUser401JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUser500JSONResponse ErrorResponse

func (response GetCurrentUser500JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDevicesRequestObject struct {
}

type GetDevicesResponseObject interface {
	VisitGetDevicesResponse(w http.ResponseWriter) error
}

type GetDevices200JSONResponse []Device

func (response GetDevices200JSONResponse) VisitGetDevicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDevices500JSONResponse ErrorResponse

func (response GetDevices500JSONResponse) VisitGetDevicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateDeviceRequestObject struct {
	Body *CreateDeviceJSONRequestBody
}

type CreateDeviceResponseObject interface {
	VisitCreateDeviceResponse(w http.ResponseWriter) error
}

type CreateDevice201JSONResponse CreateDeviceResponse

func (response CreateDevice201JSONResponse) VisitCreateDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateDevice400JSONResponse ErrorResponse

func (response CreateDevice400JSONResponse) VisitCreateDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateDevice409JSONResponse ErrorResponse

func (response CreateDevice409JSONResponse) VisitCreateDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateDevice500JSONResponse ErrorResponse

func (response CreateDevice500JSONResponse) VisitCreateDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteDeviceRequestObject struct {
	DeviceId ID `json:"device_id"`
}

type DeleteDeviceResponseObject interface {
	VisitDeleteDeviceResponse(w http.ResponseWriter) error
}

type DeleteDevice204Response struct {
}

func (response DeleteDevice204Response) VisitDeleteDeviceResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteDevice404JSONResponse ErrorResponse

func (response DeleteDevice404JSONResponse) VisitDeleteDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteDevice500JSONResponse ErrorResponse

func (response DeleteDevice500JSONResponse) VisitDeleteDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceRequestObject struct {
	DeviceId ID `json:"device_id"`
}

type GetDeviceResponseObject interface {
	VisitGetDeviceResponse(w http.ResponseWriter) error
}

type GetDevice200JSONResponse Device

func (response GetDevice200JSONResponse) VisitGetDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDevice404JSONResponse ErrorResponse

func (response GetDevice404JSONResponse) VisitGetDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetDevice500JSONResponse ErrorResponse

func (response GetDevice500JSONResponse) VisitGetDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceAddressesRequestObject struct {
	DeviceId ID `json:"device_id"`
}

type GetDeviceAddressesResponseObject interface {
	VisitGetDeviceAddressesResponse(w http.ResponseWriter) error
}

type GetDeviceAddresses200JSONResponse []Address

func (response GetDeviceAddresses200JSONResponse) VisitGetDeviceAddressesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceAddresses400JSONResponse ErrorResponse

func (response GetDeviceAddresses400JSONResponse) VisitGetDeviceAddressesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceAddresses404JSONResponse ErrorResponse

func (response GetDeviceAddresses404JSONResponse) VisitGetDeviceAddressesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceAddresses500JSONResponse ErrorResponse

func (response GetDeviceAddresses500JSONResponse) VisitGetDeviceAddressesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AddAddressRequestObject struct {
	DeviceId ID `json:"device_id"`
	Body     *AddAddressJSONRequestBody
}

type AddAddressResponseObject interface {
	VisitAddAddressResponse(w http.ResponseWriter) error
}

type AddAddress200JSONResponse Address

func (response AddAddress200JSONResponse) VisitAddAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AddAddress201JSONResponse Address

func (response AddAddress201JSONResponse) VisitAddAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type AddAddress400JSONResponse ErrorResponse

func (response AddAddress400JSONResponse) VisitAddAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AddAddress404JSONResponse ErrorResponse

func (response AddAddress404JSONResponse) VisitAddAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AddAddress500JSONResponse ErrorResponse

func (response AddAddress500JSONResponse) VisitAddAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DisableAddressRequestObject struct {
	DeviceId  ID `json:"device_id"`
	AddressId ID `json:"address_id"`
}

type DisableAddressResponseObject interface {
	VisitDisableAddressResponse(w http.ResponseWriter) error
}

type DisableAddress200JSONResponse Address

func (response DisableAddress200JSONResponse) VisitDisableAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DisableAddress400JSONResponse ErrorResponse

func (response DisableAddress400JSONResponse) VisitDisableAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DisableAddress404JSONResponse ErrorResponse

func (response DisableAddress404JSONResponse) VisitDisableAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DisableAddress500JSONResponse ErrorResponse

func (response DisableAddress500JSONResponse) VisitDisableAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeatRequestObject struct {
	DeviceId ID `json:"device_id"`
}

type DeviceHeartbeatResponseObject interface {
	VisitDeviceHeartbeatResponse(w http.ResponseWriter) error
}

type DeviceHeartbeat200JSONResponse Address

func (response DeviceHeartbeat200JSONResponse) VisitDeviceHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeat201JSONResponse Address

func (response DeviceHeartbeat201JSONResponse) VisitDeviceHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeat400JSONResponse ErrorResponse

func (response DeviceHeartbeat400JSONResponse) VisitDeviceHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeat404JSONResponse ErrorResponse

func (response DeviceHeartbeat404JSONResponse) VisitDeviceHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeat500JSONResponse ErrorResponse

func (response DeviceHeartbeat500JSONResponse) VisitDeviceHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DisableDeviceAddressLeaseRuleRequestObject struct {
	DeviceId ID `json:"device_id"`
}

type DisableDeviceAddressLeaseRuleResponseObject interface {
	VisitDisableDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error
}

type DisableDeviceAddressLeaseRule204Response struct {
}

func (response DisableDeviceAddressLeaseRule204Response) VisitDisableDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DisableDeviceAddressLeaseRule404JSONResponse ErrorResponse

func (response DisableDeviceAddressLeaseRule404JSONResponse) VisitDisableDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DisableDeviceAddressLeaseRule500JSONResponse ErrorResponse

func (response DisableDeviceAddressLeaseRule500JSONResponse) VisitDisableDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceAddressLeaseRuleRequestObject struct {
	DeviceId ID `json:"device_id"`
}

type GetDeviceAddressLeaseRuleResponseObject interface {
	VisitGetDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error
}

type GetDeviceAddressLeaseRule200JSONResponse DeviceAddressLeaseRule

func (response GetDeviceAddressLeaseRule200JSONResponse) VisitGetDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceAddressLeaseRule404JSONResponse ErrorResponse

func (response GetDeviceAddressLeaseRule404JSONResponse) VisitGetDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceAddressLeaseRule500JSONResponse ErrorResponse

func (response GetDeviceAddressLeaseRule500JSONResponse) VisitGetDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PutDeviceAddressLeaseRuleRequestObject struct {
	DeviceId ID `json:"device_id"`
	Body     *PutDeviceAddressLeaseRuleJSONRequestBody
}

type PutDeviceAddressLeaseRuleResponseObject interface {
	VisitPutDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error
}

type PutDeviceAddressLeaseRule200JSONResponse DeviceAddressLeaseRule

func (response PutDeviceAddressLeaseRule200JSONResponse) VisitPutDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutDeviceAddressLeaseRule400JSONResponse ErrorResponse

func (response PutDeviceAddressLeaseRule400JSONResponse) VisitPutDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PutDeviceAddressLeaseRule404JSONResponse ErrorResponse

func (response PutDeviceAddressLeaseRule404JSONResponse) VisitPutDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PutDeviceAddressLeaseRule500JSONResponse ErrorResponse

func (response PutDeviceAddressLeaseRule500JSONResponse) VisitPutDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeatByAPIKeyRequestObject struct {
	Body *DeviceHeartbeatByAPIKeyJSONRequestBody
}

type DeviceHeartbeatByAPIKeyResponseObject interface {
	VisitDeviceHeartbeatByAPIKeyResponse(w http.ResponseWriter) error
}

type DeviceHeartbeatByAPIKey200JSONResponse Address

func (response DeviceHeartbeatByAPIKey200JSONResponse) VisitDeviceHeartbeatByAPIKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeatByAPIKey201JSONResponse Address

func (response DeviceHeartbeatByAPIKey201JSONResponse) VisitDeviceHeartbeatByAPIKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeatByAPIKey400JSONResponse ErrorResponse

func (response DeviceHeartbeatByAPIKey400JSONResponse) VisitDeviceHeartbeatByAPIKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeatByAPIKey404JSONResponse ErrorResponse

func (response DeviceHeartbeatByAPIKey404JSONResponse) VisitDeviceHeartbeatByAPIKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeatByAPIKey500JSONResponse ErrorResponse

func (response DeviceHeartbeatByAPIKey500JSONResponse) VisitDeviceHeartbeatByAPIKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Register a new user (Admin only)
	// (POST /admin/users)
	CreateUser(ctx context.Context, request CreateUserRequestObject) (CreateUserResponseObject, error)
	// Login user
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout user
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Get current user
	// (GET /auth/me)
	GetCurrentUser(ctx context.Context, request GetCurrentUserRequestObject) (GetCurrentUserResponseObject, error)
	// List all devices
	// (GET /devices)
	GetDevices(ctx context.Context, request GetDevicesRequestObject) (GetDevicesResponseObject, error)
	// Create a device
	// (POST /devices)
	CreateDevice(ctx context.Context, request CreateDeviceRequestObject) (CreateDeviceResponseObject, error)
	// Delete a device
	// (DELETE /devices/{device_id})
	DeleteDevice(ctx context.Context, request DeleteDeviceRequestObject) (DeleteDeviceResponseObject, error)
	// Get a device
	// (GET /devices/{device_id})
	GetDevice(ctx context.Context, request GetDeviceRequestObject) (GetDeviceResponseObject, error)
	// Get addresses for a device
	// (GET /devices/{device_id}/addresses)
	GetDeviceAddresses(ctx context.Context, request GetDeviceAddressesRequestObject) (GetDeviceAddressesResponseObject, error)
	// Assign address to device
	// (POST /devices/{device_id}/addresses)
	AddAddress(ctx context.Context, request AddAddressRequestObject) (AddAddressResponseObject, error)
	// Disable address
	// (DELETE /devices/{device_id}/addresses/{address_id})
	DisableAddress(ctx context.Context, request DisableAddressRequestObject) (DisableAddressResponseObject, error)
	// Device heartbeat
	// (POST /devices/{device_id}/heartbeat)
	DeviceHeartbeat(ctx context.Context, request DeviceHeartbeatRequestObject) (DeviceHeartbeatResponseObject, error)
	// Disable device lease rule for a device
	// (DELETE /devices/{device_id}/rules/address_lease)
	DisableDeviceAddressLeaseRule(ctx context.Context, request DisableDeviceAddressLeaseRuleRequestObject) (DisableDeviceAddressLeaseRuleResponseObject, error)
	// Get IP auto-expiry rule for a device
	// (GET /devices/{device_id}/rules/address_lease)
	GetDeviceAddressLeaseRule(ctx context.Context, request GetDeviceAddressLeaseRuleRequestObject) (GetDeviceAddressLeaseRuleResponseObject, error)
	// Create or update IP auto-expiry rule for a device
	// (PUT /devices/{device_id}/rules/address_lease)
	PutDeviceAddressLeaseRule(ctx context.Context, request PutDeviceAddressLeaseRuleRequestObject) (PutDeviceAddressLeaseRuleResponseObject, error)
	// Performs a heartbeat with the given api key header
	// (POST /heartbeat)
	DeviceHeartbeatByAPIKey(ctx context.Context, request DeviceHeartbeatByAPIKeyRequestObject) (DeviceHeartbeatByAPIKeyResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateUser operation middleware
func (sh *strictHandler) CreateUser(w http.ResponseWriter, r *http.Request) {
	var request CreateUserRequestObject

	var body CreateUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUser(ctx, request.(CreateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateUserResponseObject); ok {
		if err := validResponse.VisitCreateUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCurrentUser operation middleware
func (sh *strictHandler) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	var request GetCurrentUserRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentUser(ctx, request.(GetCurrentUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCurrentUserResponseObject); ok {
		if err := validResponse.VisitGetCurrentUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDevices operation middleware
func (sh *strictHandler) GetDevices(w http.ResponseWriter, r *http.Request) {
	var request GetDevicesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDevices(ctx, request.(GetDevicesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDevices")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDevicesResponseObject); ok {
		if err := validResponse.VisitGetDevicesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDevice operation middleware
func (sh *strictHandler) CreateDevice(w http.ResponseWriter, r *http.Request) {
	var request CreateDeviceRequestObject

	var body CreateDeviceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDevice(ctx, request.(CreateDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDeviceResponseObject); ok {
		if err := validResponse.VisitCreateDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteDevice operation middleware
func (sh *strictHandler) DeleteDevice(w http.ResponseWriter, r *http.Request, deviceId ID) {
	var request DeleteDeviceRequestObject

	request.DeviceId = deviceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteDevice(ctx, request.(DeleteDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteDeviceResponseObject); ok {
		if err := validResponse.VisitDeleteDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDevice operation middleware
func (sh *strictHandler) GetDevice(w http.ResponseWriter, r *http.Request, deviceId ID) {
	var request GetDeviceRequestObject

	request.DeviceId = deviceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDevice(ctx, request.(GetDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDeviceResponseObject); ok {
		if err := validResponse.VisitGetDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDeviceAddresses operation middleware
func (sh *strictHandler) GetDeviceAddresses(w http.ResponseWriter, r *http.Request, deviceId ID) {
	var request GetDeviceAddressesRequestObject

	request.DeviceId = deviceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDeviceAddresses(ctx, request.(GetDeviceAddressesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDeviceAddresses")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDeviceAddressesResponseObject); ok {
		if err := validResponse.VisitGetDeviceAddressesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddAddress operation middleware
func (sh *strictHandler) AddAddress(w http.ResponseWriter, r *http.Request, deviceId ID) {
	var request AddAddressRequestObject

	request.DeviceId = deviceId

	var body AddAddressJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddAddress(ctx, request.(AddAddressRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddAddress")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddAddressResponseObject); ok {
		if err := validResponse.VisitAddAddressResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DisableAddress operation middleware
func (sh *strictHandler) DisableAddress(w http.ResponseWriter, r *http.Request, deviceId ID, addressId ID) {
	var request DisableAddressRequestObject

	request.DeviceId = deviceId
	request.AddressId = addressId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DisableAddress(ctx, request.(DisableAddressRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DisableAddress")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DisableAddressResponseObject); ok {
		if err := validResponse.VisitDisableAddressResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeviceHeartbeat operation middleware
func (sh *strictHandler) DeviceHeartbeat(w http.ResponseWriter, r *http.Request, deviceId ID) {
	var request DeviceHeartbeatRequestObject

	request.DeviceId = deviceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeviceHeartbeat(ctx, request.(DeviceHeartbeatRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeviceHeartbeat")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeviceHeartbeatResponseObject); ok {
		if err := validResponse.VisitDeviceHeartbeatResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DisableDeviceAddressLeaseRule operation middleware
func (sh *strictHandler) DisableDeviceAddressLeaseRule(w http.ResponseWriter, r *http.Request, deviceId ID) {
	var request DisableDeviceAddressLeaseRuleRequestObject

	request.DeviceId = deviceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DisableDeviceAddressLeaseRule(ctx, request.(DisableDeviceAddressLeaseRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DisableDeviceAddressLeaseRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DisableDeviceAddressLeaseRuleResponseObject); ok {
		if err := validResponse.VisitDisableDeviceAddressLeaseRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDeviceAddressLeaseRule operation middleware
func (sh *strictHandler) GetDeviceAddressLeaseRule(w http.ResponseWriter, r *http.Request, deviceId ID) {
	var request GetDeviceAddressLeaseRuleRequestObject

	request.DeviceId = deviceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDeviceAddressLeaseRule(ctx, request.(GetDeviceAddressLeaseRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDeviceAddressLeaseRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDeviceAddressLeaseRuleResponseObject); ok {
		if err := validResponse.VisitGetDeviceAddressLeaseRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutDeviceAddressLeaseRule operation middleware
func (sh *strictHandler) PutDeviceAddressLeaseRule(w http.ResponseWriter, r *http.Request, deviceId ID) {
	var request PutDeviceAddressLeaseRuleRequestObject

	request.DeviceId = deviceId

	var body PutDeviceAddressLeaseRuleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutDeviceAddressLeaseRule(ctx, request.(PutDeviceAddressLeaseRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutDeviceAddressLeaseRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutDeviceAddressLeaseRuleResponseObject); ok {
		if err := validResponse.VisitPutDeviceAddressLeaseRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeviceHeartbeatByAPIKey operation middleware
func (sh *strictHandler) DeviceHeartbeatByAPIKey(w http.ResponseWriter, r *http.Request) {
	var request DeviceHeartbeatByAPIKeyRequestObject

	var body DeviceHeartbeatByAPIKeyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeviceHeartbeatByAPIKey(ctx, request.(DeviceHeartbeatByAPIKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeviceHeartbeatByAPIKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeviceHeartbeatByAPIKeyResponseObject); ok {
		if err := validResponse.VisitDeviceHeartbeatByAPIKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xba2/buNL+KwTfBbaL15ekyRa7Pl+OG++2Ps22RpNiDxDkGIw4tthKpEpSTnwK//cD",
	"XnSzJNttE8e7yJcilSleZp6ZeWY4+oIDESeCA9cKD75gFYQQE/vnkNIhpRKUeg+fU1DaPEykSEBqBnYI",
	"S8y/P0iY4QH+v34xVd/P0x9P/Bx4tepgCZ9TJoHiwZV597qD9TIBPMDi5iMEGq86OBteWyuQQDTQKbH7",
	"mAkZm78wJRq6msWA88mUlozPcQffdeei6x9+uDy7NKNWHUxhwQKYMrp18yMzfOdxXyOMDlaa6NSejIIK",
	"JEs0ExwP8GUIKCIalEZmCCAxQzpkChH3bgcBJzcRUCQkokzZv4vD3wgRAeFmhTShJYlVVzknSiMjNsQ0",
	"uiWqZdJvF/O6ts1sheCttHIZdMrKrey7ESGpDlsRmRClboXcqrJJNs7ISYHkJIZt73zIxq0fLp+gU6zf",
	"tPMze8qRlULrCbKdVPVl1u7OJANOoyUyY9BMSKRDQE6quIPhjsRJZJacgFSCkwgloeDmp5jcnQOf6xAP",
	"fj7q4Jjx7L/H6/pcP5zdz/bTqERwBfXjkIRNP8GyfqILCCRo9AmWayf5BxI8WiIJOpXcIJIjCw8meK+G",
	"vtyctynP7bN2ulx42T7bT2pU0Ko1ylQSkeV0FxyN3Ni3xLkjiAmLzDuF/gyg/un/2wtEXLZEN7xBDo8N",
	"/YoItljCKNdZI1qmiYQZu6uDZmKfO5eY4QUNJ2MLo2cz57zMLiyGfmrEy/0Fkl0jw7eb9HfYrfWyXhcV",
	"97om43b1+GB1DkTB+zSCA4rJPlrVhfpnCDoEJ8XIbBzJNAJkwmeg2QIaA+Wuq2odTRUEglPV6M/MD4jM",
	"NEh0G7IgRITncdVj1Qdxvze4S5gEEwBjxlmcxmW9Mq5hDrIeyR8uKGdirR7168Kzw85rIFLfANEvl8OE",
	"vYHlvXHI+oIld9poZD8qlKQ3EQuskfXQB84CQQGRKBK3QHuV0PkvEXI0El9rfB38m5RCtsdBMD9XvbyH",
	"BBcazUTKKW4y6dpxx6MKBhjXL05xE2gKsRnHypfvZnhwVX4zWZw2+MfqiBf1EdedNRmPJ4tTwxvHk8WL",
	"DOAVmR7/+rx3/OKX3nHv+OR5k0uelEJX6bXnJ0PHEvLfS3EwKZ6VFHXyvKKoX5oWS3Wzf2uF6CPZ/Zq1",
	"lnfRZHgG6g/qou+B4mxnMbv64u9mLtbhtdOXktzahN0S1jn7nALKZu6hYZSEhKcxSBZ0UMopSBUICaqD",
	"CKcoXCYhcGUJS9UVfRQhn9J1V7SG8BPDtLQGadb+zxXp/veo++u0e/3/PzS6EwVBKpleXhjx5JzrDSxN",
	"VlU/TEatLLPySE51CFyzwDJy9Ax68x4KM3f/k0ntzJshEAoyoyAD/O/ucDLuvoFlsS23sKVkQnxikG3B",
	"vu8eFe9Pp6+F0t1bGkwVKGW2V5vIHJDxmaifY+T3zikaT3JjjAknc4iBa6SWSoPh2ZppK/w/SRQtRyxA",
	"/tU/irHDyRh38AKkcpMf947MIUQCnCQMD/BJ76h3bCmwDq2I+4TGjPcNJlyWKlRDTu7SDIUI4nBrAYRI",
	"EIiUa4MLY9RW5GOaj7Um72ANSr8U1OZZgeAauHa6TSKvqf5HZVbJSjzb7Kae86yqFqRlCvaBi3j2XM+P",
	"ju9tA/Zsds16REfeOpFKgwCUmqVRZIF0enR0bxuoBvSGnbwkFOXCMWuf1HX6u5A3jFLgqIvembTWIkGh",
	"gPis1nkK5Sb4dX+bzxyYCdzWGSMSSSDUJN5zpjQYJa86+Od9SnTMjSMjEboAuQCJ7AvOb6VxTOQSD/B7",
	"v72ymTwbGqm6nM/YMJkr4+KtrPG1eb9v3FY/EnPG2w1wWLg2UN4AOUUKtDFK40UDjV5fXk66tkLh/RBy",
	"rqpuo+d2tYcxz3IRbCfDPHpwwzwX8zlQxHjVKjs+FNh9XIDunjnPXllvPVCtrDkc7xN5CxIxamySGgiQ",
	"SB0S+n3UxoOr67ItWIRZoJZRb8JoFfQi1e2o90e3mDdp8w6wNvPVEHbaUGV2kBCpvhdMrNbObubdcnjH",
	"0ObQcO73tsDozhykUgLXxj+XfAC1s/+oEAVNWKTqsngF+sy9mofiPVudX955K79PvG/reSt0VXAHGTle",
	"gc4UvQE2juaqVtiYWUgUeTqs0A1Egs8ZnyMtLJbqCGrEzciv852YYRpitWvxu2DMUpJlkxzfvTlI1Z0z",
	"VZF6SXXZk+tVZyOv9nzBZzFZpXUXZZUvOh6UbVdvhhpE5XOR7DoE+a3gffLyxmufJsfkKPrjs/I9kuoz",
	"wWeRIYndLG20FDtj1i5WH6SB5TaSXz3U7avkHftf8rLxyhlcBLqhGHIhZrrrflT55D10WVzeMIVClyDN",
	"pIhRxJQh25yaDIkLjSQEwBZ5AQ0agvDIzp/bZ0IkiUFbdnHVUghwV9DclhF1WFQZysXwqkl1dtTGeIRX",
	"q+tdyNFbgc6c/gu4OFE15bWn+8PLaL0ufYiAdUrfDNjOhgiOFOPzKIfhzRIxrRCjG2L1oWLr/jSTX5K3",
	"8IInGDZxym9xmv3cn20lmtlNQv6GJS8EqQQCNmNB5lXbgTvM19oNwePDRvBOlLfUabUb531ckrJ/u2LU",
	"mtbvh21aa5ivGVphRu38f0ipJ/9Z4V+LgozUzKboezwgh/8AFcRae2eDnvwIRJRic25vP3bPOY7uc6/+",
	"/r99h55jwx1TGmjRJel6DJECa2n3mQlt2NVjJT9ZGTMDur9vfQrdDf5laDFd9gkbvcvWQN7/4v/clhSN",
	"XH+tqzyWNFVq/WpIctxLX+eZHjiQd760GGObRywEdLgceAdfU87Oim7pfdv6H0yZHCZPpG3vNik0sG+j",
	"z6RTtArk9t87zBTSaa7UsvQ1dp+3PLTfrHgrlJAIaZJLrfL6c9GF0EO/3WlJAu1vIiLmf7f1EPPIR1xb",
	"FQGuUglmLsTypv2e5ZLMPB9OxuhSfAJu1HDhbnKaKiaVHr2/R1rwnUad9T7ujyS8LTHSrKHB6fhxHEpG",
	"HkodMk/8YVMFym4yLFnR7um/TCNQGXeY2q7AnSmD966l9uYqeUDPbMdCRoC1QDMSKfiplVS0tHv/dUqp",
	"ZrtrgXj/aBXSKePAUeuDXjOIGjJsi9T2Ymr5Fp0lU5JqMbXtrctGaLIZCgSfsXkqgW4vWR08GO+79lo7",
	"90HVYv8aEH8Fjl+lWnTXobgR4Em6oStTSOS+fNgV6z1U6thGcao0ugGUCMU0WzRkeK196X/rMtTWbvw9",
	"d7ftboY26PiPYQw6gkO58H4iao1327kBf4tzMDxuh4zvwl73K7Q5Y0Q3qV7vo2cKJVIsGAWKFowgkrBu",
	"/dtYQ+bcIbbldC+Xw8nYtds/hNlu+cpr5a32KZ17SucO20sUnbXVL2GurleVVtsJSCM9hUiR8aFbpkNr",
	"nXO2AG5s1n4tk3/70pAPrq9Z/vTFr2n36AJ9KiM8wH2SsP7iGK+uV/8LAAD//7VnbD+wQwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
