// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package httpapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "apiKeyAuth.Scopes"
	CookieAuthScopes = "cookieAuth.Scopes"
)

// Defines values for UserRole.
const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

// AddAddressRequest defines model for AddAddressRequest.
type AddAddressRequest struct {
	// Ip IPv4 or IPv6 address
	Ip IPAddress `json:"ip"`
}

// Address defines model for Address.
type Address struct {
	CreatedAt UTCTime `json:"created_at"`
	DeviceId  ID      `json:"device_id"`

	// ExpiresAt UTC timestamp when this address will auto-expire, if an auto-expiry rule is enabled for the device. Null if no expiry is scheduled.
	ExpiresAt *UTCTime `json:"expires_at"`
	Id        ID       `json:"id"`

	// Ip IPv4 or IPv6 address
	Ip IPAddress `json:"ip"`

	// IsEnabled The latest state of this address, enabled or disabled
	IsEnabled bool `json:"is_enabled"`

	// UpdatedAt Last time it was enabled or disabled
	UpdatedAt UTCTime `json:"updated_at"`
}

// AdminUpdateUserRequest defines model for AdminUpdateUserRequest.
type AdminUpdateUserRequest struct {
	// Role The user's role. Only "admin" users can access admin endpoints.
	Role *UserRole `json:"role,omitempty"`
}

// AuthRequest defines model for AuthRequest.
type AuthRequest struct {
	Password Password `json:"password"`

	// Username Unique username. Alphanumeric, underscores, and hyphens only.
	Username Username `json:"username"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	CurrentPassword string `json:"current_password"`
	Password        string `json:"password"`
}

// CreateDeviceRequest defines model for CreateDeviceRequest.
type CreateDeviceRequest struct {
	// Name User-friendly name for the device
	Name string `json:"name"`
}

// CreateDeviceResponse defines model for CreateDeviceResponse.
type CreateDeviceResponse struct {
	// ApiKey Secret key for the device; only returned on creation.
	ApiKey string `json:"api_key"`
	Device Device `json:"device"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	// DisplayName User's public name. Unicode allowed.
	DisplayName DisplayName         `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Password    Password            `json:"password"`

	// Username Unique username. Alphanumeric, underscores, and hyphens only.
	Username Username `json:"username"`
}

// Device defines model for Device.
type Device struct {
	// AddressCount Number of currently enabled addresses for this device.
	AddressCount *int `json:"address_count,omitempty"`

	// ApiKeyPrefix Prefix of the device API key (for display only).
	ApiKeyPrefix string  `json:"api_key_prefix"`
	CreatedAt    UTCTime `json:"created_at"`
	Id           ID      `json:"id"`

	// Name User-friendly name for the device
	Name string `json:"name"`
}

// DeviceAddressLeaseRule defines model for DeviceAddressLeaseRule.
type DeviceAddressLeaseRule struct {
	CreatedAt UTCTime `json:"created_at"`
	DeviceId  ID      `json:"device_id"`

	// Enabled Whether the lease rule is active
	Enabled bool `json:"enabled"`
	Id      ID   `json:"id"`

	// TtlSeconds Seconds after which an enabled device address lease expires
	TtlSeconds int     `json:"ttl_seconds"`
	UpdatedAt  UTCTime `json:"updated_at"`
}

// DeviceHeartbeatByApiKeyRequest defines model for DeviceHeartbeatByApiKeyRequest.
type DeviceHeartbeatByApiKeyRequest struct {
	// Ip IPv4 or IPv6 address
	Ip *IPAddress `json:"ip,omitempty"`
}

// DisplayName User's public name. Unicode allowed.
type DisplayName = string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// ID defines model for ID.
type ID = int64

// IPAddress IPv4 or IPv6 address
type IPAddress = string

// Password defines model for Password.
type Password = string

// PutDeviceAddressLeaseRuleRequest defines model for PutDeviceAddressLeaseRuleRequest.
type PutDeviceAddressLeaseRuleRequest struct {
	// TtlSeconds Seconds after which an enabled device address lease expires
	TtlSeconds int `json:"ttl_seconds"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	// DisplayName User's public name. Unicode allowed.
	DisplayName *DisplayName         `json:"display_name,omitempty"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	Username    *string              `json:"username,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt UTCTime `json:"created_at"`

	// DisplayName User's public name. Unicode allowed.
	DisplayName DisplayName          `json:"display_name"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	Id          ID                   `json:"id"`

	// MustChangePassword When true, the user must change their password before using the app.
	MustChangePassword *bool `json:"must_change_password,omitempty"`

	// Role The user's role. Only "admin" users can access admin endpoints.
	Role UserRole `json:"role"`

	// Username Unique username. Alphanumeric, underscores, and hyphens only.
	Username Username `json:"username"`
}

// UserRole The user's role. Only "admin" users can access admin endpoints.
type UserRole string

// Username Unique username. Alphanumeric, underscores, and hyphens only.
type Username = string

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// AdminUpdateUserJSONRequestBody defines body for AdminUpdateUser for application/json ContentType.
type AdminUpdateUserJSONRequestBody = AdminUpdateUserRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = AuthRequest

// CreateDeviceJSONRequestBody defines body for CreateDevice for application/json ContentType.
type CreateDeviceJSONRequestBody = CreateDeviceRequest

// AddAddressJSONRequestBody defines body for AddAddress for application/json ContentType.
type AddAddressJSONRequestBody = AddAddressRequest

// PutDeviceAddressLeaseRuleJSONRequestBody defines body for PutDeviceAddressLeaseRule for application/json ContentType.
type PutDeviceAddressLeaseRuleJSONRequestBody = PutDeviceAddressLeaseRuleRequest

// DeviceHeartbeatByAPIKeyJSONRequestBody defines body for DeviceHeartbeatByAPIKey for application/json ContentType.
type DeviceHeartbeatByAPIKeyJSONRequestBody = DeviceHeartbeatByApiKeyRequest

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateProfileRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all users (Admin only)
	// (GET /admin/users)
	ListUsers(w http.ResponseWriter, r *http.Request)
	// Register a new user (Admin only)
	// (POST /admin/users)
	CreateUser(w http.ResponseWriter, r *http.Request)
	// Delete a user (Admin only)
	// (DELETE /admin/users/{user_id})
	DeleteUser(w http.ResponseWriter, r *http.Request, userId ID)
	// Update a user (Admin only)
	// (PATCH /admin/users/{user_id})
	AdminUpdateUser(w http.ResponseWriter, r *http.Request, userId ID)
	// Login user
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout user
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Get current user
	// (GET /auth/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// List all devices
	// (GET /devices)
	GetDevices(w http.ResponseWriter, r *http.Request)
	// Create a device
	// (POST /devices)
	CreateDevice(w http.ResponseWriter, r *http.Request)
	// Delete a device
	// (DELETE /devices/{device_id})
	DeleteDevice(w http.ResponseWriter, r *http.Request, deviceId ID)
	// Get a device
	// (GET /devices/{device_id})
	GetDevice(w http.ResponseWriter, r *http.Request, deviceId ID)
	// Get addresses for a device
	// (GET /devices/{device_id}/addresses)
	GetDeviceAddresses(w http.ResponseWriter, r *http.Request, deviceId ID)
	// Assign address to device
	// (POST /devices/{device_id}/addresses)
	AddAddress(w http.ResponseWriter, r *http.Request, deviceId ID)
	// Disable address
	// (DELETE /devices/{device_id}/addresses/{address_id})
	DisableAddress(w http.ResponseWriter, r *http.Request, deviceId ID, addressId ID)
	// Device heartbeat
	// (POST /devices/{device_id}/heartbeat)
	DeviceHeartbeat(w http.ResponseWriter, r *http.Request, deviceId ID)
	// Disable device lease rule for a device
	// (DELETE /devices/{device_id}/rules/address_lease)
	DisableDeviceAddressLeaseRule(w http.ResponseWriter, r *http.Request, deviceId ID)
	// Get address lease rule for a device
	// (GET /devices/{device_id}/rules/address_lease)
	GetDeviceAddressLeaseRule(w http.ResponseWriter, r *http.Request, deviceId ID)
	// Create or update IP auto-expiry rule for a device
	// (PUT /devices/{device_id}/rules/address_lease)
	PutDeviceAddressLeaseRule(w http.ResponseWriter, r *http.Request, deviceId ID)
	// Performs a heartbeat with the given api key header
	// (POST /heartbeat)
	DeviceHeartbeatByAPIKey(w http.ResponseWriter, r *http.Request)
	// Update current user profile
	// (PATCH /users/me)
	UpdateMe(w http.ResponseWriter, r *http.Request)
	// Change current user password
	// (POST /users/me/password)
	ChangePassword(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all users (Admin only)
// (GET /admin/users)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register a new user (Admin only)
// (POST /admin/users)
func (_ Unimplemented) CreateUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a user (Admin only)
// (DELETE /admin/users/{user_id})
func (_ Unimplemented) DeleteUser(w http.ResponseWriter, r *http.Request, userId ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a user (Admin only)
// (PATCH /admin/users/{user_id})
func (_ Unimplemented) AdminUpdateUser(w http.ResponseWriter, r *http.Request, userId ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Login user
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout user
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current user
// (GET /auth/me)
func (_ Unimplemented) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all devices
// (GET /devices)
func (_ Unimplemented) GetDevices(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a device
// (POST /devices)
func (_ Unimplemented) CreateDevice(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a device
// (DELETE /devices/{device_id})
func (_ Unimplemented) DeleteDevice(w http.ResponseWriter, r *http.Request, deviceId ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a device
// (GET /devices/{device_id})
func (_ Unimplemented) GetDevice(w http.ResponseWriter, r *http.Request, deviceId ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get addresses for a device
// (GET /devices/{device_id}/addresses)
func (_ Unimplemented) GetDeviceAddresses(w http.ResponseWriter, r *http.Request, deviceId ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Assign address to device
// (POST /devices/{device_id}/addresses)
func (_ Unimplemented) AddAddress(w http.ResponseWriter, r *http.Request, deviceId ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Disable address
// (DELETE /devices/{device_id}/addresses/{address_id})
func (_ Unimplemented) DisableAddress(w http.ResponseWriter, r *http.Request, deviceId ID, addressId ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Device heartbeat
// (POST /devices/{device_id}/heartbeat)
func (_ Unimplemented) DeviceHeartbeat(w http.ResponseWriter, r *http.Request, deviceId ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Disable device lease rule for a device
// (DELETE /devices/{device_id}/rules/address_lease)
func (_ Unimplemented) DisableDeviceAddressLeaseRule(w http.ResponseWriter, r *http.Request, deviceId ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get address lease rule for a device
// (GET /devices/{device_id}/rules/address_lease)
func (_ Unimplemented) GetDeviceAddressLeaseRule(w http.ResponseWriter, r *http.Request, deviceId ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create or update IP auto-expiry rule for a device
// (PUT /devices/{device_id}/rules/address_lease)
func (_ Unimplemented) PutDeviceAddressLeaseRule(w http.ResponseWriter, r *http.Request, deviceId ID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Performs a heartbeat with the given api key header
// (POST /heartbeat)
func (_ Unimplemented) DeviceHeartbeatByAPIKey(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update current user profile
// (PATCH /users/me)
func (_ Unimplemented) UpdateMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Change current user password
// (POST /users/me/password)
func (_ Unimplemented) ChangePassword(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId ID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUser(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AdminUpdateUser operation middleware
func (siw *ServerInterfaceWrapper) AdminUpdateUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "user_id" -------------
	var userId ID

	err = runtime.BindStyledParameterWithOptions("simple", "user_id", chi.URLParam(r, "user_id"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "user_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AdminUpdateUser(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDevices operation middleware
func (siw *ServerInterfaceWrapper) GetDevices(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDevices(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDevice operation middleware
func (siw *ServerInterfaceWrapper) CreateDevice(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDevice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDevice operation middleware
func (siw *ServerInterfaceWrapper) DeleteDevice(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId ID

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDevice(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDevice operation middleware
func (siw *ServerInterfaceWrapper) GetDevice(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId ID

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDevice(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDeviceAddresses operation middleware
func (siw *ServerInterfaceWrapper) GetDeviceAddresses(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId ID

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDeviceAddresses(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddAddress operation middleware
func (siw *ServerInterfaceWrapper) AddAddress(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId ID

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddAddress(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DisableAddress operation middleware
func (siw *ServerInterfaceWrapper) DisableAddress(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId ID

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	// ------------- Path parameter "address_id" -------------
	var addressId ID

	err = runtime.BindStyledParameterWithOptions("simple", "address_id", chi.URLParam(r, "address_id"), &addressId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "address_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DisableAddress(w, r, deviceId, addressId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeviceHeartbeat operation middleware
func (siw *ServerInterfaceWrapper) DeviceHeartbeat(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId ID

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeviceHeartbeat(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DisableDeviceAddressLeaseRule operation middleware
func (siw *ServerInterfaceWrapper) DisableDeviceAddressLeaseRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId ID

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DisableDeviceAddressLeaseRule(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDeviceAddressLeaseRule operation middleware
func (siw *ServerInterfaceWrapper) GetDeviceAddressLeaseRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId ID

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDeviceAddressLeaseRule(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutDeviceAddressLeaseRule operation middleware
func (siw *ServerInterfaceWrapper) PutDeviceAddressLeaseRule(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId ID

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutDeviceAddressLeaseRule(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeviceHeartbeatByAPIKey operation middleware
func (siw *ServerInterfaceWrapper) DeviceHeartbeatByAPIKey(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeviceHeartbeatByAPIKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMe operation middleware
func (siw *ServerInterfaceWrapper) UpdateMe(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ChangePassword operation middleware
func (siw *ServerInterfaceWrapper) ChangePassword(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ChangePassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/users", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/users", wrapper.CreateUser)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/admin/users/{user_id}", wrapper.DeleteUser)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/admin/users/{user_id}", wrapper.AdminUpdateUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/devices", wrapper.GetDevices)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/devices", wrapper.CreateDevice)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/devices/{device_id}", wrapper.DeleteDevice)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/devices/{device_id}", wrapper.GetDevice)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/devices/{device_id}/addresses", wrapper.GetDeviceAddresses)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/devices/{device_id}/addresses", wrapper.AddAddress)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/devices/{device_id}/addresses/{address_id}", wrapper.DisableAddress)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/devices/{device_id}/heartbeat", wrapper.DeviceHeartbeat)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/devices/{device_id}/rules/address_lease", wrapper.DisableDeviceAddressLeaseRule)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/devices/{device_id}/rules/address_lease", wrapper.GetDeviceAddressLeaseRule)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/devices/{device_id}/rules/address_lease", wrapper.PutDeviceAddressLeaseRule)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/heartbeat", wrapper.DeviceHeartbeatByAPIKey)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/users/me", wrapper.UpdateMe)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/users/me/password", wrapper.ChangePassword)
	})

	return r
}

type ListUsersRequestObject struct {
}

type ListUsersResponseObject interface {
	VisitListUsersResponse(w http.ResponseWriter) error
}

type ListUsers200JSONResponse []User

func (response ListUsers200JSONResponse) VisitListUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListUsers403Response struct {
}

func (response ListUsers403Response) VisitListUsersResponse(w http.ResponseWriter) error {
	w.WriteHeader(403)
	return nil
}

type ListUsers500JSONResponse ErrorResponse

func (response ListUsers500JSONResponse) VisitListUsersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateUserRequestObject struct {
	Body *CreateUserJSONRequestBody
}

type CreateUserResponseObject interface {
	VisitCreateUserResponse(w http.ResponseWriter) error
}

type CreateUser201JSONResponse User

func (response CreateUser201JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser400JSONResponse ErrorResponse

func (response CreateUser400JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser403Response struct {
}

func (response CreateUser403Response) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(403)
	return nil
}

type CreateUser409JSONResponse ErrorResponse

func (response CreateUser409JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser500JSONResponse ErrorResponse

func (response CreateUser500JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteUserRequestObject struct {
	UserId ID `json:"user_id"`
}

type DeleteUserResponseObject interface {
	VisitDeleteUserResponse(w http.ResponseWriter) error
}

type DeleteUser204Response struct {
}

func (response DeleteUser204Response) VisitDeleteUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteUser403JSONResponse ErrorResponse

func (response DeleteUser403JSONResponse) VisitDeleteUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteUser404JSONResponse ErrorResponse

func (response DeleteUser404JSONResponse) VisitDeleteUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteUser500JSONResponse ErrorResponse

func (response DeleteUser500JSONResponse) VisitDeleteUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AdminUpdateUserRequestObject struct {
	UserId ID `json:"user_id"`
	Body   *AdminUpdateUserJSONRequestBody
}

type AdminUpdateUserResponseObject interface {
	VisitAdminUpdateUserResponse(w http.ResponseWriter) error
}

type AdminUpdateUser200JSONResponse User

func (response AdminUpdateUser200JSONResponse) VisitAdminUpdateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AdminUpdateUser400JSONResponse ErrorResponse

func (response AdminUpdateUser400JSONResponse) VisitAdminUpdateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AdminUpdateUser403JSONResponse ErrorResponse

func (response AdminUpdateUser403JSONResponse) VisitAdminUpdateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type AdminUpdateUser404JSONResponse ErrorResponse

func (response AdminUpdateUser404JSONResponse) VisitAdminUpdateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AdminUpdateUser500JSONResponse ErrorResponse

func (response AdminUpdateUser500JSONResponse) VisitAdminUpdateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	SetCookie string
}

type Login200JSONResponse struct {
	Body    User
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type Login401JSONResponse ErrorResponse

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Login500JSONResponse ErrorResponse

func (response Login500JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204ResponseHeaders struct {
	SetCookie string
}

type Logout204Response struct {
	Headers Logout204ResponseHeaders
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(204)
	return nil
}

type GetCurrentUserRequestObject struct {
}

type GetCurrentUserResponseObject interface {
	VisitGetCurrentUserResponse(w http.ResponseWriter) error
}

type GetCurrentUser200JSONResponse User

func (response GetCurrentUser200JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUser401JSONResponse ErrorResponse

func (response GetCurrentUser401JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUser500JSONResponse ErrorResponse

func (response GetCurrentUser500JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDevicesRequestObject struct {
}

type GetDevicesResponseObject interface {
	VisitGetDevicesResponse(w http.ResponseWriter) error
}

type GetDevices200JSONResponse []Device

func (response GetDevices200JSONResponse) VisitGetDevicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDevices500JSONResponse ErrorResponse

func (response GetDevices500JSONResponse) VisitGetDevicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateDeviceRequestObject struct {
	Body *CreateDeviceJSONRequestBody
}

type CreateDeviceResponseObject interface {
	VisitCreateDeviceResponse(w http.ResponseWriter) error
}

type CreateDevice201JSONResponse CreateDeviceResponse

func (response CreateDevice201JSONResponse) VisitCreateDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateDevice400JSONResponse ErrorResponse

func (response CreateDevice400JSONResponse) VisitCreateDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateDevice409JSONResponse ErrorResponse

func (response CreateDevice409JSONResponse) VisitCreateDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateDevice500JSONResponse ErrorResponse

func (response CreateDevice500JSONResponse) VisitCreateDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteDeviceRequestObject struct {
	DeviceId ID `json:"device_id"`
}

type DeleteDeviceResponseObject interface {
	VisitDeleteDeviceResponse(w http.ResponseWriter) error
}

type DeleteDevice204Response struct {
}

func (response DeleteDevice204Response) VisitDeleteDeviceResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteDevice404JSONResponse ErrorResponse

func (response DeleteDevice404JSONResponse) VisitDeleteDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteDevice500JSONResponse ErrorResponse

func (response DeleteDevice500JSONResponse) VisitDeleteDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceRequestObject struct {
	DeviceId ID `json:"device_id"`
}

type GetDeviceResponseObject interface {
	VisitGetDeviceResponse(w http.ResponseWriter) error
}

type GetDevice200JSONResponse Device

func (response GetDevice200JSONResponse) VisitGetDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDevice404JSONResponse ErrorResponse

func (response GetDevice404JSONResponse) VisitGetDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetDevice500JSONResponse ErrorResponse

func (response GetDevice500JSONResponse) VisitGetDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceAddressesRequestObject struct {
	DeviceId ID `json:"device_id"`
}

type GetDeviceAddressesResponseObject interface {
	VisitGetDeviceAddressesResponse(w http.ResponseWriter) error
}

type GetDeviceAddresses200JSONResponse []Address

func (response GetDeviceAddresses200JSONResponse) VisitGetDeviceAddressesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceAddresses400JSONResponse ErrorResponse

func (response GetDeviceAddresses400JSONResponse) VisitGetDeviceAddressesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceAddresses404JSONResponse ErrorResponse

func (response GetDeviceAddresses404JSONResponse) VisitGetDeviceAddressesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceAddresses500JSONResponse ErrorResponse

func (response GetDeviceAddresses500JSONResponse) VisitGetDeviceAddressesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AddAddressRequestObject struct {
	DeviceId ID `json:"device_id"`
	Body     *AddAddressJSONRequestBody
}

type AddAddressResponseObject interface {
	VisitAddAddressResponse(w http.ResponseWriter) error
}

type AddAddress200JSONResponse Address

func (response AddAddress200JSONResponse) VisitAddAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AddAddress201JSONResponse Address

func (response AddAddress201JSONResponse) VisitAddAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type AddAddress400JSONResponse ErrorResponse

func (response AddAddress400JSONResponse) VisitAddAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AddAddress404JSONResponse ErrorResponse

func (response AddAddress404JSONResponse) VisitAddAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AddAddress500JSONResponse ErrorResponse

func (response AddAddress500JSONResponse) VisitAddAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DisableAddressRequestObject struct {
	DeviceId  ID `json:"device_id"`
	AddressId ID `json:"address_id"`
}

type DisableAddressResponseObject interface {
	VisitDisableAddressResponse(w http.ResponseWriter) error
}

type DisableAddress200JSONResponse Address

func (response DisableAddress200JSONResponse) VisitDisableAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DisableAddress400JSONResponse ErrorResponse

func (response DisableAddress400JSONResponse) VisitDisableAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DisableAddress404JSONResponse ErrorResponse

func (response DisableAddress404JSONResponse) VisitDisableAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DisableAddress500JSONResponse ErrorResponse

func (response DisableAddress500JSONResponse) VisitDisableAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeatRequestObject struct {
	DeviceId ID `json:"device_id"`
}

type DeviceHeartbeatResponseObject interface {
	VisitDeviceHeartbeatResponse(w http.ResponseWriter) error
}

type DeviceHeartbeat200JSONResponse Address

func (response DeviceHeartbeat200JSONResponse) VisitDeviceHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeat201JSONResponse Address

func (response DeviceHeartbeat201JSONResponse) VisitDeviceHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeat400JSONResponse ErrorResponse

func (response DeviceHeartbeat400JSONResponse) VisitDeviceHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeat404JSONResponse ErrorResponse

func (response DeviceHeartbeat404JSONResponse) VisitDeviceHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeat500JSONResponse ErrorResponse

func (response DeviceHeartbeat500JSONResponse) VisitDeviceHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DisableDeviceAddressLeaseRuleRequestObject struct {
	DeviceId ID `json:"device_id"`
}

type DisableDeviceAddressLeaseRuleResponseObject interface {
	VisitDisableDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error
}

type DisableDeviceAddressLeaseRule204Response struct {
}

func (response DisableDeviceAddressLeaseRule204Response) VisitDisableDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DisableDeviceAddressLeaseRule404JSONResponse ErrorResponse

func (response DisableDeviceAddressLeaseRule404JSONResponse) VisitDisableDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DisableDeviceAddressLeaseRule500JSONResponse ErrorResponse

func (response DisableDeviceAddressLeaseRule500JSONResponse) VisitDisableDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceAddressLeaseRuleRequestObject struct {
	DeviceId ID `json:"device_id"`
}

type GetDeviceAddressLeaseRuleResponseObject interface {
	VisitGetDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error
}

type GetDeviceAddressLeaseRule200JSONResponse DeviceAddressLeaseRule

func (response GetDeviceAddressLeaseRule200JSONResponse) VisitGetDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceAddressLeaseRule404JSONResponse ErrorResponse

func (response GetDeviceAddressLeaseRule404JSONResponse) VisitGetDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceAddressLeaseRule500JSONResponse ErrorResponse

func (response GetDeviceAddressLeaseRule500JSONResponse) VisitGetDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PutDeviceAddressLeaseRuleRequestObject struct {
	DeviceId ID `json:"device_id"`
	Body     *PutDeviceAddressLeaseRuleJSONRequestBody
}

type PutDeviceAddressLeaseRuleResponseObject interface {
	VisitPutDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error
}

type PutDeviceAddressLeaseRule200JSONResponse DeviceAddressLeaseRule

func (response PutDeviceAddressLeaseRule200JSONResponse) VisitPutDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PutDeviceAddressLeaseRule400JSONResponse ErrorResponse

func (response PutDeviceAddressLeaseRule400JSONResponse) VisitPutDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PutDeviceAddressLeaseRule404JSONResponse ErrorResponse

func (response PutDeviceAddressLeaseRule404JSONResponse) VisitPutDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type PutDeviceAddressLeaseRule500JSONResponse ErrorResponse

func (response PutDeviceAddressLeaseRule500JSONResponse) VisitPutDeviceAddressLeaseRuleResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeatByAPIKeyRequestObject struct {
	Body *DeviceHeartbeatByAPIKeyJSONRequestBody
}

type DeviceHeartbeatByAPIKeyResponseObject interface {
	VisitDeviceHeartbeatByAPIKeyResponse(w http.ResponseWriter) error
}

type DeviceHeartbeatByAPIKey200JSONResponse Address

func (response DeviceHeartbeatByAPIKey200JSONResponse) VisitDeviceHeartbeatByAPIKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeatByAPIKey201JSONResponse Address

func (response DeviceHeartbeatByAPIKey201JSONResponse) VisitDeviceHeartbeatByAPIKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeatByAPIKey400JSONResponse ErrorResponse

func (response DeviceHeartbeatByAPIKey400JSONResponse) VisitDeviceHeartbeatByAPIKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeatByAPIKey404JSONResponse ErrorResponse

func (response DeviceHeartbeatByAPIKey404JSONResponse) VisitDeviceHeartbeatByAPIKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeatByAPIKey500JSONResponse ErrorResponse

func (response DeviceHeartbeatByAPIKey500JSONResponse) VisitDeviceHeartbeatByAPIKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateMeRequestObject struct {
	Body *UpdateMeJSONRequestBody
}

type UpdateMeResponseObject interface {
	VisitUpdateMeResponse(w http.ResponseWriter) error
}

type UpdateMe200JSONResponse User

func (response UpdateMe200JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateMe400JSONResponse ErrorResponse

func (response UpdateMe400JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateMe401JSONResponse ErrorResponse

func (response UpdateMe401JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateMe409JSONResponse ErrorResponse

func (response UpdateMe409JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type UpdateMe500JSONResponse ErrorResponse

func (response UpdateMe500JSONResponse) VisitUpdateMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ChangePasswordRequestObject struct {
	Body *ChangePasswordJSONRequestBody
}

type ChangePasswordResponseObject interface {
	VisitChangePasswordResponse(w http.ResponseWriter) error
}

type ChangePassword204Response struct {
}

func (response ChangePassword204Response) VisitChangePasswordResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ChangePassword400JSONResponse ErrorResponse

func (response ChangePassword400JSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ChangePassword401JSONResponse ErrorResponse

func (response ChangePassword401JSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ChangePassword500JSONResponse ErrorResponse

func (response ChangePassword500JSONResponse) VisitChangePasswordResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all users (Admin only)
	// (GET /admin/users)
	ListUsers(ctx context.Context, request ListUsersRequestObject) (ListUsersResponseObject, error)
	// Register a new user (Admin only)
	// (POST /admin/users)
	CreateUser(ctx context.Context, request CreateUserRequestObject) (CreateUserResponseObject, error)
	// Delete a user (Admin only)
	// (DELETE /admin/users/{user_id})
	DeleteUser(ctx context.Context, request DeleteUserRequestObject) (DeleteUserResponseObject, error)
	// Update a user (Admin only)
	// (PATCH /admin/users/{user_id})
	AdminUpdateUser(ctx context.Context, request AdminUpdateUserRequestObject) (AdminUpdateUserResponseObject, error)
	// Login user
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout user
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Get current user
	// (GET /auth/me)
	GetCurrentUser(ctx context.Context, request GetCurrentUserRequestObject) (GetCurrentUserResponseObject, error)
	// List all devices
	// (GET /devices)
	GetDevices(ctx context.Context, request GetDevicesRequestObject) (GetDevicesResponseObject, error)
	// Create a device
	// (POST /devices)
	CreateDevice(ctx context.Context, request CreateDeviceRequestObject) (CreateDeviceResponseObject, error)
	// Delete a device
	// (DELETE /devices/{device_id})
	DeleteDevice(ctx context.Context, request DeleteDeviceRequestObject) (DeleteDeviceResponseObject, error)
	// Get a device
	// (GET /devices/{device_id})
	GetDevice(ctx context.Context, request GetDeviceRequestObject) (GetDeviceResponseObject, error)
	// Get addresses for a device
	// (GET /devices/{device_id}/addresses)
	GetDeviceAddresses(ctx context.Context, request GetDeviceAddressesRequestObject) (GetDeviceAddressesResponseObject, error)
	// Assign address to device
	// (POST /devices/{device_id}/addresses)
	AddAddress(ctx context.Context, request AddAddressRequestObject) (AddAddressResponseObject, error)
	// Disable address
	// (DELETE /devices/{device_id}/addresses/{address_id})
	DisableAddress(ctx context.Context, request DisableAddressRequestObject) (DisableAddressResponseObject, error)
	// Device heartbeat
	// (POST /devices/{device_id}/heartbeat)
	DeviceHeartbeat(ctx context.Context, request DeviceHeartbeatRequestObject) (DeviceHeartbeatResponseObject, error)
	// Disable device lease rule for a device
	// (DELETE /devices/{device_id}/rules/address_lease)
	DisableDeviceAddressLeaseRule(ctx context.Context, request DisableDeviceAddressLeaseRuleRequestObject) (DisableDeviceAddressLeaseRuleResponseObject, error)
	// Get address lease rule for a device
	// (GET /devices/{device_id}/rules/address_lease)
	GetDeviceAddressLeaseRule(ctx context.Context, request GetDeviceAddressLeaseRuleRequestObject) (GetDeviceAddressLeaseRuleResponseObject, error)
	// Create or update IP auto-expiry rule for a device
	// (PUT /devices/{device_id}/rules/address_lease)
	PutDeviceAddressLeaseRule(ctx context.Context, request PutDeviceAddressLeaseRuleRequestObject) (PutDeviceAddressLeaseRuleResponseObject, error)
	// Performs a heartbeat with the given api key header
	// (POST /heartbeat)
	DeviceHeartbeatByAPIKey(ctx context.Context, request DeviceHeartbeatByAPIKeyRequestObject) (DeviceHeartbeatByAPIKeyResponseObject, error)
	// Update current user profile
	// (PATCH /users/me)
	UpdateMe(ctx context.Context, request UpdateMeRequestObject) (UpdateMeResponseObject, error)
	// Change current user password
	// (POST /users/me/password)
	ChangePassword(ctx context.Context, request ChangePasswordRequestObject) (ChangePasswordResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListUsers operation middleware
func (sh *strictHandler) ListUsers(w http.ResponseWriter, r *http.Request) {
	var request ListUsersRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListUsers(ctx, request.(ListUsersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListUsers")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListUsersResponseObject); ok {
		if err := validResponse.VisitListUsersResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateUser operation middleware
func (sh *strictHandler) CreateUser(w http.ResponseWriter, r *http.Request) {
	var request CreateUserRequestObject

	var body CreateUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUser(ctx, request.(CreateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateUserResponseObject); ok {
		if err := validResponse.VisitCreateUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteUser operation middleware
func (sh *strictHandler) DeleteUser(w http.ResponseWriter, r *http.Request, userId ID) {
	var request DeleteUserRequestObject

	request.UserId = userId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteUser(ctx, request.(DeleteUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteUserResponseObject); ok {
		if err := validResponse.VisitDeleteUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AdminUpdateUser operation middleware
func (sh *strictHandler) AdminUpdateUser(w http.ResponseWriter, r *http.Request, userId ID) {
	var request AdminUpdateUserRequestObject

	request.UserId = userId

	var body AdminUpdateUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AdminUpdateUser(ctx, request.(AdminUpdateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AdminUpdateUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AdminUpdateUserResponseObject); ok {
		if err := validResponse.VisitAdminUpdateUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCurrentUser operation middleware
func (sh *strictHandler) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	var request GetCurrentUserRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentUser(ctx, request.(GetCurrentUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCurrentUserResponseObject); ok {
		if err := validResponse.VisitGetCurrentUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDevices operation middleware
func (sh *strictHandler) GetDevices(w http.ResponseWriter, r *http.Request) {
	var request GetDevicesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDevices(ctx, request.(GetDevicesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDevices")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDevicesResponseObject); ok {
		if err := validResponse.VisitGetDevicesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDevice operation middleware
func (sh *strictHandler) CreateDevice(w http.ResponseWriter, r *http.Request) {
	var request CreateDeviceRequestObject

	var body CreateDeviceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDevice(ctx, request.(CreateDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDeviceResponseObject); ok {
		if err := validResponse.VisitCreateDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteDevice operation middleware
func (sh *strictHandler) DeleteDevice(w http.ResponseWriter, r *http.Request, deviceId ID) {
	var request DeleteDeviceRequestObject

	request.DeviceId = deviceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteDevice(ctx, request.(DeleteDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteDeviceResponseObject); ok {
		if err := validResponse.VisitDeleteDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDevice operation middleware
func (sh *strictHandler) GetDevice(w http.ResponseWriter, r *http.Request, deviceId ID) {
	var request GetDeviceRequestObject

	request.DeviceId = deviceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDevice(ctx, request.(GetDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDeviceResponseObject); ok {
		if err := validResponse.VisitGetDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDeviceAddresses operation middleware
func (sh *strictHandler) GetDeviceAddresses(w http.ResponseWriter, r *http.Request, deviceId ID) {
	var request GetDeviceAddressesRequestObject

	request.DeviceId = deviceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDeviceAddresses(ctx, request.(GetDeviceAddressesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDeviceAddresses")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDeviceAddressesResponseObject); ok {
		if err := validResponse.VisitGetDeviceAddressesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddAddress operation middleware
func (sh *strictHandler) AddAddress(w http.ResponseWriter, r *http.Request, deviceId ID) {
	var request AddAddressRequestObject

	request.DeviceId = deviceId

	var body AddAddressJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddAddress(ctx, request.(AddAddressRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddAddress")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddAddressResponseObject); ok {
		if err := validResponse.VisitAddAddressResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DisableAddress operation middleware
func (sh *strictHandler) DisableAddress(w http.ResponseWriter, r *http.Request, deviceId ID, addressId ID) {
	var request DisableAddressRequestObject

	request.DeviceId = deviceId
	request.AddressId = addressId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DisableAddress(ctx, request.(DisableAddressRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DisableAddress")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DisableAddressResponseObject); ok {
		if err := validResponse.VisitDisableAddressResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeviceHeartbeat operation middleware
func (sh *strictHandler) DeviceHeartbeat(w http.ResponseWriter, r *http.Request, deviceId ID) {
	var request DeviceHeartbeatRequestObject

	request.DeviceId = deviceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeviceHeartbeat(ctx, request.(DeviceHeartbeatRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeviceHeartbeat")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeviceHeartbeatResponseObject); ok {
		if err := validResponse.VisitDeviceHeartbeatResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DisableDeviceAddressLeaseRule operation middleware
func (sh *strictHandler) DisableDeviceAddressLeaseRule(w http.ResponseWriter, r *http.Request, deviceId ID) {
	var request DisableDeviceAddressLeaseRuleRequestObject

	request.DeviceId = deviceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DisableDeviceAddressLeaseRule(ctx, request.(DisableDeviceAddressLeaseRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DisableDeviceAddressLeaseRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DisableDeviceAddressLeaseRuleResponseObject); ok {
		if err := validResponse.VisitDisableDeviceAddressLeaseRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDeviceAddressLeaseRule operation middleware
func (sh *strictHandler) GetDeviceAddressLeaseRule(w http.ResponseWriter, r *http.Request, deviceId ID) {
	var request GetDeviceAddressLeaseRuleRequestObject

	request.DeviceId = deviceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDeviceAddressLeaseRule(ctx, request.(GetDeviceAddressLeaseRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDeviceAddressLeaseRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDeviceAddressLeaseRuleResponseObject); ok {
		if err := validResponse.VisitGetDeviceAddressLeaseRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutDeviceAddressLeaseRule operation middleware
func (sh *strictHandler) PutDeviceAddressLeaseRule(w http.ResponseWriter, r *http.Request, deviceId ID) {
	var request PutDeviceAddressLeaseRuleRequestObject

	request.DeviceId = deviceId

	var body PutDeviceAddressLeaseRuleJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutDeviceAddressLeaseRule(ctx, request.(PutDeviceAddressLeaseRuleRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutDeviceAddressLeaseRule")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutDeviceAddressLeaseRuleResponseObject); ok {
		if err := validResponse.VisitPutDeviceAddressLeaseRuleResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeviceHeartbeatByAPIKey operation middleware
func (sh *strictHandler) DeviceHeartbeatByAPIKey(w http.ResponseWriter, r *http.Request) {
	var request DeviceHeartbeatByAPIKeyRequestObject

	var body DeviceHeartbeatByAPIKeyJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeviceHeartbeatByAPIKey(ctx, request.(DeviceHeartbeatByAPIKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeviceHeartbeatByAPIKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeviceHeartbeatByAPIKeyResponseObject); ok {
		if err := validResponse.VisitDeviceHeartbeatByAPIKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateMe operation middleware
func (sh *strictHandler) UpdateMe(w http.ResponseWriter, r *http.Request) {
	var request UpdateMeRequestObject

	var body UpdateMeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateMe(ctx, request.(UpdateMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateMeResponseObject); ok {
		if err := validResponse.VisitUpdateMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ChangePassword operation middleware
func (sh *strictHandler) ChangePassword(w http.ResponseWriter, r *http.Request) {
	var request ChangePasswordRequestObject

	var body ChangePasswordJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ChangePassword(ctx, request.(ChangePasswordRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ChangePassword")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ChangePasswordResponseObject); ok {
		if err := validResponse.VisitChangePasswordResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xca3PbNtb+Kxi8nWk6LyXZsZtttV9WsXvRJk01ib3dWdergYkjEQ0FsAAoR5vRf9/B",
	"hXdSkhNbVrv+0sYUAR4Az3NuPIcfcSgWieDAtcLDj1iFESyI/eeI0hGlEpR6C7+noLS5mEiRgNQM7C0s",
	"Mf/9QsIMD/H/DYqpBn6ewXji58DrdYAl/J4yCRQPr8zY6wDrVQJ4iMXNbxBqvA5wdnvjWaEEooFOiZVj",
	"JuTC/AtToqGn2QJwPpnSkvE5DvCH3lz0/MXLi7MLc9c6wBSWLIQpo1uFPze3w4eESVD+wRRUKFmimeBu",
	"VmQerjRZJOg2Ao50xBQibhXolsUxIqkWPTdLgNgMEV66tEIyjQExhYCTmxgomgmJdATIidlHb9I4NsO4",
	"QH4EU8iISNMYaP9XjoP27eBpHJsp8VDLFMzuE/ozj1fZ3ztu1677dCcwBJipqV9xc1svIkAx0aA0Uppo",
	"QGJW2dcg3ywhEWXKTZOv6EaIGAg3T0kTWkJN9SmvidL29BDT6Jaojkk/HWp1xJvZCvDZHavsQ1AGeUX2",
	"dqYsGL+091wqkJ0klcJAYPPJ2AnMfUbm5pNSHXVOnxClboXcCpJJdp85FQWSk8VOYtn76luZTxAUz2/b",
	"o7OI8Dlkj+5cQ5hKCVxPy2upnvA6qCx0QT68Bj7XER7+5XmAF4xnf35Tx0Zd9Mazti3BQuLcwqZzAdlm",
	"1rSTAtmbSQacxitk7qkpF2y0G1kkBiB4AlIJTmKURIKbn0qL/PqossjjbYu08mxfjUoEV9BcDknY9D2s",
	"mit6B6EEjd7DqraSvyLB4xWSoFPJDYU5slxigvcbdM1twDb8OTkbq8s3L5Oze6UbmUmZSmKymu5ChXN3",
	"7xvilDIsCIvNmOL8DCf+5v/sh2JRVl3u9mAzqB+DvZUtCHI5NzLiPD+7GmqccZiGIuUt6v5NurgBaUyJ",
	"p2C8yjW+HwrKw4qpzPxiC3y2SBd4eNRpQxnXMAdppPOYmCYSZuxDU4yJve4sWoZeNJqMLaifzZztMXti",
	"Ef1VK3rvzxfa1bh/uoL5DC1ijaRHRsUy1va4GyTe33gNRMHbNIZDciu7nJ9fItARuF2MjeC5h0hCzZbQ",
	"6ufs+lSt46mCUHCqWrWr+QGRmQaJbiMWRsZZzUjisZr5tk427x2XaXLcRouqI/ZwPlXhS5WXejfPymHn",
	"RyBS3wDRL1ejhL2C1b2FQc0HlpR7K8m+VChJb2IWWpL10SVnoaCASByLW6D9iiH/u4g4Ohd3JV+Av5NS",
	"yG6rDObnqs3xkOBCo5lIOcVtlG4sd3xewQDj+sUpbgNNsW1GvfPVzzM8vCqPTJanLfqxeseL5h3XQW2P",
	"x5PlqXH7x5PliwzglT09/vZ5//jFN/3j/vHJ8zaVPCkZ0tKw5ycj57NMCncvF67kAt7FoQzwJNXt+q0T",
	"oo/E+xpby1K0Ec9FMxMpZmzDWu7DbdruGZW9nNLpnFRP58T4KlqDNPv47yvS+8+o96+j3rfT3vX/f7Eb",
	"Gwy/H9Qu7WW7djVAi1TpaWjDskq41bCBHFkPy5pBcxbIjERupLnIJMrGoxuYCWluY3xuB5AkMTqxw1sr",
	"2c27Bcf34PtaI9XtAFt5OnapYsSuO5D01i+omVBJnR0xT+gjsyvoV0zogvFfsf1NoZBwRMLQkNz+gIDT",
	"RDCulTUw3JD8yo3xiyiJUUDhsrRHNVPG2e+pk8TZsVGcRISnC5AsDFDKKUgVCgkqQIRTFK2SCLiynnDV",
	"xv0mIj6ldRv32eRUEKaS6dU7c4x5LPoKVqPUTFhfT+a2W6/da8lUR8A1C23siZ5Bf95HUeZKfIUDzMzI",
	"CAgFmbm3Q/zP3mgy7r2CVSGWe7B194V4zyATwY53l4rx0+mPQuneLQ2nCpQy4jUmMgtkfCaa6zj3snOK",
	"xpNc0S8IJ3NYANdIrZQGE1Fqpu3+/0LieHXOQuSH/lTcO5qMcYCXIJWb/Lh/ZBYhEuAkYXiIT/pH/WMb",
	"5OnIbvHAQmpgQWj+nkNL+PbWhvbKuDyIC96jEIMG6qBrwGG0p930McVD/JopfWknNPxzLo2d/PnRkdWv",
	"gmtwYSJJktif1+A3ZR6W5cHtdmtYqF3ojgvlTqQkfsObvpxCMVOWr6dHJ811fi/kDaMUOOo5ltrNceQ0",
	"A92CzfCv77iSTQuoun4tko+54RGJ0TuQS5DIDnCcSRcLIld+z+35OHXyzGYoXRhroEPmqtAf1+sAJ0K1",
	"HLRLnChEEIdbp/pJaGP65ikXSRbs1Cwo/VLQ1b3tSzOLs65qdGNY1g2IHd+bAA5Z7UhC3h4glVqtPUvj",
	"eOWAtUdkvCQU5ZvzCaB2iyhgfXr07f6Ez2yVcf6tb4NIbLyGFZIwZ0qDOeRD5NpbL16ZJlsItw4qmnbw",
	"0fxvyujanZdRpy2xgZhpr2sNJR0dOUUSluI9qJzuyJudFlV8bkd7kiZEkgVoq+mvvDEzhqAwZV4qXGdZ",
	"sOP2Gj/TRHg1Sp62R9YosyNNDp3s78TL/AgJN/G0kwspiGcGnDExutWepBXudL8cKYX4h8gGB7EMn9sN",
	"D9Fhmztnh7nkkEKEC5uHK/vNDWzXXsLtGeD3b+86XiruZPSO9mP0fPLuEI3e/pWFVQ8GmllkXFEVKBbh",
	"e5HqJ5XRVBkO5DuqDGs6Ux0NYjFnVtJ233VURH+gCmOpQBvjaQLNUKMfLy4mPfu60ttM5KK5liDGPu2B",
	"mF56qX8g9H4t5nOgiPEqtwMfLVs53oHunbngt/K8eiy/tpA/3ifmliRm1Liz1ECAxAcVpPnEBh5eXVdC",
	"NoMwC9Qy6lMd1UBvlEgn6v3SLeZ1BLvA2sy3i4vmISFSfS+YWNfWbubdsniXx9qYkjBrLt4plzJAPj3x",
	"pUIUNGFxi3P8A+gzNzSPYvfMOv94p628nHjf7HkjdHXjDtJm/AA6O+gNsHGZwO5MlpnFhE3+PnQDseBz",
	"m7oWLnvdQFArbs79c/aR4MoqYbanuH5+ddi5KZrvWnZ02ZVtKSkfavtEb1bosMthlaueHjRRVS0Ta9kq",
	"n67NaqOQFwXvM6XVWgPWpphcduvxffs95qPOBJ/FxknsZZl1m53KklLOVh8kwXKO5JU/TX6VtOPgY161",
	"cZf8U1YUfVHUTjGFIhcOzaRY2By5sl63T6RICIEtoajx6spQ5fyshfCtDHIFvM3gvlyL8tD5qzcCnbnz",
	"L+DSnc7aY/h3Xi8LOeic0QbABhssOFKMz+MchjcrxLRCjG6w1YeKrfs7mbxitsMveIJhm0/5KUpzkOuz",
	"rY5me5UrQSqBkM1YWKp17QDuKH/WbggeHzaCd3J5S70qu/m8j+uk7J9XjFpqfX/Y1KphvkG0gkbd/v+I",
	"Uu/8Z7URWhTOSMtLgaxz7oAU/kO8K6g3CLack78DEaXYnNsCkd1jjqP7lNWX33ZL6H1s+MCUBlr0mClN",
	"dKqQAsu0+4yENkj1WMFPlsbMgO4r/55Md4t+GVlMl3XCRu2y1ZAPPmYtLFuConPXnegyj6WTKveNNoMc",
	"N+humumBDXnwsYOMXRqx2KDD9YF30DXl6KzoNd03139iylbM0tyeGxNZnMC+SZ/tTlFNmfO/f5ghpDu5",
	"UsfAXXifV4V2v1nxLJSQCGmCS63y/HNRqNlH333QkoTav4mImf/d5kPMJW9xbVYEuEolmLlKTed960sy",
	"c300GaML8R64OYZ37k1OW8ak0iLz5wgLPpPUWevR/pyENyWPNKsFdGf8OAolcx5KRcRP/sOmDJQVMiqx",
	"aPfwX6YxqMx3mNqmnJ1dBq9dS92FVecBPbMVC5kDrAWakVjBV51ORUe35R8nlWrErRni/aNVSHcYB45a",
	"b/TaQdQSYVukdidTy2/Rqz1mbchkMxQKPmPzVALdnrE6eCzed+q1se6DSsX+MRBeyhvdCd5JuqGdQci8",
	"stTAmSVTkmoxLX8EqP7ln1K7pOt+uwGUCMU0W7bEd51NoX/qJNTWVtg917btzkJrcrJiVpE3c/wvZpIP",
	"Wx34N9s5ga17W/+A1xblYLy4HeK9d/Zlv0Kb40V0k+p6oyFTKJFiyShQtGQEkYT1mp/JMa6cW8S2iO7l",
	"ajQZu37Eh6Dtlk8srD1rn4K5p2DusLVEUVdbbRW+ul5XCm0nIM3uKUSKeA/dMh1Zds7ZErjhrG0nzpuD",
	"26NB173l6lI7OlkuvaeRfUrImPIg77u2zdWDvOPtLpVsbuKfHqqKrfUDEIfUfJI40TK7/fjG+rFrdJ+6",
	"Ne/QbFKuHc6gVKK5a4GtknxQ/khGu9Pwj7z4Pps/GxPkIUdxpd686Zrcurs3q59QfKjq1dbvNO5E/JZk",
	"TjaP74l65Faxs9qhGFftVgo+NyjmcFv5gTmj+1R/3+6Jux63Ko0KZDZ4VDfQ5Q9peANtH+ai4lTGeIgH",
	"JGGD5TFeX6//GwAA//9aV96dHVkAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
