// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// AddAddressRequest defines model for AddAddressRequest.
type AddAddressRequest struct {
	// Ip IPv4 or IPv6 address
	Ip string `json:"ip"`
}

// Address defines model for Address.
type Address struct {
	CreatedAt time.Time `json:"created_at"`
	DeviceId  int64     `json:"device_id"`
	ID        int64     `json:"id"`

	// IP IPv4 or IPv6 address
	IP string `json:"ip"`
}

// CreateDeviceRequest defines model for CreateDeviceRequest.
type CreateDeviceRequest struct {
	Name string `json:"name"`
}

// Device defines model for Device.
type Device struct {
	CreatedAt time.Time `json:"created_at"`
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// CreateDeviceJSONRequestBody defines body for CreateDevice for application/json ContentType.
type CreateDeviceJSONRequestBody = CreateDeviceRequest

// AddAddressJSONRequestBody defines body for AddAddress for application/json ContentType.
type AddAddressJSONRequestBody = AddAddressRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all devices
	// (GET /devices)
	GetDevices(w http.ResponseWriter, r *http.Request)
	// Create a device
	// (POST /devices)
	CreateDevice(w http.ResponseWriter, r *http.Request)
	// Get addresses for a device
	// (GET /devices/{device_id}/addresses)
	GetDeviceAddresses(w http.ResponseWriter, r *http.Request, deviceId int64)
	// Assign address to device
	// (POST /devices/{device_id}/addresses)
	AddAddress(w http.ResponseWriter, r *http.Request, deviceId int64)
	// Disable address
	// (DELETE /devices/{device_id}/addresses/{address_id})
	DisableAddress(w http.ResponseWriter, r *http.Request, deviceId int64, addressId int64)
	// Device heartbeat endpoint
	// (POST /devices/{device_id}/heartbeat)
	DeviceHeartbeat(w http.ResponseWriter, r *http.Request, deviceId int64)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all devices
// (GET /devices)
func (_ Unimplemented) GetDevices(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a device
// (POST /devices)
func (_ Unimplemented) CreateDevice(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get addresses for a device
// (GET /devices/{device_id}/addresses)
func (_ Unimplemented) GetDeviceAddresses(w http.ResponseWriter, r *http.Request, deviceId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Assign address to device
// (POST /devices/{device_id}/addresses)
func (_ Unimplemented) AddAddress(w http.ResponseWriter, r *http.Request, deviceId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Disable address
// (DELETE /devices/{device_id}/addresses/{address_id})
func (_ Unimplemented) DisableAddress(w http.ResponseWriter, r *http.Request, deviceId int64, addressId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Device heartbeat endpoint
// (POST /devices/{device_id}/heartbeat)
func (_ Unimplemented) DeviceHeartbeat(w http.ResponseWriter, r *http.Request, deviceId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetDevices operation middleware
func (siw *ServerInterfaceWrapper) GetDevices(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDevices(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDevice operation middleware
func (siw *ServerInterfaceWrapper) CreateDevice(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDevice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDeviceAddresses operation middleware
func (siw *ServerInterfaceWrapper) GetDeviceAddresses(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId int64

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDeviceAddresses(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddAddress operation middleware
func (siw *ServerInterfaceWrapper) AddAddress(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId int64

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddAddress(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DisableAddress operation middleware
func (siw *ServerInterfaceWrapper) DisableAddress(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId int64

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	// ------------- Path parameter "address_id" -------------
	var addressId int64

	err = runtime.BindStyledParameterWithOptions("simple", "address_id", chi.URLParam(r, "address_id"), &addressId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "address_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DisableAddress(w, r, deviceId, addressId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeviceHeartbeat operation middleware
func (siw *ServerInterfaceWrapper) DeviceHeartbeat(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId int64

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeviceHeartbeat(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/devices", wrapper.GetDevices)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/devices", wrapper.CreateDevice)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/devices/{device_id}/addresses", wrapper.GetDeviceAddresses)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/devices/{device_id}/addresses", wrapper.AddAddress)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/devices/{device_id}/addresses/{address_id}", wrapper.DisableAddress)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/devices/{device_id}/heartbeat", wrapper.DeviceHeartbeat)
	})

	return r
}

type GetDevicesRequestObject struct {
}

type GetDevicesResponseObject interface {
	VisitGetDevicesResponse(w http.ResponseWriter) error
}

type GetDevices200JSONResponse []Device

func (response GetDevices200JSONResponse) VisitGetDevicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDevices500JSONResponse ErrorResponse

func (response GetDevices500JSONResponse) VisitGetDevicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateDeviceRequestObject struct {
	Body *CreateDeviceJSONRequestBody
}

type CreateDeviceResponseObject interface {
	VisitCreateDeviceResponse(w http.ResponseWriter) error
}

type CreateDevice201JSONResponse Device

func (response CreateDevice201JSONResponse) VisitCreateDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateDevice400JSONResponse ErrorResponse

func (response CreateDevice400JSONResponse) VisitCreateDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateDevice500JSONResponse ErrorResponse

func (response CreateDevice500JSONResponse) VisitCreateDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceAddressesRequestObject struct {
	DeviceId int64 `json:"device_id"`
}

type GetDeviceAddressesResponseObject interface {
	VisitGetDeviceAddressesResponse(w http.ResponseWriter) error
}

type GetDeviceAddresses200JSONResponse []Address

func (response GetDeviceAddresses200JSONResponse) VisitGetDeviceAddressesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceAddresses400JSONResponse ErrorResponse

func (response GetDeviceAddresses400JSONResponse) VisitGetDeviceAddressesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceAddresses404JSONResponse ErrorResponse

func (response GetDeviceAddresses404JSONResponse) VisitGetDeviceAddressesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceAddresses500JSONResponse ErrorResponse

func (response GetDeviceAddresses500JSONResponse) VisitGetDeviceAddressesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AddAddressRequestObject struct {
	DeviceId int64 `json:"device_id"`
	Body     *AddAddressJSONRequestBody
}

type AddAddressResponseObject interface {
	VisitAddAddressResponse(w http.ResponseWriter) error
}

type AddAddress201JSONResponse Address

func (response AddAddress201JSONResponse) VisitAddAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type AddAddress400JSONResponse ErrorResponse

func (response AddAddress400JSONResponse) VisitAddAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AddAddress404JSONResponse ErrorResponse

func (response AddAddress404JSONResponse) VisitAddAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AddAddress500JSONResponse ErrorResponse

func (response AddAddress500JSONResponse) VisitAddAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DisableAddressRequestObject struct {
	DeviceId  int64 `json:"device_id"`
	AddressId int64 `json:"address_id"`
}

type DisableAddressResponseObject interface {
	VisitDisableAddressResponse(w http.ResponseWriter) error
}

type DisableAddress200JSONResponse Address

func (response DisableAddress200JSONResponse) VisitDisableAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DisableAddress400JSONResponse ErrorResponse

func (response DisableAddress400JSONResponse) VisitDisableAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DisableAddress404JSONResponse ErrorResponse

func (response DisableAddress404JSONResponse) VisitDisableAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DisableAddress409JSONResponse ErrorResponse

func (response DisableAddress409JSONResponse) VisitDisableAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type DisableAddress500JSONResponse ErrorResponse

func (response DisableAddress500JSONResponse) VisitDisableAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeatRequestObject struct {
	DeviceId int64 `json:"device_id"`
}

type DeviceHeartbeatResponseObject interface {
	VisitDeviceHeartbeatResponse(w http.ResponseWriter) error
}

type DeviceHeartbeat200JSONResponse Address

func (response DeviceHeartbeat200JSONResponse) VisitDeviceHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeat201JSONResponse Address

func (response DeviceHeartbeat201JSONResponse) VisitDeviceHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeat400JSONResponse ErrorResponse

func (response DeviceHeartbeat400JSONResponse) VisitDeviceHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeat404JSONResponse ErrorResponse

func (response DeviceHeartbeat404JSONResponse) VisitDeviceHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeat500JSONResponse ErrorResponse

func (response DeviceHeartbeat500JSONResponse) VisitDeviceHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all devices
	// (GET /devices)
	GetDevices(ctx context.Context, request GetDevicesRequestObject) (GetDevicesResponseObject, error)
	// Create a device
	// (POST /devices)
	CreateDevice(ctx context.Context, request CreateDeviceRequestObject) (CreateDeviceResponseObject, error)
	// Get addresses for a device
	// (GET /devices/{device_id}/addresses)
	GetDeviceAddresses(ctx context.Context, request GetDeviceAddressesRequestObject) (GetDeviceAddressesResponseObject, error)
	// Assign address to device
	// (POST /devices/{device_id}/addresses)
	AddAddress(ctx context.Context, request AddAddressRequestObject) (AddAddressResponseObject, error)
	// Disable address
	// (DELETE /devices/{device_id}/addresses/{address_id})
	DisableAddress(ctx context.Context, request DisableAddressRequestObject) (DisableAddressResponseObject, error)
	// Device heartbeat endpoint
	// (POST /devices/{device_id}/heartbeat)
	DeviceHeartbeat(ctx context.Context, request DeviceHeartbeatRequestObject) (DeviceHeartbeatResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetDevices operation middleware
func (sh *strictHandler) GetDevices(w http.ResponseWriter, r *http.Request) {
	var request GetDevicesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDevices(ctx, request.(GetDevicesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDevices")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDevicesResponseObject); ok {
		if err := validResponse.VisitGetDevicesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDevice operation middleware
func (sh *strictHandler) CreateDevice(w http.ResponseWriter, r *http.Request) {
	var request CreateDeviceRequestObject

	var body CreateDeviceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDevice(ctx, request.(CreateDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDeviceResponseObject); ok {
		if err := validResponse.VisitCreateDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDeviceAddresses operation middleware
func (sh *strictHandler) GetDeviceAddresses(w http.ResponseWriter, r *http.Request, deviceId int64) {
	var request GetDeviceAddressesRequestObject

	request.DeviceId = deviceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDeviceAddresses(ctx, request.(GetDeviceAddressesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDeviceAddresses")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDeviceAddressesResponseObject); ok {
		if err := validResponse.VisitGetDeviceAddressesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddAddress operation middleware
func (sh *strictHandler) AddAddress(w http.ResponseWriter, r *http.Request, deviceId int64) {
	var request AddAddressRequestObject

	request.DeviceId = deviceId

	var body AddAddressJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddAddress(ctx, request.(AddAddressRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddAddress")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddAddressResponseObject); ok {
		if err := validResponse.VisitAddAddressResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DisableAddress operation middleware
func (sh *strictHandler) DisableAddress(w http.ResponseWriter, r *http.Request, deviceId int64, addressId int64) {
	var request DisableAddressRequestObject

	request.DeviceId = deviceId
	request.AddressId = addressId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DisableAddress(ctx, request.(DisableAddressRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DisableAddress")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DisableAddressResponseObject); ok {
		if err := validResponse.VisitDisableAddressResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeviceHeartbeat operation middleware
func (sh *strictHandler) DeviceHeartbeat(w http.ResponseWriter, r *http.Request, deviceId int64) {
	var request DeviceHeartbeatRequestObject

	request.DeviceId = deviceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeviceHeartbeat(ctx, request.(DeviceHeartbeatRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeviceHeartbeat")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeviceHeartbeatResponseObject); ok {
		if err := validResponse.VisitDeviceHeartbeatResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xYW2/jNhP9KwS/76EFFF+SbND1m7fZtkY3rbF96EMRLBhxLHMrkdwh5cQw9N8LkrpG",
	"8ubS1DGKvgQOOeQMZ845Q2pHY5VpJUFaQ2c7auI1ZMz/nHM+5xzBmI/wJQdj3aBGpQGtAG8itPvLwcQo",
	"tBVK0hldLDfnRCFZLDcXhIUNaEThjmU6BTqj07eno+nFd6PpaHp2SiNqt9oNG4tCJrQoIorwJRcInM7+",
	"cC6uaxt18xliS4uIlpH1Q4oRmAX+iflwVwoz94tyZuHEigz6DiPKYSNi+CR4Z4mQ9uK8MRfSQgLo7B9n",
	"GNG7k0SdSJa50cWlX/n4hHWjvLfZsp8nTtsH8a6idjaGsvi9n770q/YWOfjctSq4BDRKspTotZIuoxm7",
	"+wAysWs6ezOJaCZk9e/ZQ/X1uw/FFqJ6mQI/v2DV4R8AqUu4N30w5e8RFX4Eo5U0A6cDN93NdigqkcqS",
	"lcolH6TMPT9uSMiV6qMtpJUwycliWcGNZEyyBDKQlpitsZA5J8J6/7+zNN1eipiUS68a2/lyQSO6ATRh",
	"8+lo4s6oNEimBZ3Rs9FkNKUR1cyu/fnG4TT+dwK2H9+PYAlLU1LaESGJXUMTlUsWc7YLHqwvyw1dRUJW",
	"/eank4lHi5IWpPfDtE5F7NeOPxvnrJI7L2UWMr/w/wgrOqP/GzfCOC5VcVxissk3Q2TbkO7uMX792Vm9",
	"eWIQX/PdBc6Ay4W0gI6VvwFuAIlf4MFh8ixjuKUz+kGYTnpdmVliHIarkesiolqZgdIEtSCMSLgtNyC3",
	"wq59gRKxAUlKDnSL1FYZGogDxr5TfPtiyRkSsoEUlQj2FBVKkjIU2mazxRyKHpimLxZqhaF+dOEQ3AHn",
	"/JDAecc4qZN2hKCtcccrCPUxW0S1tIx3dRssxqXAPUJwQLKbFDipV5CVQsKI0RCLlYgb73skaF67cnqH",
	"LAML6MLcI8EL36XdgFPHqoHMOk28C8uolfUHrynF9SEUsbqHPVoSXxPZ55Pzw/kuqyy479w/+M59jOzy",
	"+L+H+R7RGhrtbw9zzsveUN0qrGrv1aVN87p4JF3EIejy8p2p/4oaqFNpQZgxIpH+avUarakm8/H0poXc",
	"sFTUqkxCHck3WW4suQESZttPqG9fi+nNBf0YaT730GpT86skf7CfjnflTzccxCAFC31ZuGL4J2GNZ2YI",
	"Fyb02ntq01WIy2D1NJX4p5tqtNtD3X3y1GTpldv5M4lfnc/kcQzGrPI03dYFPLgcXAljhEyq14fgjvWs",
	"KcGhqV9lp+a+i+cWVR1iiOjt4SNiKQLj3VIdnSiVFG9/9XqCFq2Bob2B8CFo+E5SqgKCVmgNEdaQOEd0",
	"Dbb5+jEi7+8sstga/5KNU1HOr1Blfqhsxv6rSa4NhL28fLnpENOILFZuFdwJY423FaZ6VkQEweYoTZgW",
	"MvHmVXXc9EkwdTv7OQm3UXiqhrG+QHq3P9VZ+Hc8O/6mTlW431MFR092T83q1HuSHOhC9Uvrnhy/8uWq",
	"9SHwv/vVc6UsBFlrEgHJtRLSDn+ucGv9ZoGpOaZ0RsdMi/FmSovr4q8AAAD//42LHr+YGQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
