// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

// AddDeviceIPRequest defines model for AddDeviceIPRequest.
type AddDeviceIPRequest struct {
	IpAddress string `json:"ip_address" validate:"ipv4"`
}

// CreateDeviceRequest defines model for CreateDeviceRequest.
type CreateDeviceRequest struct {
	Name string `json:"name"`
}

// Device defines model for Device.
type Device struct {
	CreatedAt time.Time `json:"created_at"`
	Id        int64     `json:"id"`
	Name      string    `json:"name"`
}

// DeviceIP defines model for DeviceIP.
type DeviceIP struct {
	CreatedAt  time.Time  `json:"created_at"`
	DeviceId   int64      `json:"device_id"`
	DisabledAt *time.Time `json:"disabled_at"`
	Id         int64      `json:"id"`
	IpAddress  string     `json:"ip_address"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// CreateDeviceJSONRequestBody defines body for CreateDevice for application/json ContentType.
type CreateDeviceJSONRequestBody = CreateDeviceRequest

// AddDeviceIpJSONRequestBody defines body for AddDeviceIp for application/json ContentType.
type AddDeviceIpJSONRequestBody = AddDeviceIPRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all devices
	// (GET /devices)
	GetDevices(w http.ResponseWriter, r *http.Request)
	// Create a device
	// (POST /devices)
	CreateDevice(w http.ResponseWriter, r *http.Request)
	// Get IPs for a device
	// (GET /devices/{id}/ips)
	GetDeviceIps(w http.ResponseWriter, r *http.Request, id int64)
	// Assign IP to device
	// (POST /devices/{id}/ips)
	AddDeviceIp(w http.ResponseWriter, r *http.Request, id int64)
	// Disable device IP
	// (PATCH /devices/{id}/ips/{ip_id}/disable)
	DisableDeviceIp(w http.ResponseWriter, r *http.Request, id int64, ipId int64)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all devices
// (GET /devices)
func (_ Unimplemented) GetDevices(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a device
// (POST /devices)
func (_ Unimplemented) CreateDevice(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get IPs for a device
// (GET /devices/{id}/ips)
func (_ Unimplemented) GetDeviceIps(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Assign IP to device
// (POST /devices/{id}/ips)
func (_ Unimplemented) AddDeviceIp(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Disable device IP
// (PATCH /devices/{id}/ips/{ip_id}/disable)
func (_ Unimplemented) DisableDeviceIp(w http.ResponseWriter, r *http.Request, id int64, ipId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetDevices operation middleware
func (siw *ServerInterfaceWrapper) GetDevices(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDevices(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDevice operation middleware
func (siw *ServerInterfaceWrapper) CreateDevice(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDevice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDeviceIps operation middleware
func (siw *ServerInterfaceWrapper) GetDeviceIps(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDeviceIps(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddDeviceIp operation middleware
func (siw *ServerInterfaceWrapper) AddDeviceIp(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddDeviceIp(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DisableDeviceIp operation middleware
func (siw *ServerInterfaceWrapper) DisableDeviceIp(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// ------------- Path parameter "ip_id" -------------
	var ipId int64

	err = runtime.BindStyledParameterWithOptions("simple", "ip_id", chi.URLParam(r, "ip_id"), &ipId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "ip_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DisableDeviceIp(w, r, id, ipId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/devices", wrapper.GetDevices)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/devices", wrapper.CreateDevice)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/devices/{id}/ips", wrapper.GetDeviceIps)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/devices/{id}/ips", wrapper.AddDeviceIp)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/devices/{id}/ips/{ip_id}/disable", wrapper.DisableDeviceIp)
	})

	return r
}

type GetDevicesRequestObject struct {
}

type GetDevicesResponseObject interface {
	VisitGetDevicesResponse(w http.ResponseWriter) error
}

type GetDevices200JSONResponse []Device

func (response GetDevices200JSONResponse) VisitGetDevicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDevices500JSONResponse ErrorResponse

func (response GetDevices500JSONResponse) VisitGetDevicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateDeviceRequestObject struct {
	Body *CreateDeviceJSONRequestBody
}

type CreateDeviceResponseObject interface {
	VisitCreateDeviceResponse(w http.ResponseWriter) error
}

type CreateDevice201JSONResponse Device

func (response CreateDevice201JSONResponse) VisitCreateDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateDevice400JSONResponse ErrorResponse

func (response CreateDevice400JSONResponse) VisitCreateDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateDevice500JSONResponse ErrorResponse

func (response CreateDevice500JSONResponse) VisitCreateDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceIpsRequestObject struct {
	Id int64 `json:"id"`
}

type GetDeviceIpsResponseObject interface {
	VisitGetDeviceIpsResponse(w http.ResponseWriter) error
}

type GetDeviceIps200JSONResponse []DeviceIP

func (response GetDeviceIps200JSONResponse) VisitGetDeviceIpsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceIps400JSONResponse ErrorResponse

func (response GetDeviceIps400JSONResponse) VisitGetDeviceIpsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceIps404JSONResponse ErrorResponse

func (response GetDeviceIps404JSONResponse) VisitGetDeviceIpsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceIps500JSONResponse ErrorResponse

func (response GetDeviceIps500JSONResponse) VisitGetDeviceIpsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AddDeviceIpRequestObject struct {
	Id   int64 `json:"id"`
	Body *AddDeviceIpJSONRequestBody
}

type AddDeviceIpResponseObject interface {
	VisitAddDeviceIpResponse(w http.ResponseWriter) error
}

type AddDeviceIp201JSONResponse DeviceIP

func (response AddDeviceIp201JSONResponse) VisitAddDeviceIpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type AddDeviceIp400JSONResponse ErrorResponse

func (response AddDeviceIp400JSONResponse) VisitAddDeviceIpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AddDeviceIp404JSONResponse ErrorResponse

func (response AddDeviceIp404JSONResponse) VisitAddDeviceIpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AddDeviceIp500JSONResponse ErrorResponse

func (response AddDeviceIp500JSONResponse) VisitAddDeviceIpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DisableDeviceIpRequestObject struct {
	Id   int64 `json:"id"`
	IpId int64 `json:"ip_id"`
}

type DisableDeviceIpResponseObject interface {
	VisitDisableDeviceIpResponse(w http.ResponseWriter) error
}

type DisableDeviceIp200JSONResponse DeviceIP

func (response DisableDeviceIp200JSONResponse) VisitDisableDeviceIpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DisableDeviceIp400JSONResponse ErrorResponse

func (response DisableDeviceIp400JSONResponse) VisitDisableDeviceIpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DisableDeviceIp404JSONResponse ErrorResponse

func (response DisableDeviceIp404JSONResponse) VisitDisableDeviceIpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DisableDeviceIp409JSONResponse ErrorResponse

func (response DisableDeviceIp409JSONResponse) VisitDisableDeviceIpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type DisableDeviceIp500JSONResponse ErrorResponse

func (response DisableDeviceIp500JSONResponse) VisitDisableDeviceIpResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all devices
	// (GET /devices)
	GetDevices(ctx context.Context, request GetDevicesRequestObject) (GetDevicesResponseObject, error)
	// Create a device
	// (POST /devices)
	CreateDevice(ctx context.Context, request CreateDeviceRequestObject) (CreateDeviceResponseObject, error)
	// Get IPs for a device
	// (GET /devices/{id}/ips)
	GetDeviceIps(ctx context.Context, request GetDeviceIpsRequestObject) (GetDeviceIpsResponseObject, error)
	// Assign IP to device
	// (POST /devices/{id}/ips)
	AddDeviceIp(ctx context.Context, request AddDeviceIpRequestObject) (AddDeviceIpResponseObject, error)
	// Disable device IP
	// (PATCH /devices/{id}/ips/{ip_id}/disable)
	DisableDeviceIp(ctx context.Context, request DisableDeviceIpRequestObject) (DisableDeviceIpResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetDevices operation middleware
func (sh *strictHandler) GetDevices(w http.ResponseWriter, r *http.Request) {
	var request GetDevicesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDevices(ctx, request.(GetDevicesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDevices")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDevicesResponseObject); ok {
		if err := validResponse.VisitGetDevicesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDevice operation middleware
func (sh *strictHandler) CreateDevice(w http.ResponseWriter, r *http.Request) {
	var request CreateDeviceRequestObject

	var body CreateDeviceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDevice(ctx, request.(CreateDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDeviceResponseObject); ok {
		if err := validResponse.VisitCreateDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDeviceIps operation middleware
func (sh *strictHandler) GetDeviceIps(w http.ResponseWriter, r *http.Request, id int64) {
	var request GetDeviceIpsRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDeviceIps(ctx, request.(GetDeviceIpsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDeviceIps")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDeviceIpsResponseObject); ok {
		if err := validResponse.VisitGetDeviceIpsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddDeviceIp operation middleware
func (sh *strictHandler) AddDeviceIp(w http.ResponseWriter, r *http.Request, id int64) {
	var request AddDeviceIpRequestObject

	request.Id = id

	var body AddDeviceIpJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddDeviceIp(ctx, request.(AddDeviceIpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddDeviceIp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddDeviceIpResponseObject); ok {
		if err := validResponse.VisitAddDeviceIpResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DisableDeviceIp operation middleware
func (sh *strictHandler) DisableDeviceIp(w http.ResponseWriter, r *http.Request, id int64, ipId int64) {
	var request DisableDeviceIpRequestObject

	request.Id = id
	request.IpId = ipId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DisableDeviceIp(ctx, request.(DisableDeviceIpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DisableDeviceIp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DisableDeviceIpResponseObject); ok {
		if err := validResponse.VisitDisableDeviceIpResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xXTW/jNhD9K8S0R/kryQZd3bJNWwjdoML20MMiCGbFscytRHJJyokR6L8XpCTLiuVk",
	"2waxb7I8nHnz8d6Ij5CpUitJ0lmIH8FmKyoxPF5xfk1rkVGSfqJvFVnn32qjNBknKNgIfYecG7LhFz1g",
	"qQuCGBbvz6aLy5+mi+ni/AwiWCpTooMYhF5fQARuo72ZdUbIHCJ4mCjUYpIpTjnJCT04gxOHeXC7xkJw",
	"dNQdr+s6AkPfKmGIQ/x5F8Xt1rf68pUyB3UEPxtCR00uBzORWNIwh5SMVRILpldKEkRQ4sNHkrlbQfxu",
	"HkEpZPfz/GlGTxEG72PYGlT7cLKAmd9hgLotny/DxImS9mpYRyD4wFZId7lTayEd5WS8YZfr85gFh9Y0",
	"2oVzOIskfZ08ePB2993pcGHxS/F8EFkVhTeC2JmK/k/xhiP//GCPlrRPb+DsxSL/Yowyn8hqJe3IxJD/",
	"ezjBTSQmlWNLVUk+iu9JHP9KyKXynjjZzAjthJIQt01mKDlLUtbCZiVKzKkk6ZjdWEelDyJciP8XFsXm",
	"WmSsPXrT216lCUSwJmMb54vp3OeoNEnUAmI4n86nC4hAo1uF/GZNNuE5J7eP7zdyDIuCtXZMSOZW1KPy",
	"xUJvm/DG+rp16HvUVDU4P5vPw+Qq6UiGOKh1IbJwdvbV+mCdUAYNdFSGgz8aWkIMP8x6SZ21ejpred7X",
	"G43BTVPuYRp//O6t3v1LEM/FHg7OSMhEOjJe6f4ksybDwoEwHLYqSzQbiOGjsIPy+jYHff4M3ZvbOgKt",
	"7EhrGgVmyCTdtw7YvXCr0KBcrEmyVmiGTdpVbmioRNZ9UHzzasUZWw4jJWonOFBUKMlaKLDLb68s9d4w",
	"LV4NajdD++iaJLgfnIu3HJwPyNm2aCc4tNu5490I7c9sHW2lZfYoeD0T+mWNIRk2DktSy5bKMGRWUyaW",
	"IutDHdCbRNsgawZLcmQ8mgNKm1z7DeFfeBHslnHcbJHh2EU7VX1xh9W3b6d4Sfr9mnfM0b2YX7xd7La/",
	"gofV/GtYzadIHz/t/YQf4NDE8+Ww9F9x3up+kq4vtp8NTu16HFKlv3jok2DK6y+dkavVWItShtaKXIYv",
	"puNtHM/h09k5iQz3Qf8N2vSPKeNn6zKQyVZaK7PF9fak7j+2T5HRV2GefO2ceoHQY3tx9ij0nX9ur1zh",
	"FoIuW+3z/gbN3wzl7lUBLeuuak8lZSgA143VqYhAdChgejimvjv6lv6vxE5SZqssI2uXVVFstj17c6bf",
	"CGuFzLsLQ6C5r/iRmJ2kPbk9mHujtuAaTO+PgQkLQ8iHbTo53WkZ3bUySQ+qjj8W/DRMr0wBMcxQi9l6",
	"AfVt/U8AAAD//y5YuT+xFAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
