// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "apiKeyAuth.Scopes"
	BearerAuthScopes = "bearerAuth.Scopes"
	CookieAuthScopes = "cookieAuth.Scopes"
)

// AddAddressRequest defines model for AddAddressRequest.
type AddAddressRequest struct {
	// Ip IPv4 or IPv6 address
	Ip IPAddress `json:"ip"`
}

// Address defines model for Address.
type Address struct {
	CreatedAt time.Time `json:"created_at"`
	DeviceId  ID        `json:"device_id"`
	Id        ID        `json:"id"`

	// Ip IPv4 or IPv6 address
	Ip IPAddress `json:"ip"`

	// Status The latest state of this address, enabled or disabled
	Status bool `json:"status"`

	// UpdatedAt Last time it was enabled or disabled
	UpdatedAt time.Time `json:"updated_at"`
}

// AuthRequest defines model for AuthRequest.
type AuthRequest struct {
	Password Password `json:"password"`

	// Username Unique username. Alphanumeric, underscores, and hyphens only.
	Username Username `json:"username"`
}

// CreateDeviceRequest defines model for CreateDeviceRequest.
type CreateDeviceRequest struct {
	// Name User-friendly name for the device
	Name string `json:"name"`
}

// CreateDeviceResponse defines model for CreateDeviceResponse.
type CreateDeviceResponse struct {
	// ApiKey Secret key for the device; only returned on creation.
	ApiKey string `json:"api_key"`
	Device Device `json:"device"`
}

// CreateUserRequest defines model for CreateUserRequest.
type CreateUserRequest struct {
	// DisplayName User's public name. Unicode allowed.
	DisplayName DisplayName          `json:"display_name"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	Password    Password             `json:"password"`

	// Username Unique username. Alphanumeric, underscores, and hyphens only.
	Username Username `json:"username"`
}

// Device defines model for Device.
type Device struct {
	// ApiKeyPrefix Prefix of the device API key (for display only).
	ApiKeyPrefix string    `json:"api_key_prefix"`
	CreatedAt    time.Time `json:"created_at"`
	Id           ID        `json:"id"`

	// Name User-friendly name for the device
	Name string `json:"name"`
}

// DisplayName User's public name. Unicode allowed.
type DisplayName = string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// ID defines model for ID.
type ID = int64

// IPAddress IPv4 or IPv6 address
type IPAddress = string

// Password defines model for Password.
type Password = string

// User defines model for User.
type User struct {
	CreatedAt time.Time `json:"created_at"`

	// DisplayName User's public name. Unicode allowed.
	DisplayName DisplayName          `json:"display_name"`
	Email       *openapi_types.Email `json:"email,omitempty"`
	Id          ID                   `json:"id"`

	// Username Unique username. Alphanumeric, underscores, and hyphens only.
	Username Username `json:"username"`
}

// Username Unique username. Alphanumeric, underscores, and hyphens only.
type Username = string

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = AuthRequest

// CreateDeviceJSONRequestBody defines body for CreateDevice for application/json ContentType.
type CreateDeviceJSONRequestBody = CreateDeviceRequest

// AddAddressJSONRequestBody defines body for AddAddress for application/json ContentType.
type AddAddressJSONRequestBody = AddAddressRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Register a new user (Admin only)
	// (POST /admin/users)
	CreateUser(w http.ResponseWriter, r *http.Request)
	// Login user
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout user
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Get current user
	// (GET /auth/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// List all devices
	// (GET /devices)
	GetDevices(w http.ResponseWriter, r *http.Request)
	// Create a device
	// (POST /devices)
	CreateDevice(w http.ResponseWriter, r *http.Request)
	// Get addresses for a device
	// (GET /devices/{device_id}/addresses)
	GetDeviceAddresses(w http.ResponseWriter, r *http.Request, deviceId int64)
	// Assign address to device
	// (POST /devices/{device_id}/addresses)
	AddAddress(w http.ResponseWriter, r *http.Request, deviceId int64)
	// Disable address
	// (DELETE /devices/{device_id}/addresses/{address_id})
	DisableAddress(w http.ResponseWriter, r *http.Request, deviceId int64, addressId int64)
	// Device heartbeat
	// (POST /devices/{device_id}/heartbeat)
	DeviceHeartbeat(w http.ResponseWriter, r *http.Request, deviceId int64)
	// Performs a heartbeat with the given api key header
	// (POST /heartbeat)
	DeviceHeartbeatByApiKey(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Register a new user (Admin only)
// (POST /admin/users)
func (_ Unimplemented) CreateUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Login user
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout user
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current user
// (GET /auth/me)
func (_ Unimplemented) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all devices
// (GET /devices)
func (_ Unimplemented) GetDevices(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a device
// (POST /devices)
func (_ Unimplemented) CreateDevice(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get addresses for a device
// (GET /devices/{device_id}/addresses)
func (_ Unimplemented) GetDeviceAddresses(w http.ResponseWriter, r *http.Request, deviceId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Assign address to device
// (POST /devices/{device_id}/addresses)
func (_ Unimplemented) AddAddress(w http.ResponseWriter, r *http.Request, deviceId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Disable address
// (DELETE /devices/{device_id}/addresses/{address_id})
func (_ Unimplemented) DisableAddress(w http.ResponseWriter, r *http.Request, deviceId int64, addressId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Device heartbeat
// (POST /devices/{device_id}/heartbeat)
func (_ Unimplemented) DeviceHeartbeat(w http.ResponseWriter, r *http.Request, deviceId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Performs a heartbeat with the given api key header
// (POST /heartbeat)
func (_ Unimplemented) DeviceHeartbeatByApiKey(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDevices operation middleware
func (siw *ServerInterfaceWrapper) GetDevices(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDevices(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDevice operation middleware
func (siw *ServerInterfaceWrapper) CreateDevice(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDevice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDeviceAddresses operation middleware
func (siw *ServerInterfaceWrapper) GetDeviceAddresses(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId int64

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDeviceAddresses(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddAddress operation middleware
func (siw *ServerInterfaceWrapper) AddAddress(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId int64

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddAddress(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DisableAddress operation middleware
func (siw *ServerInterfaceWrapper) DisableAddress(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId int64

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	// ------------- Path parameter "address_id" -------------
	var addressId int64

	err = runtime.BindStyledParameterWithOptions("simple", "address_id", chi.URLParam(r, "address_id"), &addressId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "address_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DisableAddress(w, r, deviceId, addressId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeviceHeartbeat operation middleware
func (siw *ServerInterfaceWrapper) DeviceHeartbeat(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "device_id" -------------
	var deviceId int64

	err = runtime.BindStyledParameterWithOptions("simple", "device_id", chi.URLParam(r, "device_id"), &deviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, CookieAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeviceHeartbeat(w, r, deviceId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeviceHeartbeatByApiKey operation middleware
func (siw *ServerInterfaceWrapper) DeviceHeartbeatByApiKey(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeviceHeartbeatByApiKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/users", wrapper.CreateUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/me", wrapper.GetCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/devices", wrapper.GetDevices)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/devices", wrapper.CreateDevice)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/devices/{device_id}/addresses", wrapper.GetDeviceAddresses)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/devices/{device_id}/addresses", wrapper.AddAddress)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/devices/{device_id}/addresses/{address_id}", wrapper.DisableAddress)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/devices/{device_id}/heartbeat", wrapper.DeviceHeartbeat)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/heartbeat", wrapper.DeviceHeartbeatByApiKey)
	})

	return r
}

type CreateUserRequestObject struct {
	Body *CreateUserJSONRequestBody
}

type CreateUserResponseObject interface {
	VisitCreateUserResponse(w http.ResponseWriter) error
}

type CreateUser201JSONResponse User

func (response CreateUser201JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser400JSONResponse ErrorResponse

func (response CreateUser400JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser403Response struct {
}

func (response CreateUser403Response) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.WriteHeader(403)
	return nil
}

type CreateUser409JSONResponse ErrorResponse

func (response CreateUser409JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateUser500JSONResponse ErrorResponse

func (response CreateUser500JSONResponse) VisitCreateUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200ResponseHeaders struct {
	SetCookie string
}

type Login200JSONResponse struct {
	Body    User
	Headers Login200ResponseHeaders
}

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response.Body)
}

type Login401JSONResponse ErrorResponse

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Login500JSONResponse ErrorResponse

func (response Login500JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204ResponseHeaders struct {
	SetCookie string
}

type Logout204Response struct {
	Headers Logout204ResponseHeaders
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Set-Cookie", fmt.Sprint(response.Headers.SetCookie))
	w.WriteHeader(204)
	return nil
}

type GetCurrentUserRequestObject struct {
}

type GetCurrentUserResponseObject interface {
	VisitGetCurrentUserResponse(w http.ResponseWriter) error
}

type GetCurrentUser200JSONResponse User

func (response GetCurrentUser200JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUser401JSONResponse ErrorResponse

func (response GetCurrentUser401JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetCurrentUser500JSONResponse ErrorResponse

func (response GetCurrentUser500JSONResponse) VisitGetCurrentUserResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDevicesRequestObject struct {
}

type GetDevicesResponseObject interface {
	VisitGetDevicesResponse(w http.ResponseWriter) error
}

type GetDevices200JSONResponse []Device

func (response GetDevices200JSONResponse) VisitGetDevicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDevices500JSONResponse ErrorResponse

func (response GetDevices500JSONResponse) VisitGetDevicesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateDeviceRequestObject struct {
	Body *CreateDeviceJSONRequestBody
}

type CreateDeviceResponseObject interface {
	VisitCreateDeviceResponse(w http.ResponseWriter) error
}

type CreateDevice201JSONResponse CreateDeviceResponse

func (response CreateDevice201JSONResponse) VisitCreateDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateDevice400JSONResponse ErrorResponse

func (response CreateDevice400JSONResponse) VisitCreateDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateDevice500JSONResponse ErrorResponse

func (response CreateDevice500JSONResponse) VisitCreateDeviceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceAddressesRequestObject struct {
	DeviceId int64 `json:"device_id"`
}

type GetDeviceAddressesResponseObject interface {
	VisitGetDeviceAddressesResponse(w http.ResponseWriter) error
}

type GetDeviceAddresses200JSONResponse []Address

func (response GetDeviceAddresses200JSONResponse) VisitGetDeviceAddressesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceAddresses400JSONResponse ErrorResponse

func (response GetDeviceAddresses400JSONResponse) VisitGetDeviceAddressesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceAddresses404JSONResponse ErrorResponse

func (response GetDeviceAddresses404JSONResponse) VisitGetDeviceAddressesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetDeviceAddresses500JSONResponse ErrorResponse

func (response GetDeviceAddresses500JSONResponse) VisitGetDeviceAddressesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AddAddressRequestObject struct {
	DeviceId int64 `json:"device_id"`
	Body     *AddAddressJSONRequestBody
}

type AddAddressResponseObject interface {
	VisitAddAddressResponse(w http.ResponseWriter) error
}

type AddAddress200JSONResponse Address

func (response AddAddress200JSONResponse) VisitAddAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AddAddress201JSONResponse Address

func (response AddAddress201JSONResponse) VisitAddAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type AddAddress400JSONResponse ErrorResponse

func (response AddAddress400JSONResponse) VisitAddAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AddAddress404JSONResponse ErrorResponse

func (response AddAddress404JSONResponse) VisitAddAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type AddAddress500JSONResponse ErrorResponse

func (response AddAddress500JSONResponse) VisitAddAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DisableAddressRequestObject struct {
	DeviceId  int64 `json:"device_id"`
	AddressId int64 `json:"address_id"`
}

type DisableAddressResponseObject interface {
	VisitDisableAddressResponse(w http.ResponseWriter) error
}

type DisableAddress200JSONResponse Address

func (response DisableAddress200JSONResponse) VisitDisableAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DisableAddress400JSONResponse ErrorResponse

func (response DisableAddress400JSONResponse) VisitDisableAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DisableAddress404JSONResponse ErrorResponse

func (response DisableAddress404JSONResponse) VisitDisableAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DisableAddress500JSONResponse ErrorResponse

func (response DisableAddress500JSONResponse) VisitDisableAddressResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeatRequestObject struct {
	DeviceId int64 `json:"device_id"`
}

type DeviceHeartbeatResponseObject interface {
	VisitDeviceHeartbeatResponse(w http.ResponseWriter) error
}

type DeviceHeartbeat200JSONResponse Address

func (response DeviceHeartbeat200JSONResponse) VisitDeviceHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeat201JSONResponse Address

func (response DeviceHeartbeat201JSONResponse) VisitDeviceHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeat400JSONResponse ErrorResponse

func (response DeviceHeartbeat400JSONResponse) VisitDeviceHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeat404JSONResponse ErrorResponse

func (response DeviceHeartbeat404JSONResponse) VisitDeviceHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeat500JSONResponse ErrorResponse

func (response DeviceHeartbeat500JSONResponse) VisitDeviceHeartbeatResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeatByApiKeyRequestObject struct {
}

type DeviceHeartbeatByApiKeyResponseObject interface {
	VisitDeviceHeartbeatByApiKeyResponse(w http.ResponseWriter) error
}

type DeviceHeartbeatByApiKey200JSONResponse Address

func (response DeviceHeartbeatByApiKey200JSONResponse) VisitDeviceHeartbeatByApiKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeatByApiKey201JSONResponse Address

func (response DeviceHeartbeatByApiKey201JSONResponse) VisitDeviceHeartbeatByApiKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeatByApiKey400JSONResponse ErrorResponse

func (response DeviceHeartbeatByApiKey400JSONResponse) VisitDeviceHeartbeatByApiKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeatByApiKey404JSONResponse ErrorResponse

func (response DeviceHeartbeatByApiKey404JSONResponse) VisitDeviceHeartbeatByApiKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeviceHeartbeatByApiKey500JSONResponse ErrorResponse

func (response DeviceHeartbeatByApiKey500JSONResponse) VisitDeviceHeartbeatByApiKeyResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Register a new user (Admin only)
	// (POST /admin/users)
	CreateUser(ctx context.Context, request CreateUserRequestObject) (CreateUserResponseObject, error)
	// Login user
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout user
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Get current user
	// (GET /auth/me)
	GetCurrentUser(ctx context.Context, request GetCurrentUserRequestObject) (GetCurrentUserResponseObject, error)
	// List all devices
	// (GET /devices)
	GetDevices(ctx context.Context, request GetDevicesRequestObject) (GetDevicesResponseObject, error)
	// Create a device
	// (POST /devices)
	CreateDevice(ctx context.Context, request CreateDeviceRequestObject) (CreateDeviceResponseObject, error)
	// Get addresses for a device
	// (GET /devices/{device_id}/addresses)
	GetDeviceAddresses(ctx context.Context, request GetDeviceAddressesRequestObject) (GetDeviceAddressesResponseObject, error)
	// Assign address to device
	// (POST /devices/{device_id}/addresses)
	AddAddress(ctx context.Context, request AddAddressRequestObject) (AddAddressResponseObject, error)
	// Disable address
	// (DELETE /devices/{device_id}/addresses/{address_id})
	DisableAddress(ctx context.Context, request DisableAddressRequestObject) (DisableAddressResponseObject, error)
	// Device heartbeat
	// (POST /devices/{device_id}/heartbeat)
	DeviceHeartbeat(ctx context.Context, request DeviceHeartbeatRequestObject) (DeviceHeartbeatResponseObject, error)
	// Performs a heartbeat with the given api key header
	// (POST /heartbeat)
	DeviceHeartbeatByApiKey(ctx context.Context, request DeviceHeartbeatByApiKeyRequestObject) (DeviceHeartbeatByApiKeyResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateUser operation middleware
func (sh *strictHandler) CreateUser(w http.ResponseWriter, r *http.Request) {
	var request CreateUserRequestObject

	var body CreateUserJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateUser(ctx, request.(CreateUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateUserResponseObject); ok {
		if err := validResponse.VisitCreateUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCurrentUser operation middleware
func (sh *strictHandler) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	var request GetCurrentUserRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCurrentUser(ctx, request.(GetCurrentUserRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCurrentUser")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCurrentUserResponseObject); ok {
		if err := validResponse.VisitGetCurrentUserResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDevices operation middleware
func (sh *strictHandler) GetDevices(w http.ResponseWriter, r *http.Request) {
	var request GetDevicesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDevices(ctx, request.(GetDevicesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDevices")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDevicesResponseObject); ok {
		if err := validResponse.VisitGetDevicesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateDevice operation middleware
func (sh *strictHandler) CreateDevice(w http.ResponseWriter, r *http.Request) {
	var request CreateDeviceRequestObject

	var body CreateDeviceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateDevice(ctx, request.(CreateDeviceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateDevice")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateDeviceResponseObject); ok {
		if err := validResponse.VisitCreateDeviceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDeviceAddresses operation middleware
func (sh *strictHandler) GetDeviceAddresses(w http.ResponseWriter, r *http.Request, deviceId int64) {
	var request GetDeviceAddressesRequestObject

	request.DeviceId = deviceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDeviceAddresses(ctx, request.(GetDeviceAddressesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDeviceAddresses")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDeviceAddressesResponseObject); ok {
		if err := validResponse.VisitGetDeviceAddressesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddAddress operation middleware
func (sh *strictHandler) AddAddress(w http.ResponseWriter, r *http.Request, deviceId int64) {
	var request AddAddressRequestObject

	request.DeviceId = deviceId

	var body AddAddressJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.AddAddress(ctx, request.(AddAddressRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddAddress")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(AddAddressResponseObject); ok {
		if err := validResponse.VisitAddAddressResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DisableAddress operation middleware
func (sh *strictHandler) DisableAddress(w http.ResponseWriter, r *http.Request, deviceId int64, addressId int64) {
	var request DisableAddressRequestObject

	request.DeviceId = deviceId
	request.AddressId = addressId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DisableAddress(ctx, request.(DisableAddressRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DisableAddress")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DisableAddressResponseObject); ok {
		if err := validResponse.VisitDisableAddressResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeviceHeartbeat operation middleware
func (sh *strictHandler) DeviceHeartbeat(w http.ResponseWriter, r *http.Request, deviceId int64) {
	var request DeviceHeartbeatRequestObject

	request.DeviceId = deviceId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeviceHeartbeat(ctx, request.(DeviceHeartbeatRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeviceHeartbeat")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeviceHeartbeatResponseObject); ok {
		if err := validResponse.VisitDeviceHeartbeatResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeviceHeartbeatByApiKey operation middleware
func (sh *strictHandler) DeviceHeartbeatByApiKey(w http.ResponseWriter, r *http.Request) {
	var request DeviceHeartbeatByApiKeyRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeviceHeartbeatByApiKey(ctx, request.(DeviceHeartbeatByApiKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeviceHeartbeatByApiKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeviceHeartbeatByApiKeyResponseObject); ok {
		if err := validResponse.VisitDeviceHeartbeatByApiKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaa2/bOBb9KwR3gOlgZTtuMsXU+2XdembqbaY1mha7QOA1aPHaZiuRKkk58Qb+7ws+",
	"9LKk2J0kTjDolyKVRfI+zjn3ktQNDkWcCA5cKzy4wSpcQUzsn0NKh5RKUOoDfE1BafMwkSIBqRnYV1hi",
	"/v1BwgIP8N96xVQ9P09vPPFz4O02wBK+pkwCxYNLM3YaYL1JAA+wmH+GUONtgLPXa2uFEogGOiPWjoWQ",
	"sfkLU6Kho1kMOJ9Macn40kxGYc1CmDG618yRef3g977F7QArTXRqfaCgQskSzQTHA/xxBSgiGpRG5hVA",
	"YoH0iilE3NgAASfzCCgSElGm7N+Fm3MhIiDcrJAmtBSb6irnRGlkAoSYRldEtUx6SEB3M2jGFSG2ccm9",
	"DcoJq1jYmPVUr1pRlhClroTcm5xJ9p6JiALJSQz7xnzK3tt1Lp8gKNZvsvy19XJko9DqQWZJNTNm7c5C",
	"MuA02iDzDloIifQKkIsqDjBckziJzJITkEpwEqFkJbj5KSbX58CXeoUHP58EOGY8+29/X+asPfu9UYng",
	"CurukITNvsCm7tEFhBI0+gKbHU/+gQSPNkiCTiU32OPIwoMJ3m0n7r7kOTtr3uXBy+xs99SkoDVrlKkk",
	"IpvZITgauXffWSgFGGLCIjOmyJ8B1D/9f7uhiMucc683xOGxoV8JwR4mjPKcNaJllkhYsOs6aCb2uRO/",
	"DC9oOBlbGD1bOJkyVlgM/dSIlz9THA5V+z9P3jsw1Oqpj3pFSHei2ZiIEhYb7f5RoSSdRyy0dnfRJ85C",
	"QQGRKBJXQLsV3fmXWHE0Et/qT4B/lVLIdhEB83OVIj73XGi0ECmnjRWo5u54VMk54/rFWTGScQ1LkPbF",
	"Sam5IHzzfoEHl+WRyfqsASjVN17U35gGOzEeT9ZnpryOJ+sXWTGvxLT/8nm3/+KXbr/bP33ehM1Jifel",
	"Yc9Ph05i899LIpIUz9oT9UvDYgYS99Rv3YNi7hfFQ4l7ZyG0JGxXw1KEmmj4qbT8Dgc5+5oCymbuomGU",
	"rAhPY5AsDFDKKUgVCgkqQIRTtNokK+DK6l+VnJ/Fis/oLjlPn1dyfmqEW2uQZu3/XpLO/046L2ed6d9/",
	"aCSYgjCVTG8uTHhyCX8LG9Ok1Z3JlNoKtSMwSfUKuGahLfDoGXSXXbQCIvUciP7JdIpm5AoIBZnp3AD/",
	"pzOcjDtvYVOY5Ra2Ci/EFwaZCXa8e1SMn83eCKU7VzScKVDKmFebyDjI+ELU/Rh52zlF40nGWhQTTpYQ",
	"A9dIbZQGU7Y10zb4/yZRtBmxEPmhfxTvDidjHOA1SOUm73dPjBMiAU4Shgf4tHvS7duKqlc2xD1CY8Z7",
	"BhOu6RWqoZl3XYtCBHG4sgBCJAxFyrXBhaGvDfmY5u9acjtYg9KvBLVtWyi4Bq5dbpPIZ6r3WZlVsl3g",
	"Pt7UW6htlUFapmAfuBpg/Xp+0r83A6xvds16jUOenUilYQhKLdIoskA6Ozm5NwOqJa7BkleEojw4Zu3T",
	"ek5/E3LOKAWOOui96ZItEhQKiW+SnVIoN8HL4xmfCZgpZVaMEYkkEGr6+CVTGkyStwH++ZgRHXMjZCRC",
	"FyDXIJEd4HQrjWMiN3iAP3jzyjR5NjRRdS2k4TBZKiPxNtZ4asb3jGz1IrFkvJ2Aw0LaQHkCcooUaENK",
	"o6KhRm8+fpx07IbH6xByUlXn6Lld7WHoWd5TH0TMkwcn5rlYLoEixqusDHwpsHZcgO68dspeWW+3UG0t",
	"HfrHRN6aRIwaTlIDARKpp4R+X7Xx4HJa5oJFmAVqGfWmjFZBL1LdjnrvusW82eEcAGszXw1hZw3HUw4S",
	"ItX3gontju9m3j3Ouw5tCQ1+f7DnFc7nMJUSuDb6XNIAamf/USEKmrBI1WPxO+jXbmheio/MOr+8Uytv",
	"Jz42e94JXQ3ck6wcv4POEn0LbFybq1phY2YhUeTbYYXmEAm+ZHyJtLBYqiOoETcjv84dMcM0xOrQs7Si",
	"Y5aSbJri+P7tk0zdOVOVqJdSlz2ZboNb+2rfL/hdTHacc0iyyuemD9ptVw+aG0Ll9yLZ6SrypuBj9uWN",
	"p8hNwuRa9Mfuyp8clHM05ieJdSSXdKh3k1/CbHt+43qAOmX3QPkIi3iCVAIhW7DQr36LMg3ztcxGVpIY",
	"tC3Yly176zHNtv5m21ts3Mt3SFWUBqWw7z3h206PIZSli73DlPJxN5xnx1vbZ5lRe4L7mz3BfapFfhf0",
	"NaYVPGqvGkNKfcnIjou0yOeq86a4UD+QL+wYfHmAjWftw4GGRPk3EFGKLbk9NDu8VJ3cp63+64R2C/2h",
	"B1wzpYEWt/Luptvs/Q3M77OA3mLVY9XMbPebId2j65E0prgieooCM7SYLovCrfKyt5T3bvyf5rGToQh0",
	"w8XCyH3P4TaspUyVriXrsuQHfZs0PXQpD25a2NimiUWEHrmJuKPalA9Biu9zjs32P5hSZr9K85JuqmSR",
	"gmPTPotOcceUK0D3SUqAJ1Xp9vdbmJ/flbUfyXkeSkiE1AoxrfKDi+L6qot+vdaShNofYUXM/76QIraP",
	"fM21h9jAVSrBzIVY/plY17aTzDwfTsboo/gC3KThwh0BNsiJNexN7sFfY2twR1b7YB6xT3hX6kqzqzCX",
	"5MdRlKx/KN2tfm8hbtEPZ+SqRKPmM4ADpOKCxICIQrdLDZqnevfmnimUSLFmFChaM4JIwjr1j/tMg+O+",
	"79wnBq82Q3cP/52N39n49NlYXKlVP4G5nG4rd2wTkCZ6CpGCsOiK6ZUlyZKtgRvq2M9k8o9eGui8u2b5",
	"m5fLqemJ50AkyIoV1mpXWVMZ4QHukYT11n28nW7/HwAA//+rjiNj3i8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
